<?php
/**$
    License - pt_PT
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:47
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'your_licenses' => 'Suas licenças',
  'max_domains' => 'Não. Domínios permitidos',
  'max_customers' => 'Nº de Clientes Autorizados',
  'your_domains' => 'Seus domínios autorizados',
  'serverstatus' => 'Status do servidor',
  'add2' => 'Adicionar',
  'upgradenow' => 'Atualize sua licença agora',
  'upgradedays' => '%dias% dias oferecidos',
  'reset2' => 'Repor',
  'automaticrenewal' => 'Renovação automática',
  'manualrenewal' => 'Renovação Manual',
  'licenseexpired' => 'Aviso: Sua licença expirou para continuar usando CLIENTXCMS, renove sua chave de licença.',
  'ordernow' => 'Encomendar agora',
  'ordernow2' => 'Encomende sua licença CLIENTXCMS a partir de 9,99 € /mês',
  'checkoutpage.modules.modulechoose2' => 'Você pode escolher <b>contar</b> complementos para sua oferta',
  'checkoutpage.modules.primarymodule' => 'Primeiro módulo',
  'checkoutpage.modules.secondarymodule' => 'Segundo Módulo',
  'checkoutpage.modules.tertiarymodule' => 'Terceiro Módulo',
  'checkoutpage.modules.canchangemodule' => 'Você poderá alterar seus módulos na próxima renovação',
  'checkoutpage.modules.canchange' => 'Você ainda poderá alterar este domínio após a compra',
  'checkoutpage.modules.canchange2' => 'Você ainda poderá alterar este domínio após a renovação',
  'checkoutpage.modules.modulechoose3' => 'Os módulos adquiridos com a licença são vitalícios',
  'checkoutpage.modules.modulechoose' => 'Escolha um complemento',
  'checkoutpage.installation.title' => 'Instalação',
  'checkoutpage.installation.subtitle' => 'Nossa equipe irá configurar sua área de cliente para você assim que você receber seu pedido.',
  'licensechecker' => 'Verificação de licença',
  'licencepage.reset' => 'As chaves de licença foram redefinidas com êxito.',
  'licencepage.reinstall' => 'Redefinição de tokens com êxito',
  'licencepage.save' => 'Informações modificadas com êxito.',
  'reinstall' => 'Reinstalar',
  'onetimemodule' => 'Módulo vitalício',
  'downloadablefromadmin' => 'Módulo para download da sua área de administração.',
  'experimental.title' => 'Modo Experimental',
  'experimental.help' => 'O modo experimental permite que você tenha recursos com antecedência, mas pode causar bugs, para ser usado com cautela.',
  'downloadmodal.title' => 'O download está pronto na versão %version%',
  'downloadmodal.description' => 'Se reinstalado, o token deve ser redefinido.',
  'downloadmodal.button1' => 'Faça o download do arquivo',
  'downloadmodal.button2' => 'Redefinir token',
  'downloadmodal.button3' => 'Redefinir chave de licença',
  'renewlicense' => 'Renovar Licença',
  'renewmodule' => 'Módulo de Renovação',
];