<?php
/**$
    Proxmox - pt_PT
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:37
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'proxmox.console' => 'Consolar',
  'proxmox.disk' => 'Espaço em disco',
  'proxmox.cores' => 'Copas',
  'proxmox.cpuunits' => 'CPU',
  'proxmox.net' => 'Rede',
  'proxmox.panel.problem' => 'Você tem algum problema com hospedagem?',
  'proxmox.panel.openticket' => 'Abra um ticket!',
  'proxmox.network.title' => 'Rede',
  'proxmox.reboot' => 'Reiniciar',
  'proxmox.snapshots.title' => 'Instantâneos',
  'proxmox.snapshots.remaining' => 'Você fica com %resting% snapshots permitidos.',
  'proxmox.backups.success2' => 'Backup excluído.',
  'proxmox.backups.unauthorized' => 'Não é possível fazer um backup.',
  'proxmox.form.converter.title' => 'Conversor',
  'proxmox.form.converter.mb' => 'Digite seu número em MB',
  'proxmox.form.converter.gb' => 'Digite seu número em GB',
  'proxmox.admin.title' => 'Configuração do Proxmox',
  'proxmox.admin.subtitle' => 'Gerencie suas configurações de oferta.',
  'proxmox.admin.productname' => 'Nome do produto',
  'proxmox.memory' => 'Memória',
  'proxmox.bwlimit' => 'Largura de banda',
  'proxmox.graph' => 'Gráficos',
  'proxmox.unlimited' => 'Ilimitado',
  'proxmox.network.type' => 'Tipo',
  'proxmox.network.link_down' => 'Desligar',
  'proxmox.network.virtio' => 'Virtio',
  'proxmox.network.rate' => 'Baço',
  'proxmox.backups.success3' => 'Backup restaurado.',
  'proxmox.reinstall.title' => 'Reinstalação',
  'proxmox.reinstall.remaining' => 'Restam %restantes% instalações autorizadas.',
  'proxmox.reinstall.limit' => 'Você atingiu o número máximo de desinstalações permitidas.',
  'proxmox.reinstall.success' => 'Instalação.',
  'proxmox.form.restrictions.reinstall' => 'Número de realocações autorizadas',
  'proxmox.form.restrictions.nolimit' => '0 para ilimitado',
  'proxmox.form.restrictions.unauthorized' => '0 para desativar',
  'proxmox.admin.templates.subtitle' => 'Administrar os diferentes modelos Proxmox',
  'proxmox.admin.oses.title' => 'Ousar',
  'proxmox.admin.oses.subtitle' => 'Gerencie os diferentes Proxmox OS',
  'proxmox.os' => 'OSSO',
  'proxmox.template' => 'Modelo do SO',
  'proxmox.offline' => 'extinto',
  'proxmox.online' => 'Iluminado',
  'proxmox.format' => 'Formato do disco',
  'proxmox.size' => 'Tamanho do disco',
  'proxmox.hostname' => 'Anfitrião',
  'proxmox.tasks' => 'Pontos',
  'proxmox.uptime' => 'Disponibilidade',
  'proxmox.cpu' => 'CPU',
  'proxmox.button' => 'Conexão',
  'proxmox.informations' => 'Informação',
  'proxmox.start' => 'Começar',
  'proxmox.stop' => 'Para desativar',
  'proxmox.shutdown' => 'Matar',
  'proxmox.choosehostname' => 'Escolha um nome de host personalizado',
  'proxmox.network.gw' => 'Porta',
  'proxmox.network.gw6' => 'Gateway v6',
  'proxmox.network.ip' => 'Endereço IP',
  'proxmox.network.firewall' => 'Parada de fogo',
  'proxmox.network.mtu' => 'Transferência máxima de interface',
  'proxmox.network.ip6' => 'Endereço IP v6',
  'proxmox.network.name' => 'Nome',
  'proxmox.network.bridge' => 'Ponte',
  'proxmox.network.hwaddr' => 'Endereço MAC',
  'proxmox.snapshots.limit' => 'Você atingiu o número máximo de instantâneos permitidos.',
  'proxmox.snapshots.success' => 'Instantâneo salvo.',
  'proxmox.snapshots.success2' => 'Instantâneo excluído.',
  'proxmox.snapshots.success3' => 'Instantâneo restaurado.',
  'proxmox.snapshots.unauthorized' => 'Você não pode tirar um instantâneo.',
  'proxmox.backups.title' => 'Backups',
  'proxmox.backups.remaining' => 'Você fica %restante% backup(s) permitido(s).',
  'proxmox.backups.limit' => 'Você atingiu o número máximo de backups permitidos.',
  'proxmox.backups.success' => 'Backup salvo.',
  'proxmox.config.title' => 'Proxmox',
  'proxmox.config.subtitle' => 'Administrar os recursos da oferta.',
  'proxmox.form.title' => 'Configuração proxmox',
  'proxmox.form.block' => 'Bloqueio de IP (por exemplo, 123.223.134.XX / 24)',
  'proxmox.form.importertitle' => 'Importador de blocos de IP',
  'proxmox.form.range' => 'Intervalo de IP (Ex: 1-16)',
  'proxmox.form.btn' => 'Importação Rápida',
  'proxmox.form.global.title' => 'Informações Gerais',
  'proxmox.form.restrictions.title' => 'Restrição',
  'proxmox.form.restrictions.snapshot' => 'Número de snapshots permitidos',
  'proxmox.form.restrictions.backup' => 'Número de backups permitidos',
  'proxmox.settings.password' => 'Defina uma senha de root aleatória e envie-a por e-mail no momento da entrega',
  'proxmox.settings.lxcparams' => 'Adicionar parâmetros ao adicionar a rede',
  'proxmox.settings.lxcparamshelp' => 'Exemplo: bridge=vmbr0,',
  'proxmox.settings.sshcommand' => 'Comando executado ao instalar um VPS',
  'proxmox.settings.sshexecutehelp' => 'As variáveis estão disponíveis. Mais informações sobre nossa documentação <a href="%link%"></a>',
  'proxmox.settings.sshexecutehelp2' => 'Se este comando estiver vazio, o comando configurado <a href="/admin/settings#proxmox"> aqui</a> será executado.',
  'proxmox.admin.ipaddress.title' => 'IP de configuração',
  'proxmox.admin.ipaddress.subtitle' => 'Administre os diferentes endereços IP.',
  'proxmox.admin.ipaddress.used' => 'Usado?',
  'proxmox.admin.templates.title' => 'Modelo',
  'proxmox.admin.type' => 'Tipo',
  'proxmox.settings.defaultdisk' => 'Disco padrão a ser alterado',
  'proxmox.settings.vpsprefix' => 'Prefixo de nome de host padrão',
  'proxmox.settings.backupstorage' => 'Servidor de armazenamento de backup',
];