<?php
/**$
    Pterobox - pt_PT
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:37
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'pterobox.cannot.core' => 'Não é possível exceder %limit% de núcleos.',
  'pterobox.cannot.empty' => 'Não é possível definir um valor em branco ou 0',
  'pterobox.panel.disk' => 'Espaço em disco',
  'pterobox.config.subtitle' => 'Gerencie os diferentes recursos da oferta.',
  'pterobox.form.resources.title' => 'Recursos',
  'pterobox.form.resources.servers' => 'Número de servidores que podem ser criados',
  'pterobox.form.resources.cores' => 'Uso da CPU (%)',
  'pterobox.form.features.allocations' => 'Subsídios',
  'pterobox.form.features.backups' => 'Backups',
  'pterobox.form.features.servers' => 'Servidores',
  'pterobox.form.features.cores' => 'Copas',
  'pterobox.form.core.title' => 'Informação',
  'pterobox.form.core.egg' => 'ID Ovo Pterodáctilo',
  'pterobox.cannot.database' => 'Não é possível exceder os bancos de dados %limit%.',
  'pterobox.cannot.backup' => 'Não é possível exceder os backups %limit%.',
  'pterobox.cannot.allocation' => 'Você não pode exceder as alocações %limit%.',
  'pterobox.cannot.server' => 'Você não pode exceder %limit% servidores.',
  'pterobox.adminindex.disk' => 'Espaço em disco',
  'pterobox.adminindex.productname' => 'Nome do produto',
  'pterobox.config.title' => 'Configuração do Servidor',
  'pterobox.form.features.databases' => 'Bancos',
  'pterobox.createserver' => 'Criar um servidor',
  'pterobox.updateserver' => 'Modificar o servidor',
  'pterobox.button' => 'Modificar',
  'pterobox.servername' => 'Nome do servidor',
  'pterobox.used' => 'usado',
  'pterobox.used2' => 'Usado',
  'pterobox.cannot.memory' => 'Não é possível exceder %limit% GB de memória.',
  'pterobox.cannot.disk' => 'Não é possível exceder %limit% GB de espaço em disco.',
  'pterobox.panel.memory' => 'Memória',
  'pterobox.panel.button' => 'Gerenciar meu servidor',
  'pterobox.panel.problem' => 'Você tem algum problema com hospedagem?',
  'pterobox.panel.openticket' => 'Abra um ticket!',
  'pterobox.panel.information' => 'Informações sobre a propriedade',
  'pterobox.panel.backupswisp' => 'Tamanho limite do backup',
  'pterobox.panel.backupswisphelp' => 'O número total de Gigabytes que o servidor pode usar para seus backups.',
  'pterobox.adminindex.title' => 'Configuração Pterobox',
  'pterobox.adminindex.subtitle' => 'Gerencie suas configurações de oferta.',
  'pterobox.adminindex.memory' => 'Memória',
  'pterobox.form.resources.memory' => 'Memória (GB)',
  'pterobox.form.resources.disk' => 'Espaço (GB)',
  'pterobox.form.resources.help' => 'Disponível para toda a caixa',
  'pterobox.form.resources.portrange' => 'Porta a ser atribuída ao servidor (exemplo: 3000-4000)',
  'pterobox.form.resources.cpu' => 'Limite de CPU (%)',
  'pterobox.form.resources.swap' => 'Trocar',
  'pterobox.form.resources.swaphelp' => '0 desativará a troca para o servidor. -1 não permitirá limitação',
  'pterobox.form.resources.io' => 'Bloco de E/S',
  'pterobox.form.features.title' => 'Características',
  'pterobox.form.core.nest' => 'ID Ninho Pterodáctilo',
  'pterobox.form.core.location' => 'ID Localização Pterodáctilo',
];