<?php
/**$
    Pterodactyl - pt_PT
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'pterodactyl.failed.pwdempty' => 'A senha não deve estar em branco',
  'pterodactyl.failed.linkserver' => 'Falha na alteração de senha porque o servidor vinculado não existe',
  'pterodactyl.failed.retrieveuser' => 'Falha na recuperação do usuário, código de erro recebido: %status_code%',
  'pterodactyl.failed.changepwd' => 'Falha na alteração de senha, código de erro recebido: %status_code%',
  'pterodactyl.panel.problem' => 'Você tem algum problema com hospedagem?',
  'pterodactyl.panel.openticket' => 'Abra um ticket!',
  'pterodactyl.panel.information' => 'Informações sobre a propriedade',
  'pterodactyl.panel.start' => 'Começar',
  'pterodactyl.form.resources.disk' => 'Espaço em disco (MB)',
  'pterodactyl.form.resources.swap' => 'Trocar',
  'pterodactyl.form.resources.swaphelp' => '0 desativará a troca para o servidor. -1 não permitirá limitação',
  'pterodactyl.form.resources.io' => 'Bloco de E/S',
  'pterodactyl.form.configurations.image' => 'Docker de imagens',
  'pterodactyl.form.configurations.startup' => 'Comando Iniciar',
  'pterodactyl.form.configurations.oomkiller' => 'Desativar o OOM Killer',
  'pterodactyl.form.configurations.dedicatedip' => 'Endereço IP dedicado',
  'pterodactyl.failed.unsuspendexist' => 'Falha na dessuspensão do servidor porque ele não existe.',
  'pterodactyl.failed.terminateexist' => 'Falha ao excluir o servidor porque ele não existe.',
  'pterodactyl.failed.satisfying' => 'Não é possível encontrar nós que satisfaçam a demanda',
  'pterodactyl.panel.disk' => 'Espaço em disco',
  'pterodactyl.panel.memory' => 'Memória',
  'pterodactyl.panel.button' => 'Gerenciar meu servidor',
  'pterodactyl.config.subtitle' => 'Gerencie os diferentes recursos da oferta.',
  'pterodactyl.form.resources.title' => 'Recursos',
  'pterodactyl.form.resources.memory' => 'Memória (MB)',
  'pterodactyl.form.core.nest' => 'ID Ninho Pterodáctilo',
  'pterodactyl.form.core.location' => 'ID Localização Pterodáctilo',
  'pterodactyl.form.configurations.title' => 'Configuração',
  'pterodactyl.offline' => 'extinto',
  'pterodactyl.online' => 'Iluminado',
  'pterodactyl.failed.alreadycreated' => 'Falha na criação do servidor porque ele já está criado',
  'pterodactyl.failed.changepkgexist' => 'Falha ao alterar o pacote do servidor porque ele não existe',
  'pterodactyl.failed.suspendexist' => 'Falha ao suspender o servidor porque ele não existe.',
  'pterodactyl.failed.createuser' => 'Falha na criação do usuário, código de erro recebido: %status_code%',
  'pterodactyl.failed.geteggs' => 'Falha ao obter dados do ovo, código de erro recebido: %status_code%',
  'pterodactyl.failed.getserver' => 'Falha ao obter dados para o servidor, código de erro recebido: %status_code%',
  'pterodactyl.failed.createserver' => 'Falha na criação do servidor, código de erro recebido: %status_code%',
  'pterodactyl.failed.suspendserver' => 'Falha na suspensão do servidor, código de erro recebido: %status_code%',
  'pterodactyl.failed.unsuspendserver' => 'Falha na suspensão do servidor, código de erro recebido: %status_code%',
  'pterodactyl.failed.terminateserver' => 'Falha na exclusão do servidor, código de erro recebido: %status_code%',
  'pterodactyl.failed.buildserver' => 'Falha na atualização da versão do servidor, código de erro recebido: %status_code%',
  'pterodactyl.failed.startupserver' => 'Falha na atualização de inicialização do servidor, código de erro recebido: %status_code%',
  'pterodactyl.panel.stop' => 'Desligar',
  'pterodactyl.panel.powerstop' => 'Matar',
  'pterodactyl.panel.restart' => 'Reiniciar',
  'pterodactyl.adminindex.title' => 'Configuração do pterodáctilo',
  'pterodactyl.adminindex.subtitle' => 'Gerencie suas configurações de oferta.',
  'pterodactyl.adminindex.memory' => 'Memória',
  'pterodactyl.adminindex.disk' => 'Espaço em disco',
  'pterodactyl.adminindex.productname' => 'Nome do produto',
  'pterodactyl.config.title' => 'Configuração do Servidor',
  'pterodactyl.form.resources.portrange' => 'Porta a ser atribuída ao servidor (exemplo: 3000-4000)',
  'pterodactyl.form.resources.cpu' => 'Limite de CPU (%)',
  'pterodactyl.form.features.title' => 'Características',
  'pterodactyl.form.features.databases' => 'Bancos de dados a serem atribuídos ao servidor',
  'pterodactyl.form.features.allocations' => 'Alocações adicionais a serem alocadas ao servidor',
  'pterodactyl.form.features.backups' => 'Backups de dados a serem atribuídos ao servidor',
  'pterodactyl.form.core.title' => 'Informação',
  'pterodactyl.form.core.servername' => 'Nome do servidor',
  'pterodactyl.form.core.egg' => 'ID Ovo Pterodáctilo',
];