<?php
/**$
    Support - pt_PT
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:39
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'department' => 'Departamento',
  'support.related' => 'Serviço/Transação Relacionado',
  'support.admin.department.title' => 'Departamento',
  'support.admin.department.subtitle' => 'Administrar os diferentes departamentos de suporte',
  'support.show.our_reply' => 'Nossa resposta',
  'support.show.your_reply' => 'Sua resposta',
  'support.priority' => 'Prioridade',
  'support.priorities.High' => 'Alto',
  'support.priorities.Medium' => 'Média',
  'support.priorities.Low' => 'Fraco',
  'departments' => 'Departamentos',
  'your_tickets' => 'Seus pedidos',
  'new_ticket' => 'Nova aplicação',
  'reply' => 'Responder',
  'open_tickets' => 'Solicitações em aberto',
  'predefinedreplies' => 'Respostas predefinidas',
  'predefinedreply' => 'Resposta predefinida',
  'support.actions.close' => 'O pedido acaba de ser encerrado',
  'support.actions.reply' => 'A resposta acaba de ser postada',
  'support.table.last_updated' => 'Última atualização',
  'support.table.close' => 'Fechar',
  'support.table.priority' => 'Prioridade',
  'support.table.department' => 'Departamento',
  'support.table.subject' => 'Assunto',
  'support.admin.ticket.createsubtitle' => 'Abra um ticket para um cliente específico.',
  'support.email.title' => 'Resposta do nosso suporte para solicitar %subject%',
  'support.email.content' => 'Nosso suporte acaba de responder ao seu pedido de ajuda. Você pode visualizá-lo clicando no botão acima.',
  'support.email.button' => 'Meu Ingresso',
  'support.show.reopentext' => 'Seu aplicativo está fechado no momento, você pode reabri-lo clicando no botão.',
  'support.show.reopen' => 'Reabra o aplicativo',
  'support.show.your_question' => 'Sua consulta',
  'support.department' => 'Departamento',
  'support.discussion' => 'Discussão',
  'support.content' => 'Pedir',
  'support.newticket' => 'Novo Bilhete',
  'support.submit' => 'Para enviar',
  'tickets' => 'Bilhetes',
  'support.title' => 'Suporte técnico',
  'support.messages' => 'Mensagens',
  'support.replied' => 'Respondeu a você',
  'support.icon' => 'Ícone',
  'support.informations' => 'Notícia',
  'support.actions.reopen' => 'O aplicativo acaba de ser reaberto.',
  'support.actions.submit' => 'O aplicativo acaba de ser aberto',
  'support.admin.predefined.title' => 'Respostas predefinidas',
  'support.admin.predefined.create' => 'Você pode criar respostas enlatadas <a href="%route%" target="_blank"></a> aqui',
  'support.admin.predefined.subtitle' => 'Administrar as várias respostas predefinidas do suporte',
  'support.admin.predefined.global' => 'A resposta pode estar disponível para todos os funcionários',
  'support.admin.predefined.tips' => '<strong>[SOBRENOME]</strong> - Nome do Cliente | <strong>[NOME]</strong> - Nome do Cliente | <strong>[EMAIL]</strong> - E-mail do Cliente |  <strong>[RELACIONADO]</strong> Nome da transação/serviço relacionado (se definido)',
  'support.admin.ticket.title' => 'Apoio',
  'support.admin.ticket.subtitle' => 'Gerenciar os vários tickets de suporte',
  'support.show.reply' => 'Responder',
  'support.show.textarea' => 'Por favor, explique o seu problema tanto quanto possível. 
Não forneça nenhuma informação confidencial (senhas, etc.), nossos técnicos têm todas as informações necessárias para resolver seu problema',
  'support.states.Pending' => 'Pendente',
  'support.states.Reply Support' => 'Resposta do Suporte',
  'support.states.Reply Customer' => 'Resposta do cliente',
  'support.states.Closed' => 'Fechado',
  'support.print' => 'Imprimir',
  'support.admin' => 'Funcionários a serem notificados por e-mail',
  'servicespage.options.manage' => 'Precisa de um IP extra ou mais espaço em disco?',
];