<?php
/**$
    translator - pt_PT
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:45
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'translatesitems.positive' => 'O valor deve ser positivo.',
  'translatesitems.numeric' => 'O valor deve ser um numérico válido.',
  'translatesitems.between' => 'O valor deve estar entre %d e %d.',
  'translatesitems.inArray' => 'O valor não existe nestes valores: %s',
  'translatesitems.notInArray' => 'O valor não deve existir nestes valores: %s',
  'translatesitems.arrayHasKey' => 'A matriz deve conter a chave %s',
  'translatesitems.unique' => 'O valor deve ser exclusivo no banco de dados',
  'translatesitems.arrayHasNotKey' => 'A matriz não deve conter a chave %s',
  'translatesitems.filetype' => 'O campo não é um formato validado (%s)',
  'translatesitems.maxLength' => 'O valor deve conter menos de %d caracteres.',
  'translatesitems.betweenLength' => 'O valor deve conter entre %d e %d caracteres.',
  'translatesitems.bannedEmail' => 'O endereço de e-mail ou nome de domínio é proibido.',
  'translatesitems.email' => 'O valor deve ser um e-mail válido.',
  'translatesitems.invalidip' => 'o valor deve ser um endereço IP validado.',
  'translatesitems.url' => 'O valor deve ser uma URL verificada.',
  'translatesitems.domain' => 'O valor deve ser um domínio válido.',
  'translatesitems.equals' => 'O valor deve ser igual à sua validação.',
  'translatesitems.ispassword' => 'A senha deve ser a atual.',
  'translatesitems.isfuture' => 'A data deve ser no futuro.',
  'translatesitems.startswith' => 'O valor deve começar com %s.',
  'translatesitems.endswith' => 'O valor deve terminar com %s.',
  'translatesitems.contains' => 'O valor deve conter %s',
  'translatesitems.notcontains' => 'O valor não deve conter %s',
  'translatesitems.passwordsecurity' => 'Sua senha não é segura! Por favor, use um diferente',
  'translatesitems.sshpublic' => 'A chave SSH deve ser uma chave válida',
  'translatesitems.boolean' => 'O valor deve ser um Booleano validado.',
  'translatesitems.int' => 'O valor deve ser um número validado.',
  'translatesitems.negative' => 'O valor deve ser negativo.',
  'translatesitems.max' => 'O número deve ser menor que %d',
  'translatesitems.min' => 'O número deve ser pelo menos %d',
  'translatesitems.minLength' => 'O valor deve conter mais de %d caracteres.',
  'translatesitems.license' => 'Esta licença é inválida %s',
  'translatesitems.exists' => 'O valor deve existir no banco de dados.',
  'translatesitems.ispast' => 'A data deve estar no passado.',
  'translatesitems.true' => 'O valor deve ser verdadeiro.',
  'translatesitems.false' => 'O valor deve ser false.',
  'translatesitems.uploaded' => 'Você precisa fazer upload de um arquivo.',
  'translatesitems.required' => 'O valor deve ser obrigatório.',
  'translatesitems.empty' => 'O valor não pode estar vazio.',
  'translatesitems.slug' => 'O valor deve ser um slug válido.',
  'translatesitems.phonenumber' => 'O valor deve ser um número de telefone válido.',
  'translatesitems.postcode' => 'O valor deve ser um código postal verificado (%s).',
  'translatesitems.numericOrZero' => 'O valor deve ser um numérico válido ou igual a zero.',
  'translatesitems.positiveOrZero' => 'O valor deve ser positivo ou igual a zero.',
  'translatesitems.ostemplate' => 'Você tem que escolher entre um modelo ou um sistema operacional.',
  'translatesitems.domainIsAlreadyRegistered' => 'Este domínio já está registrado',
];