<?php
/**$
    VirtualizorCloud - pt_PT
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:42
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'virtualizorcloud.offline' => 'extinto',
  'virtualizorcloud.online' => 'Iluminado',
  'virtualizorcloud.planname' => 'Nome do plano',
  'virtualizorcloud.graph' => 'Gráfico',
  'virtualizorcloud.panel.disk' => 'Espaço em disco',
  'virtualizorcloud.panel.cores' => 'Copas',
  'virtualizorcloud.panel.in' => 'Entrante',
  'virtualizorcloud.panel.out' => 'Extrovertido',
  'virtualizorcloud.form.resources.priority' => 'Prioridade de E/S (OpenVZ)',
  'virtualizorcloud.form.resources.vnc' => 'VNC Habilitado (KVM)',
  'virtualizorcloud.form.resources.speed' => 'Velocidade de rede em KB/s (0GB/s ou vazia sem limite)',
  'virtualizorcloud.form.resources.server' => 'Servidor',
  'virtualizorcloud.form.stockage.space' => 'Espaço em disco (GB)',
  'virtualizorcloud.form.cpu.cores' => 'Copas',
  'virtualizorcloud.form.cpu.units' => 'Unidade',
  'virtualizorcloud.form.cpu.cpu' => '% da CPU',
  'virtualizorcloud.form.ips.internalips' => 'Número de endereços IP internos',
  'virtualizorcloud.form.ips.ips' => 'Número de IPs',
  'virtualizorcloud.admin.title' => 'Virtualizador de configuração',
  'virtualizorcloud.admin.subtitle' => 'Gerencie suas configurações de oferta.',
  'virtualizorcloud.admin.planname' => 'Nome do plano',
  'virtualizorcloud.config.title' => 'Configurar sua oferta',
  'virtualizorcloud.hostname' => 'Anfitrião',
  'virtualizorcloud.os' => 'OSSO',
  'virtualizorcloud.panel.restart' => 'Reiniciar',
  'virtualizorcloud.panel.os_name' => 'OSSO',
  'virtualizorcloud.panel.bandwidth' => 'Largura de banda',
  'virtualizorcloud.panel.ram' => 'CARNEIRO',
  'virtualizorcloud.panel.virt' => 'Virtualização',
  'virtualizorcloud.panel.cpu' => 'CPU',
  'virtualizorcloud.panel.reset' => 'Reinstalação',
  'virtualizorcloud.form.resources.title' => 'Recursos',
  'virtualizorcloud.form.resources.disk' => 'Espaço em disco (GB)',
  'virtualizorcloud.form.resources.io' => 'Bloco de E/S',
  'virtualizorcloud.form.resources.bandwidth' => 'Largura de banda (0GB ou vazio sem limite)',
  'virtualizorcloud.form.resources.inodes' => 'INode (OpenVZ)',
  'virtualizorcloud.form.resources.network_speed' => 'Velocidade da rede em MB/s',
  'virtualizorcloud.form.resources.upload_speed' => 'Velocidade de download em MB/s',
  'virtualizorcloud.form.stockage.title' => 'Armazenamento',
  'virtualizorcloud.form.stockage.ram' => 'MB de RAM (KVM, LXC)',
  'virtualizorcloud.form.stockage.guaranteed' => 'Garantia RAM (MB)',
  'virtualizorcloud.form.stockage.burstable' => 'RAM instável (OpenVZ)',
  'virtualizorcloud.form.configurations.group' => 'Grupo',
  'virtualizorcloud.form.configurations.vnc' => 'VNC',
  'virtualizorcloud.form.ips.ip6subnet' => 'Número de endereços IPv6',
  'virtualizorcloud.form.ips.ip6' => 'Número de endereços IPv6 de sub-rede',
  'virtualizorcloud.productname' => 'Nome do produto',
  'virtualizorcloud.choosehostname' => 'Escolha um nome de host personalizado',
  'virtualizorcloud.panel.button' => 'Conexão',
  'virtualizorcloud.panel.start' => 'Começar',
  'virtualizorcloud.panel.stop' => 'Desligar',
  'virtualizorcloud.panel.powerstop' => 'Matar',
  'virtualizorcloud.panel.usage' => 'Uso',
  'virtualizorcloud.panel.site' => 'Abra o site',
  'virtualizorcloud.panel.information' => 'Informações sobre a propriedade',
  'virtualizorcloud.panel.problem' => 'Você tem algum problema com hospedagem?',
  'virtualizorcloud.panel.openticket' => 'Abra um ticket!',
  'virtualizorcloud.panel.uptime' => 'Disponibilidade',
  'virtualizorcloud.form.resources.ip6' => 'IPv6',
  'virtualizorcloud.form.resources.ip6subnet' => 'Sub-rede IP6',
  'virtualizorcloud.form.resources.ips' => 'IP',
  'virtualizorcloud.form.resources.oses' => 'Ossos disponíveis (separados por vírgulas)',
  'virtualizorcloud.form.resources.internalips' => 'IP interno',
  'virtualizorcloud.form.resources.portrange' => 'Porta a ser atribuída ao servidor (separada por vírgulas)',
  'virtualizorcloud.form.cpu.title' => 'CPU',
  'virtualizorcloud.form.converter.title' => 'Conversor',
  'virtualizorcloud.form.converter.mb' => 'Digite seu número em MB',
  'virtualizorcloud.form.converter.gb' => 'Digite seu número em GB',
  'virtualizorcloud.form.configurations.title' => 'Configuração',
  'virtualizorcloud.form.configurations.server' => 'Servidor',
  'virtualizorcloud.config.subtitle' => 'Administrar os recursos da oferta.',
  'virtualizorcloud.converter.title' => 'Conversor',
  'virtualizorcloud.converter.mb' => 'Digite seu número em MB',
  'virtualizorcloud.converter.gb' => 'Digite seu número em GB',
];