<?php
/**$
    Welcome - pt_PT
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:42
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'why_choose_us' => 'Por que nos escolher?',
  'demonstration' => 'Demonstração',
  'demonstrationcontent' => 'Gostaria de descobrir sua futura área de clientes? Acesse uma versão demo!',
  'community.title' => 'Comunidade',
  'community.twitter.title' => 'Gorjeio',
  'community.twitter.description' => 'Você pode nos seguir no Twitter para ser o primeiro a ser alertado sobre futuras atualizações.',
  'community.twitter.seemore' => 'Veja nossos tweets',
  'themepage.larium.administration.description' => 'Não há necessidade de abrir seu acesso FTP, vá diretamente da administração <span class="text-primary fw-bold">CLIENTXCMS</span> para personalizar seu',
  'themepage.larium.administration.list.position.title' => 'Posições',
  'themepage.larium.administration.list.position.content' => 'Altere as posições dos elementos (seções, menus, controles deslizantes, links de rodapé) com um simples clique.',
  'themepage.larium.administration.list.component.title' => 'Componentes automatizados',
  'themepage.list.visual.title' => 'Sem alterações visuais',
  'themepage.list.visual.content' => 'Seus clientes não veem a diferença entre seu site de comerciante e sua área de cliente.',
  'themepage.list.components.title' => 'Componentes interativos',
  'themepage.list.components.content' => 'Adicionar, editar, alterar a posição dos componentes nas páginas.',
  'pricing.description' => 'Comece a trabalhar com <span class="text-primary font-weight-bold"> CLIENTXCMS </span> e comece seu negócio de hospedagem na web hoje mesmo.',
  'pricing.formuls.hostownserver' => 'Hospedado em seu próprio servidor',
  'pricing.formuls.custom' => 'Personalizável e configurável',
  'pricing.formuls.sourcecode' => 'Código fonte incluído',
  'pricing.formuls.withall' => '%count% Módulos Pagos Grátis',
  'pricing.install.title' => 'Instalação & Configuração',
  'pricing.install.count' => 'por instalação',
  'pricing.embedding.title' => 'Incorporando seu site',
  'pricing.embedding.count' => 'através da integração',
  'pricing.embedding.content' => 'Certifique-se de que a sua área de cliente é idêntica ao seu site sem transição!',
  'pricing.mail.title' => 'Servidor de e-mail',
  'pricing.mail.content' => 'Solicite um servidor SMTP para sua empresa diretamente do CLIENTXCMS.',
  'for.services.notincluded' => 'Módulo complementar',
  'darktheme' => 'Modo Noturno',
  'features.translated.title' => 'Totalmente traduzido',
  'features.configurable.content' => 'Configure seus produtos, servidores e opções para personalizar o CLIENTXCMS ao seu gosto.',
  'features.security.title' => 'Segurança',
  'features.security.content' => 'A CLIENTCMS está em constante evolução e melhorando a segurança a cada dia.',
  'features.support.title' => 'Suporte personalizado',
  'features.support.content' => 'Uma equipe disponível todos os dias para ajudá-lo e tirar suas dúvidas.',
  'home' => 'Recepção',
  'shopmore' => 'Encomendar mais',
  'reload' => 'Recarregar',
  'our_modules' => 'Nossos módulos',
  'decovery_our_modules' => 'Descubra nossos módulos',
  'backtohome' => 'Voltar à página inicial',
  'addthemeandfinish' => 'Adicionar tema & Concluir',
  'why_choose_us_sub' => 'CLIENTXCMS é feito para a nova geração de hosts inovadores. Configuração menos complicada, criação mais rápida.',
  'emailtemplates.title' => 'Nossos modelos de e-mail',
  'emailtemplates.subtitle' => 'Personalize sua área de cliente <span class="text-primary font-weight-bold"> CLIENTXCMS com modelos de e-mail </span> que correspondam à sua empresa',
  'licensecheckerpage.howtouse' => 'Como usar esta ferramenta:',
  'licensecheckerpage.first' => 'Digite <b>apenas</b> o nome de domínio onde CLIENTXCMS está instalado',
  'licensecheckerpage.second' => 'Por exemplo, se houve uma instalação @ https://clients.exemple.com, basta digitar <b>clients.exemple.com</b> como o domínio',
  'licensecheckerpage.third' => 'O domínio não deve incluir o <b>www</b> ou <b>https://</b>.',
  'cookieconsent' => 'Este site utiliza cookies para lhe proporcionar uma experiência de utilizador. Ao usá-lo, você concorda com nosso uso de cookies <a href=\'/\' target=\'_blank\' class=\'text-success h6\'></a>',
  'welcome.heading' => 'Nova Geração de Provedor de Hospedagem',
  'welcome.description' => 'Inicie seu negócio de hospedagem na web com nossas ferramentas.',
  'welcome.refund' => 'Ao enviar este formulário, você concorda com nossos Termos de Venda e Uso.',
  'community.discord.title' => 'Discórdia',
  'community.discord.description' => 'Usamos o Discord para fornecer suporte, bem como para obter seus comentários para que possamos planejar futuras atualizações.',
  'community.discord.seemore' => 'Junte-se ao nosso servidor',
  'themepage.title' => 'Reunimos<br/>
                Seu site e sua área de cliente',
  'themepage.larium.title' => 'Personalizável conforme desejado',
  'themepage.larium.subtitle' => 'Não há necessidade de gerenciar um site de vitrine, <span class="text-primary fw-bold">CLIENTXCMS</span> o inclui com uma instalação de um clique e uma configuração simplificada',
  'themepage.larium.subtitle2' => 'Simplifique sua vida por menos com Larium',
  'themepage.larium.rlt.title' => 'RTL & LTR',
  'themepage.larium.rlt.description' => 'Escolha a posição <span class="text-primary fw-bold"></span>do menu de navegação do cliente nas configurações do tema.',
  'themepage.larium.nightmode.title' => 'Modo Dia e Noite',
  'themepage.larium.nightmode.description' => 'Escolha o modo <span class="text-primary fw-bold">do</span> seu tema Noite ou Dia',
  'themepage.larium.administration.title' => 'Gestão a partir da administração',
  'themepage.larium.administration.list.component.content' => 'Os componentes podem exibir informações dinamicamente, como anúncios ou grupos de produtos.',
  'themepage.larium.administration.list.translation.title' => 'Componentes de tradução',
  'themepage.larium.administration.list.translation.content' => 'Os componentes podem ser traduzidos de acordo com o idioma do usuário.',
  'themepage.larium.administration.list.flex.title' => 'Flexibilidade',
  'themepage.larium.administration.list.flex.content' => 'Adicione quantos menus, seções, redes sociais, controles deslizantes ou links de rodapé desejar.',
  'themepage.larium.administration.list.footer' => 'Gerenciamento de rodapé',
  'themepage.larium.administration.list.sections' => 'Gestão de Seções',
  'themepage.larium.administration.list.menus' => 'Gerenciamento de cardápios',
  'themepage.larium.administration.list.info' => 'Mídias Sociais & Gestão da Informação',
  'themepage.larium.administration.list.sliders' => 'Gerenciamento de controle deslizante na página inicial',
  'themepage.list.synchronization.title' => 'Produtos sincronizados',
  'themepage.list.synchronization.content' => 'Chega de editar suas descrições em dois lugares, tudo está em sincronia.',
  'themepage.list.personalization.title' => 'Personalização',
  'themepage.list.personalization.content' => 'Edite facilmente o menu de navegação ou as redes sociais da sua empresa.',
  'themepage.subtitle' => 'Aproveite um site de apresentação incluído em <span class="text-primary fw-bold">CLIENTXCMS que é fácil de</span> instalar e configurável conforme desejado.',
  'themepage.notincluded' => 'Tema não incluído em nossos planos padrão. <a href=\'/Larium\'>Disponível para compra</a>.',
  'modulesfeatures.title' => 'Nossos módulos oficiais',
  'modulesfeatures.title2' => 'Precisa de mais módulos?',
  'modulesfeatures.description2' => 'Mais módulos <span class="text-primary font-weight-bold"> CLIENTXCMS </span> estão disponíveis na loja!',
  'modulesfeatures.description' => 'Comece a trabalhar com <span class="text-primary font-weight-bold"> CLIENTXCMS e com </span> módulos desenvolvidos por nós para você.',
  'modulesfeatures.button' => 'Documentação Oficial do CLIENTXCMS',
  'modulesfeatures.documentation' => 'Encontre as respostas para todas as suas perguntas facilmente com a nossa documentação!',
  'documentation.title' => 'Documentação',
  'pricing.title' => 'Taxas',
  'pricing.formuls.unlimited' => 'Clientes ilimitados',
  'pricing.formuls.customers' => 'Até %<strong>count%</strong> clientes',
  'pricing.formuls.domain' => '1 Domínio Autorizado',
  'pricing.formuls.nothostownserver' => 'Hospedado em nossos servidores',
  'pricing.formuls.modulesfree' => '<strong>%count%</strong> Módulos Pagos Oferecidos',
  'pricing.formuls.modulefree' => '1 módulo pago gratuito',
  'pricing.formuls.domains' => '%count% Domínios Permitidos',
  'pricing.formuls.support' => '%suporte% suporte incluído',
  'pricing.formuls.nosourcecode' => 'Código fonte não incluído',
  'pricing.formuls.discord' => 'Grade & Salas Privadas em nossa discórdia',
  'pricing.formuls.installation' => 'Instalação por nossa equipe',
  'pricing.formuls.with' => 'contar módulos gratuitos',
  'pricing.formuls.themes' => 'Contar temas oferecidos',
  'pricing.install.dedicated' => 'VPS/Dedicado',
  'pricing.install.content' => 'Garanta uma instalação suave e bem-sucedida e deixe nossa equipe instalar e configurar o CLIENTXCMS para você.',
  'pricing.integration.title' => 'Incorporando seu site',
  'pricing.integration.count' => 'por integração',
  'pricing.integration.content' => 'Certifique-se de que a sua área de cliente é idêntica ao seu site sem transição!',
  'pricing.hosting.title' => 'Hospedagem de sites',
  'pricing.hosting.our_hosting' => 'Nossa hospedagem na web',
  'pricing.hosting.content' => 'Encomende sua hospedagem web para o seu negócio diretamente da CLIENTXCMS.',
  'pricing.reseller.title' => 'Revenda Web',
  'pricing.reseller.content' => 'Encomende um revendedor web para sua empresa diretamente da CLIENTXCMS.',
  'pricing.mailer.title' => 'Servidor de E-mail',
  'pricing.mailer.content' => 'Solicite um servidor SMTP para sua empresa diretamente do CLIENTXCMS.',
  'for.services.included' => 'Disponível para todos',
  'features.translated.content' => 'Todo o CLIENTXCMS é traduzido para vários idiomas, o que possibilita a aquisição de clientes de todo o mundo.',
  'features.developper.title' => 'Desenvolvedor amigável',
  'features.developper.content' => 'Somos bem pesquisados e nossos recursos da comunidade facilitam o desenvolvimento e a personalização do CLIENTXCMS.',
  'features.responsive.content' => 'A área do cliente é adequada para qualquer tipo de tela para melhorar a experiência do usuário.',
  'features.tasks.title' => 'Tarefas agendadas',
  'features.tasks.content' => 'Tarefas recorrentes são realizadas para enviar e-mails ou gerenciar serviços automaticamente.',
  'features.easy.title' => 'Simplismo',
  'features.easy.content' => 'O CMS foi projetado para ser o mais simples e intuitivo possível, adequado para usuários iniciantes e experientes.',
  'features.installation.title' => 'Instalação com 1 clique',
  'features.installation.content' => 'Os módulos podem ser baixados da sua área de administração da sua área de clientes. Isso evita uma instalação complexa.',
  'features.configurable.title' => 'Configurável',
  'features.title' => 'Nossas soluções',
  'features.description' => 'Comece a trabalhar com <span class="text-primary font-weight-bold">CLIENTXCMS</span> que pode fornecer tudo o que você precisa para gerar lucros, adquirir novos clientes e ter uma interface de usuário moderna.',
  'pricing.ctxhosting.title' => 'Oferecemos planos pré-desenhados para provedores de hospedagem',
  'pricing.ctxhosting.content' => 'CTXHosting é a nossa gama de hospedagem de alta qualidade com ofertas projetadas para provedores de hospedagem a partir de <strong>XX € / mês</strong>',
  'pricing.ctxhosting.domain' => 'Nome de domínio .fr comprável',
  'pricing.ctxhosting.included' => 'CLIENTXCMS incluído na oferta & pré-configurado',
  'pricing.ctxhosting.info' => 'Serviços Gerenciados & Ajuda',
  'pricing.ctxhosting.installation' => 'Instalação em até 48 horas úteis',
  'pricing.ctxhosting.start' => 'a partir de XX€/mês',
  'pricing.ctxhosting.addon' => 'Oferecemos ofertas de armazenamento VPS ou PBS HDD para seus clientes.',
];