<?php
/**$
    Wisp - pt_PT
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:43
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'Wisp.failed.linkserver' => 'Falha na alteração de senha porque o servidor vinculado não existe',
  'Wisp.failed.retrieveuser' => 'Falha na recuperação do usuário, código de erro recebido: %status_code%',
  'Wisp.failed.changepwd' => 'Falha na alteração de senha, código de erro recebido: %status_code%',
  'Wisp.panel.openticket' => 'Abra um ticket!',
  'Wisp.panel.information' => 'Informações sobre a propriedade',
  'Wisp.panel.start' => 'Começar',
  'Wisp.form.resources.title' => 'Recursos',
  'Wisp.form.resources.memory' => 'Memória (MB)',
  'Wisp.form.resources.disk' => 'Espaço em disco (MB)',
  'Wisp.form.configurations.title' => 'Configuração',
  'Wisp.form.configurations.image' => 'Docker de imagens',
  'Wisp.form.configurations.startup' => 'Comando Iniciar',
  'Wisp.failed.alreadycreated' => 'Falha na criação do servidor porque ele já está criado',
  'Wisp.failed.changepkgexist' => 'Falha ao alterar o pacote do servidor porque ele não existe',
  'Wisp.failed.suspendexist' => 'Falha ao suspender o servidor porque ele não existe.',
  'Wisp.failed.unsuspendexist' => 'Falha na dessuspensão do servidor porque ele não existe.',
  'Wisp.failed.terminateexist' => 'Falha ao excluir o servidor porque ele não existe.',
  'Wisp.failed.satisfying' => 'Não é possível encontrar nós que satisfaçam a demanda',
  'Wisp.failed.pwdempty' => 'A senha não deve estar em branco',
  'Wisp.failed.suspendserver' => 'Falha na suspensão do servidor, código de erro recebido: %status_code%',
  'Wisp.failed.unsuspendserver' => 'Falha na suspensão do servidor, código de erro recebido: %status_code%',
  'Wisp.failed.terminateserver' => 'Falha na exclusão do servidor, código de erro recebido: %status_code%',
  'Wisp.failed.buildserver' => 'Falha na atualização da versão do servidor, código de erro recebido: %status_code%',
  'Wisp.failed.startupserver' => 'Falha na atualização de inicialização do servidor, código de erro recebido: %status_code%',
  'Wisp.panel.disk' => 'Espaço em disco',
  'Wisp.panel.memory' => 'Memória',
  'Wisp.panel.button' => 'Gerenciar meu servidor',
  'Wisp.panel.problem' => 'Você tem algum problema com hospedagem?',
  'Wisp.adminindex.subtitle' => 'Gerencie suas configurações de oferta.',
  'Wisp.adminindex.memory' => 'Memória',
  'Wisp.adminindex.disk' => 'Espaço em disco',
  'Wisp.adminindex.productname' => 'Nome do produto',
  'Wisp.migrate.title' => 'Migração Wisp',
  'Wisp.migrate.subtitle' => 'Use esta página para migrar suas configurações do Pterodáctilo para o Wisp.',
  'Wisp.migrate.info' => 'Esta ação irá alterar os tipos de produto, migrar as configurações do módulo Pterodáctilo para o módulo Wisp.',
  'Wisp.config.title' => 'Configuração do Servidor',
  'Wisp.config.subtitle' => 'Gerencie os diferentes recursos da oferta.',
  'Wisp.form.features.title' => 'Características',
  'Wisp.form.features.databases' => 'Bancos de dados a serem atribuídos ao servidor',
  'Wisp.form.features.backups' => 'Limite de tamanho de backup (MB)',
  'Wisp.form.features.allocations' => 'Alocação (MB)',
  'Wisp.form.core.title' => 'Informação',
  'Wisp.form.core.servername' => 'Nome do servidor',
  'Wisp.form.core.egg' => 'ID Ovo Wisp',
  'Wisp.form.core.nest' => 'ID Nest Wisp',
  'Wisp.form.core.location' => 'ID Localização Wisp',
  'Wisp.form.converter.gb' => 'Digite seu número em GB',
  'Wisp.offline' => 'extinto',
  'Wisp.online' => 'Iluminado',
  'Wisp.failed.createuser' => 'Falha na criação do usuário, código de erro recebido: %status_code%',
  'Wisp.failed.geteggs' => 'Falha ao obter dados do ovo, código de erro recebido: %status_code%',
  'Wisp.failed.getserver' => 'Falha ao obter dados para o servidor, código de erro recebido: %status_code%',
  'Wisp.failed.createserver' => 'Falha na criação do servidor, código de erro recebido: %status_code%',
  'Wisp.panel.stop' => 'Desligar',
  'Wisp.panel.powerstop' => 'Matar',
  'Wisp.panel.restart' => 'Reiniciar',
  'Wisp.adminindex.title' => 'Configurando o Wisp',
  'Wisp.form.resources.swap' => 'Trocar',
  'Wisp.form.resources.io' => 'Bloco de E/S',
  'Wisp.form.resources.portrange' => 'Porta a ser atribuída ao servidor (separada por vírgulas)',
  'Wisp.form.resources.cpu' => 'Limite de CPU (%)',
  'Wisp.form.configurations.oomkiller' => 'Desativar o OOM Killer',
  'Wisp.form.configurations.dedicatedip' => 'Endereço IP dedicado',
  'Wisp.form.converter.title' => 'Conversor',
  'Wisp.form.converter.mb' => 'Digite seu número em MB',
  'wisp.admin.migratebtn' => 'Área de migração',
];