<?php
/**$
    Proxmox - fr_FR
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'proxmox.console' => 'Console',
  'proxmox.disk' => 'Espace disque',
  'proxmox.cores' => 'Coeurs',
  'proxmox.cpuunits' => 'CPU',
  'proxmox.net' => 'Net',
  'proxmox.panel.problem' => 'Vous avez un problème avec l\'hébergement ?',
  'proxmox.panel.openticket' => 'Ouvrir un ticket!',
  'proxmox.network.title' => 'Réseau',
  'proxmox.reboot' => 'Redémarrer',
  'proxmox.snapshots.title' => 'Snapshots',
  'proxmox.snapshots.remaining' => 'Il vous reste %remaining% snapshots autorisées.',
  'proxmox.backups.success2' => 'Sauvegarde supprimée.',
  'proxmox.backups.unauthorized' => 'Vous ne pouvez pas faire de sauvegarde.',
  'proxmox.form.converter.title' => 'Convertisseur',
  'proxmox.form.converter.mb' => 'Tapez votre chiffre en MB',
  'proxmox.form.converter.gb' => 'Tapez votre chiffre en GB',
  'proxmox.admin.title' => 'Configuration Proxmox',
  'proxmox.admin.subtitle' => 'Administrez les configurations de vos offres.',
  'proxmox.admin.productname' => 'Nom du produit',
  'proxmox.memory' => 'Mémoire',
  'proxmox.bwlimit' => 'Bande passante',
  'proxmox.graph' => 'Graphiques',
  'proxmox.unlimited' => 'Illimité',
  'proxmox.network.type' => 'Type',
  'proxmox.network.link_down' => 'Déconnecter',
  'proxmox.network.virtio' => 'Virtio',
  'proxmox.network.rate' => 'Rate',
  'proxmox.backups.success3' => 'Sauvegarde restaurée.',
  'proxmox.reinstall.title' => 'Réinstallation',
  'proxmox.reinstall.remaining' => 'Il vous reste %remaining% installations autorisées.',
  'proxmox.reinstall.limit' => 'Vous avez atteint le maximum de désinstallations autorisées.',
  'proxmox.reinstall.success' => 'Installation en cours.',
  'proxmox.form.restrictions.reinstall' => 'Nombre de réinstallations autorisées',
  'proxmox.form.restrictions.nolimit' => '0 pour illimité',
  'proxmox.form.restrictions.unauthorized' => '0 pour désactiver',
  'proxmox.admin.templates.subtitle' => 'Administrez les différentes templates Proxmox',
  'proxmox.admin.oses.title' => 'Oses',
  'proxmox.admin.oses.subtitle' => 'Administrez les différents OS Proxmox',
  'proxmox.os' => 'OS',
  'proxmox.template' => 'Modèle OS',
  'proxmox.offline' => 'éteint',
  'proxmox.online' => 'Allumé',
  'proxmox.format' => 'Format du disque',
  'proxmox.size' => 'Taille du disque',
  'proxmox.hostname' => 'Hôte',
  'proxmox.tasks' => 'Taches',
  'proxmox.uptime' => 'Disponibilité',
  'proxmox.cpu' => 'CPU',
  'proxmox.button' => 'Connexion',
  'proxmox.informations' => 'Information',
  'proxmox.start' => 'Démarrer',
  'proxmox.stop' => 'Éteindre',
  'proxmox.shutdown' => 'Tuer',
  'proxmox.choosehostname' => 'Choisir un nom d\'hôte personnalisé',
  'proxmox.network.gw' => 'Passerelle',
  'proxmox.network.gw6' => 'Passerelle v6',
  'proxmox.network.ip' => 'Adresse IP',
  'proxmox.network.firewall' => 'Pare Feu',
  'proxmox.network.mtu' => 'Maximum de transfert de l\'interface',
  'proxmox.network.ip6' => 'Adresse IP v6',
  'proxmox.network.name' => 'Nom',
  'proxmox.network.bridge' => 'Pont',
  'proxmox.network.hwaddr' => 'Adresse MAC',
  'proxmox.snapshots.limit' => 'Vous avez atteint le maximum de snapshots autorisées.',
  'proxmox.snapshots.success' => 'Snapshot enregistrée.',
  'proxmox.snapshots.success2' => 'Snapshot supprimée.',
  'proxmox.snapshots.success3' => 'Snapshot restaurée.',
  'proxmox.snapshots.unauthorized' => 'Vous ne pouvez pas faire de snapshot.',
  'proxmox.backups.title' => 'Sauvegardes',
  'proxmox.backups.remaining' => 'Il vous reste %remaining% sauvegarde (s) autorisées.',
  'proxmox.backups.limit' => 'Vous avez atteint le maximum de sauvegarde autorisés.',
  'proxmox.backups.success' => 'Sauvegarde enregistrée.',
  'proxmox.config.title' => 'Proxmox',
  'proxmox.config.subtitle' => 'Administrez les caractéristiques de l\'offre.',
  'proxmox.form.title' => 'Configuration proxmox',
  'proxmox.form.block' => 'Bloc d\'IP (ex: 123.223.134.XX / 24)',
  'proxmox.form.importertitle' => 'Importateur de bloc d\'IP',
  'proxmox.form.range' => 'Plage IP (Ex: 1-16)',
  'proxmox.form.btn' => 'Importation rapide',
  'proxmox.form.global.title' => 'Informations générales',
  'proxmox.form.restrictions.title' => 'Restriction',
  'proxmox.form.restrictions.snapshot' => 'Nombre de snapshot autorisées',
  'proxmox.form.restrictions.backup' => 'Nombre de backup autorisées',
  'proxmox.settings.password' => 'Définir un mot de passe root aléatoire et l\'envoyer par email lors de la livraison',
  'proxmox.settings.lxcparams' => 'Ajouter des paramètres lors de l\'ajout du réseau',
  'proxmox.settings.lxcparamshelp' => 'Exemple: bridge=vmbr0,',
  'proxmox.settings.sshcommand' => 'Commande executée à l\'installation d\'un VPS',
  'proxmox.settings.sshexecutehelp' => 'Des variables sont disponibles. Plus d\'informations sur notre <a href="%link%">documentation</a>',
  'proxmox.settings.sshexecutehelp2' => 'Si cette commande est vide, la commande configurée <a href="/admin/settings#proxmox">ici</a> va être executée.',
  'proxmox.admin.ipaddress.title' => 'Configuration IP',
  'proxmox.admin.ipaddress.subtitle' => 'Administrez les différentes adresses IP.',
  'proxmox.admin.ipaddress.used' => 'Utilisée ?',
  'proxmox.admin.templates.title' => 'Modèle',
  'proxmox.admin.type' => 'Type',
];