<?php
/**$
    Proxmox - fr_FR
    CLIENTXCMS Translator system - Exported on 2023-07-26 10:57:47
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'proxmox' => [
    'os' => 'OS',
    'template' => 'Modèle OS',
    'offline' => 'éteint',
    'online' => 'Allumé',
    'format' => 'Format du disque',
    'size' => 'Taille du disque',
    'hostname' => 'Hôte',
    'memory' => 'Mémoire',
    'bwlimit' => 'Bande passante',
    'console' => 'Console',
    'disk' => 'Espace disque',
    'cores' => 'Coeurs',
    'cpuunits' => 'CPU',
    'net' => 'Net',
    'tasks' => 'Taches',
    'uptime' => 'Disponibilité',
    'cpu' => 'CPU',
    'button' => 'Connexion',
    'informations' => 'Information',
    'start' => 'Démarrer',
    'stop' => 'Éteindre',
    'shutdown' => 'Tuer',
    'choosehostname' => 'Choisir un nom d\'hôte personnalisé',
    'graph' => 'Graphiques',
    'unlimited' => 'Illimité',
    'panel' => [
      'problem' => 'Vous avez un problème avec l\'hébergement ?',
      'openticket' => 'Ouvrir un ticket!',
    ],
    'network' => [
      'title' => 'Réseau',
      'gw' => 'Passerelle',
      'gw6' => 'Passerelle v6',
      'ip' => 'Adresse IP',
      'firewall' => 'Pare Feu',
      'mtu' => 'Maximum de transfert de l\'interface',
      'ip6' => 'Adresse IP v6',
      'name' => 'Nom',
      'bridge' => 'Pont',
      'hwaddr' => 'Adresse MAC',
      'type' => 'Type',
      'rate' => 'Rate',
      'link_down' => 'Déconnecter',
      'virtio' => 'Virtio',
    ],
    'reboot' => 'Redémarrer',
    'snapshots' => [
      'title' => 'Snapshots',
      'remaining' => 'Il vous reste %remaining% snapshots autorisées.',
      'limit' => 'Vous avez atteint le maximum de snapshots autorisées.',
      'unauthorized' => 'Vous ne pouvez pas faire de snapshot.',
      'success' => 'Snapshot enregistrée.',
      'success2' => 'Snapshot supprimée.',
      'success3' => 'Snapshot restaurée.',
    ],
    'reinstall' => [
      'title' => 'Réinstallation',
      'remaining' => 'Il vous reste %remaining% installations autorisées.',
      'limit' => 'Vous avez atteint le maximum de désinstallations autorisées.',
      'success' => 'Installation en cours.',
    ],
    'backups' => [
      'title' => 'Sauvegardes',
      'remaining' => 'Il vous reste %remaining% sauvegarde (s) autorisées.',
      'limit' => 'Vous avez atteint le maximum de sauvegarde autorisés.',
      'success' => 'Sauvegarde enregistrée.',
      'success2' => 'Sauvegarde supprimée.',
      'success3' => 'Sauvegarde restaurée.',
      'unauthorized' => 'Vous ne pouvez pas faire de sauvegarde.',
    ],
    'config' => [
      'title' => 'Proxmox',
      'subtitle' => 'Administrez les caractéristiques de l\'offre.',
    ],
    'form' => [
      'title' => 'Configuration proxmox',
      'block' => 'Bloc d\'IP (ex: 123.223.134.XX / 24)',
      'importertitle' => 'Importateur de bloc d\'IP',
      'range' => 'Plage IP (Ex: 1-16)',
      'btn' => 'Importation rapide',
      'global' => [
        'title' => 'Informations générales',
      ],
      'restrictions' => [
        'title' => 'Restriction',
        'snapshot' => 'Nombre de snapshot autorisées',
        'reinstall' => 'Nombre de réinstallations autorisées',
        'backup' => 'Nombre de backup autorisées',
        'nolimit' => '0 pour illimité',
        'unauthorized' => '0 pour désactiver',
      ],
      'converter' => [
        'title' => 'Convertisseur',
        'mb' => 'Tapez votre chiffre en MB',
        'gb' => 'Tapez votre chiffre en GB',
      ],
    ],
    'settings' => [
      'password' => 'Définir un mot de passe root aléatoire et l\'envoyer par email lors de la livraison',
      'lxcparams' => 'Ajouter des paramètres lors de l\'ajout du réseau',
      'lxcparamshelp' => 'Exemple: bridge=vmbr0,',
      'sshcommand' => 'Commande executée à l\'installation d\'un VPS',
      'sshexecutehelp' => 'Des variables sont disponibles. Plus d\'informations sur notre <a href="%link%">documentation</a>',
      'sshexecutehelp2' => 'Si cette commande est vide, la commande configurée <a href="/admin/settings#proxmox">ici</a> va être executée.',
    ],
    'admin' => [
      'ipaddress' => [
        'title' => 'Configuration IP',
        'subtitle' => 'Administrez les différentes adresses IP.',
        'used' => 'Utilisée ?',
      ],
      'templates' => [
        'title' => 'Modèle',
        'subtitle' => 'Administrez les différentes templates Proxmox',
      ],
      'oses' => [
        'title' => 'Oses',
        'subtitle' => 'Administrez les différents OS Proxmox',
      ],
      'title' => 'Configuration Proxmox',
      'subtitle' => 'Administrez les configurations de vos offres.',
      'productname' => 'Nom du produit',
      'type' => 'Type',
    ],
  ],
];