<?php
/**$
    Pterodactyl - fr_FR
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'pterodactyl.failed.pwdempty' => 'Le mot de passe ne doit pas être vide',
  'pterodactyl.failed.linkserver' => 'Échec de la modification du mot de passe car le serveur lié n\'existe pas',
  'pterodactyl.failed.retrieveuser' => 'Échec de la récupération de l\'utilisateur, code d\'erreur reçu : %status_code%',
  'pterodactyl.failed.changepwd' => 'Échec de la modification du mot de passe, code d\'erreur reçu : %status_code%',
  'pterodactyl.panel.problem' => 'Vous avez un problème avec l\'hébergement ?',
  'pterodactyl.panel.openticket' => 'Ouvrir un ticket !',
  'pterodactyl.panel.information' => 'Informations sur l\'hébergement',
  'pterodactyl.panel.start' => 'Démarrer',
  'pterodactyl.form.resources.disk' => 'Espace disque (Mo)',
  'pterodactyl.form.resources.swap' => 'Swap',
  'pterodactyl.form.resources.swaphelp' => '0 désactivera le swap pour le serveur. -1 pour un swap illimité',
  'pterodactyl.form.resources.io' => 'Bloc IO',
  'pterodactyl.form.configurations.image' => 'Image Docker',
  'pterodactyl.form.configurations.startup' => 'Commande de lancement',
  'pterodactyl.form.configurations.oomkiller' => 'Désactiver OOM Killer',
  'pterodactyl.form.configurations.dedicatedip' => 'Adresse IP dédiée',
  'pterodactyl.failed.unsuspendexist' => 'Échec de la reprise du serveur car il n\'existe pas.',
  'pterodactyl.failed.terminateexist' => 'Échec de la suppression du serveur car il n\'existe pas.',
  'pterodactyl.failed.satisfying' => 'Impossible de trouver des nœuds satisfaisant la demande',
  'pterodactyl.panel.disk' => 'Espace disque',
  'pterodactyl.panel.memory' => 'Mémoire',
  'pterodactyl.panel.button' => 'Gérer mon serveur',
  'pterodactyl.config.subtitle' => 'Administrez les différentes caractéristiques de l\'offre.',
  'pterodactyl.form.resources.title' => 'Ressources',
  'pterodactyl.form.resources.memory' => 'Mémoire (Mo)',
  'pterodactyl.form.core.nest' => 'ID Nest Pterodactyl',
  'pterodactyl.form.core.location' => 'ID Location Pterodactyl',
  'pterodactyl.form.configurations.title' => 'Configuration',
  'pterodactyl.offline' => 'Éteint',
  'pterodactyl.online' => 'Allumé',
  'pterodactyl.failed.alreadycreated' => 'Échec de la création du serveur car il est déjà créé',
  'pterodactyl.failed.changepkgexist' => 'Échec de la modification du package du serveur car il n\'existe pas',
  'pterodactyl.failed.suspendexist' => 'Echec de la suspension du serveur car il n\'existe pas.',
  'pterodactyl.failed.createuser' => 'Échec de la création de l\'utilisateur, code d\'erreur reçu : %status_code%',
  'pterodactyl.failed.geteggs' => 'Échec de l\'obtention des données sur les œufs, code d\'erreur reçu : %status_code%',
  'pterodactyl.failed.getserver' => 'Échec de l\'obtention des données sur le serveur, code d\'erreur reçu : %status_code%',
  'pterodactyl.failed.createserver' => 'Échec de la création du serveur, code d\'erreur reçu : %status_code%',
  'pterodactyl.failed.suspendserver' => 'Échec de la suspension du serveur, code d\'erreur reçu : %status_code%',
  'pterodactyl.failed.unsuspendserver' => 'Échec de la suspension du serveur, code d\'erreur reçu : %status_code%',
  'pterodactyl.failed.terminateserver' => 'Échec de la suppression du serveur, code d\'erreur reçu : %status_code%',
  'pterodactyl.failed.buildserver' => 'Échec de la mise à jour de la version du serveur, code d\'erreur reçu : %status_code%',
  'pterodactyl.failed.startupserver' => 'Échec de la mise à jour du démarrage du serveur, code d\'erreur reçu : %status_code%',
  'pterodactyl.panel.stop' => 'Eteindre',
  'pterodactyl.panel.powerstop' => 'Forcer l\'arrêt',
  'pterodactyl.panel.restart' => 'Redémarrer',
  'pterodactyl.adminindex.title' => 'Configuration Ptérodactyl',
  'pterodactyl.adminindex.subtitle' => 'Administrez les configurations de vos offres.',
  'pterodactyl.adminindex.memory' => 'Mémoire',
  'pterodactyl.adminindex.disk' => 'Espace disque',
  'pterodactyl.adminindex.productname' => 'Nom du produit',
  'pterodactyl.config.title' => 'Configuration du serveur',
  'pterodactyl.form.resources.portrange' => 'Port à attribuer au serveur (Exemple: 3000-4000)',
  'pterodactyl.form.resources.cpu' => 'Limite du processeur (%)',
  'pterodactyl.form.features.title' => 'Fonctionnalités',
  'pterodactyl.form.features.databases' => 'Bases de données à attribuer au serveur',
  'pterodactyl.form.features.allocations' => 'Allocations supplémentaires à attribuer au serveur',
  'pterodactyl.form.features.backups' => 'Sauvegardes de données à attribuer au serveur',
  'pterodactyl.form.core.title' => 'Information',
  'pterodactyl.form.core.servername' => 'Nom du serveur',
  'pterodactyl.form.core.egg' => 'ID Egg Ptérodactyl',
];
