<?php
/**$
    Pterobox - fr_FR
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'pterobox.cannot.core' => 'Vous ne pouvez pas dépasser %limit% coeurs.',
  'pterobox.cannot.empty' => 'Vous ne pouvez pas mettre une valeur vide ou 0',
  'pterobox.panel.disk' => 'Espace disque',
  'pterobox.config.subtitle' => 'Administrez les différentes caractéristiques de l\'offre.',
  'pterobox.form.resources.title' => 'Ressources',
  'pterobox.form.resources.servers' => 'Nb. de serveur pouvant être créer',
  'pterobox.form.resources.cores' => 'Utilisation du CPU (%)',
  'pterobox.form.features.allocations' => 'Allocations',
  'pterobox.form.features.backups' => 'Sauvegardes',
  'pterobox.form.features.servers' => 'Serveurs',
  'pterobox.form.features.cores' => 'Coeurs',
  'pterobox.form.core.title' => 'Information',
  'pterobox.form.core.egg' => 'ID Egg Ptérodactyl',
  'pterobox.cannot.database' => 'Vous ne pouvez pas dépasser %limit% bases de données.',
  'pterobox.cannot.backup' => 'Vous ne pouvez pas dépasser %limit% sauvegardes.',
  'pterobox.cannot.allocation' => 'Vous ne pouvez pas dépasser %limit% allocations.',
  'pterobox.cannot.server' => 'Vous ne pouvez pas dépasser %limit% serveurs.',
  'pterobox.adminindex.disk' => 'Espace disque',
  'pterobox.adminindex.productname' => 'Nom du produit',
  'pterobox.config.title' => 'Configuration du serveur',
  'pterobox.form.features.databases' => 'Bases de données',
  'pterobox.createserver' => 'Créer un serveur',
  'pterobox.updateserver' => 'Modifier le serveur',
  'pterobox.button' => 'Modifier',
  'pterobox.servername' => 'Nom du serveur',
  'pterobox.used' => 'utilisé',
  'pterobox.used2' => 'utilisés',
  'pterobox.cannot.memory' => 'Vous ne pouvez pas dépasser %limit% Go de mémoire.',
  'pterobox.cannot.disk' => 'Vous ne pouvez pas dépasser %limit% Go d\'espace disque.',
  'pterobox.panel.memory' => 'Mémoire',
  'pterobox.panel.button' => 'Gérer mon serveur',
  'pterobox.panel.problem' => 'Vous avez un problème avec l\'hébergement ?',
  'pterobox.panel.openticket' => 'Ouvrir un ticket !',
  'pterobox.panel.information' => 'Informations sur l\'hébergement',
  'pterobox.panel.backupswisp' => 'Taille de limite de sauvegarde',
  'pterobox.panel.backupswisphelp' => 'Le nombre total de Gigaoctet que le serveur peut utiliser pour ses sauvegardes.',
  'pterobox.adminindex.title' => 'Configuration Pterobox',
  'pterobox.adminindex.subtitle' => 'Administrez les configurations de vos offres.',
  'pterobox.adminindex.memory' => 'Mémoire',
  'pterobox.form.resources.memory' => 'Mémoire (Go)',
  'pterobox.form.resources.disk' => 'Espace (Go)',
  'pterobox.form.resources.help' => 'Disponible pour l\'ensemble de la box',
  'pterobox.form.resources.portrange' => 'Port à attribuer au serveur (Exemple: 3000-4000)',
  'pterobox.form.resources.cpu' => 'Limite du processeur (%)',
  'pterobox.form.resources.swap' => 'Swap',
  'pterobox.form.resources.swaphelp' => '0 désactivera le swap pour le serveur. -1 pour mettre un swap illimité',
  'pterobox.form.resources.io' => 'Bloc IO',
  'pterobox.form.features.title' => 'Fonctionnalités',
  'pterobox.form.core.nest' => 'ID Nest Pterodactyl',
  'pterobox.form.core.location' => 'ID Location Pterodactyl',
];
