<?php
/**$
    Shop - fr_FR
    CLIENTXCMS Translator system - Exported on 2023-08-15 22:16:29
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'active_services' => 'Services actifs',
  'see_product' => 'Voir les produits',
  'active' => 'Activation',
  'percentage' => 'Pourcentage',
  'group' => 'Groupe',
  'discounts' => 'Réductions',
  'servicestate' => [
    'Pending' => 'En attente',
    'Online' => 'En ligne',
    'Terminated' => 'Terminé',
    'Suspended' => 'Suspendu',
    'Expired' => 'Expiré',
    'Refunded' => 'Remboursé',
  ],
  'pdf' => [
    'payable' => 'Net à payer TTC ',
    'title' => 'Facture N° %createdat%-%id%',
    'totalht' => 'Total HT : ',
    'deadline' => 'Date Échéance',
    'qty' => 'Qté',
    'label' => 'Label',
    'totalvat' => 'Total TVA : ',
    'discount' => 'Réduction : ',
    'totalprice' => 'Prix TTC : ',
  ],
  'serviceactions' => [
    'transactions' => [
      'cancel' => 'Transaction annulée.',
      'success' => 'Transaction effectuée avec succès.',
    ],
    'rename' => [
      'length' => 'Le nom du service doit être entre 1 et 100 caractères.',
      'success' => 'Nom de service modifié avec succès.',
    ],
    'password' => [
      'length' => 'Le nom du service doit être au minimum de 9 caractères.',
      'success' => 'Mot de passe modifié avec succès.',
      'error' => 'Impossible de modifier le mot de passe de facturation.',
    ],
    'recurring' => [
      'success' => 'Cycle de facture modifié avec succès.',
      'error' => 'Impossible de modifier le cycle de facturation.',
      'discount' => 'Vous devez attendre la fin de vos %months% cycle(s) pour pouvoir modifier le cycle de facturation.',
    ],
    'renew' => [
      'success' => 'Renouvellement du service effectué avec succès.',
      'cancel' => 'Renouvellement du service annulé.',
      'manage' => 'Payer le renouvellement de votre service.',
      'renewinfo' => 'Ce service expire dans %days% jours. Vous pouvez le renouveler en cliquant sur le bouton ci-dessous pour éviter la coupure du service.',
      'warning' => 'Attention',
      'information' => 'Information',
    ],
  ],
  'servicespage' => [
    'crontab' => 'Si votre service met plus de 3 minutes à se liver, vérifiez que <a href=\'%link%\'>vos tâches CRON</a> tournent correctement.',
    'renewbywallet' => 'Renouveler automatiquement via le portefeuille',
    'renewtitle' => 'Gestion du renouvellement',
    'expire_at' => 'Date d\'expiration',
    'recurringcycle' => 'Cycle de facturation',
    'servicename' => 'Nom du service',
    'title' => 'Gestion de service',
    'subscription' => [
      'title' => 'Annuler l\'abonnement %method%',
      'title2' => 'Réactiver l\'abonnement %method%',
      'subtitle' => 'Nous ne prélèverons plus automatiquement pour renouveler votre service.',
      'last4' => 'Quatre derniers chiffres de la carte',
      'cancel' => 'Votre abonnement de votre service vient d\'être annulé',
      'lastpayment' => 'Votre dernier prélèvement remonte au %date%',
      'uncancel' => 'Votre abonnement de votre service vient d\'être réactiver. La prochaine facturation sera le %date%',
      'addsubscription' => 'Vous pouvez demander un abonnement automatiquement pour ce service. Vous serez débiter le %date% de %price%',
      'makesubscription' => 'S\'abonner',
      'manage' => 'Gérer l\'abonnement',
    ],
    'password' => 'Modifier le mot de passe',
    'subscriptioninfo' => 'Votre service sera renouveler le %date% via un prélèvement automatique de %method%.',
    'removetransactionitem' => 'Retirer la transaction à payer',
    'renewwarning' => 'Une facture est à payer pour continuer l\'abonnement du service. <a href=\'%link%\'>Cliquez ici pour la payer</a>. Après l\'expiration du service il sera impossible d\'utiliser le service.',
    'autoterminate' => 'Fin programmé dans',
    'cannotRenew' => 'Le cycle de limite de service est atteint',
    'suspend_expire' => 'Votre service sera expiré dans %date%. Après cette période le service sera supprimer du serveur.',
    'created_at' => 'Date de création',
    'recurring' => 'Facturation',
    'cycles' => 'Cycles',
    'maxcycles' => 'Nb. max de renouvellement',
    'currentcycle' => 'Nb. actuel de renouvellement',
    'noc' => 'Localisation',
    'price' => 'Prix',
    'changestate' => 'Etat modifié avec succès.',
    'renew' => 'Renouveler',
    'terminate' => 'Terminer',
    'suspend' => 'Suspendre',
    'unsuspend' => 'Réactiver',
    'refund' => 'Rembourser',
    'upgrade' => [
      'title' => 'Amélioration',
      'manage' => 'Passer à l\'offre supérieur pour votre service',
      'actual' => 'Offre actuelle',
      'btn' => 'Passer sur cette offre',
    ],
    'cancel' => [
      'title' => 'Annuler le service',
      'subtitle' => 'Votre service s\'arrêtera le %date%',
      'reason' => 'Raison de l\'annulation',
      'button' => 'Arrêter',
      'uncancelbtn' => 'Reprendre',
      'uncancel' => 'Votre annulation de votre service vient d\'être annulé',
      'cancel' => 'Votre annulation de votre service vient d\'être demandé',
    ],
    'makeaction' => 'Effectuer l\'action',
    'options' => [
      'title' => 'Gestions des options',
      'empty' => 'Ce service ne présente pas d\'option disponible',
      'your_options' => 'Vos options',
      'new_price' => 'Nouveau prix',
      'prorata' => 'Prorata',
      'per_month' => 'Tout les %months% mois',
      'today' => 'à régler aujourd\'hui',
    ],
  ],
  'transactionpage' => [
    'summary' => 'Récapitulatif de la commande',
    'summarysub' => 'Tous les éléments ici ne peuvent pas être supprimés.',
    'issuedby' => 'Émise par',
    'delivred' => 'Livraison',
    'success' => 'Effectuée',
    'refunded' => 'Remboursée',
    'pending' => 'Attente du paiement',
    'pending2' => 'En cours de livraison',
    'make' => 'Payer maintenant',
    'id' => 'Identifiant',
    'info' => 'Informations de la transaction',
    'items' => 'Nb. Objet',
  ],
  'options' => [
    'core' => [
      'title' => 'Coeurs supplémentaire',
      'unit' => 'Coeur(s)',
    ],
    'swap' => [
      'title' => 'Swap supplémentaire',
      'unit' => 'options.swap.unit',
    ],
    'min_value' => 'Valeur minimum',
    'min_valuesub' => '(0 conseillé pour une option additionnel, 3 pour une options obligatoire requis)',
    'max_value' => 'Valeur maximum',
    'backup' => [
      'title' => 'Sauvegarde supplémentaire',
      'unit' => 'Sauvegarde(s)',
    ],
    'additional' => 'Supplémentaire',
    'unit_price' => 'Prix unitaire',
    'createcustom' => 'Nouvelle option personnalisé',
    'values' => 'Valeurs autorisées',
    'fieldname' => 'Label du champ',
    'title' => 'Options additionnels',
    'disk' => [
      'title' => 'Espace disque supplémentaire',
    ],
    'ip' => [
      'title' => 'Adresse IP supplémentaire',
      'unit' => 'Adresse(s) IP',
    ],
    'servername' => [
      'title' => 'Nom du serveur',
    ],
    'memory' => [
      'title' => 'Mémoire supplémentaire',
    ],
    'database' => [
      'title' => 'Base de données supplémentaire',
      'unit' => 'Base(s) de données',
    ],
    'allocation' => [
      'title' => 'Allocation supplémentaire',
      'unit' => 'Allocation(s)',
    ],
    'bandwidth' => [
      'title' => 'Bande passante du serveur',
      'unit' => 'gb/s',
    ],
    'server' => [
      'title' => 'Serveur supplémentaire',
      'unit' => 'Serveur(s)',
    ],
  ],
  'best_sales' => 'Meilleures ventes',
  'discount' => 'Réduction',
  'your_order' => 'Votre commande',
  'recurring' => 'Récurrent',
  'deals' => 'Deals & Bon plan',
  'pay_with' => 'Payer avec',
  'payment_cancel' => 'Paiement annulé avec succès.',
  'return' => [
    'btn' => 'Plus de détails',
    'Pending' => [
      'state' => 'En attente',
      'title' => 'Commande mise en attente.',
      'content' => 'Votre commande vient d\'être mise en attente.',
    ],
    'Refunded' => [
      'state' => 'Remboursée',
      'title' => 'Commande remboursée avec succès.',
      'content' => 'Votre commande vient d\'être remboursée.',
    ],
    'title' => 'Suivi de votre commande',
    'Draft' => [
      'state' => 'Brouillon',
      'title' => 'Commande en brouillon.',
      'content' => 'Votre commande vient d\'être mise en brouillon.',
    ],
    'Completed' => [
      'state' => 'Complétée',
      'title' => 'Commande validée avec succès.',
      'content' => 'Votre commande vient d\'être validée.',
    ],
    'Cancelled' => [
      'state' => 'Annulée',
      'title' => 'Commande Annulée.',
      'content' => 'Votre commande vient d\'être annulée.',
    ],
    'Refused' => [
      'state' => 'Refusée',
      'title' => 'Commande refusée.',
      'content' => 'Rapprochez vous du support pour plus d\'informations.',
    ],
  ],
  'shopadmin' => [
    'dashboard' => [
      'transactions' => 'Transactions effectuées',
      'transactionmustbecancelled' => 'Certains produits ont étés supprimés, impossible de livrer certains transactions. Annulez les transactions %ids% pour livrer les autres transactions en attente de livraison.',
    ],
    'quotes' => [
      'info' => 'Information du devis',
      'details' => 'Details du devis',
      'sendmail' => 'Envoyer le devis par mail',
      'description' => 'Description',
      'maketransaction' => 'Créer la transaction',
      'refuse' => 'Refuser le devis',
      'accept' => 'Accepter le devis',
      'seetransaction' => 'Voir la transaction',
      'addrow' => 'Ajouter une ligne',
      'finish' => 'Terminer le devis',
      'title' => 'Devis',
      'subtitle' => 'Administrez les devis du système.',
      'note_admin' => 'Note pour l\'administrateur',
      'note' => 'Note pour le client',
    ],
    'orders' => [
      'webhook' => [
        'url' => 'URL de la webhook',
        'title' => 'Executer une webhook lors d\'une commande',
        'variables' => 'Variables disponibles',
      ],
      'title' => 'Commandes',
      'subtitle' => 'Administrez les commandes du système.',
      'confirmed' => 'Confirmé',
      'validateorder' => 'Valider la commande',
      'data' => 'Administrez les données de la commande %id%',
    ],
    'domains' => [
      'title' => 'Domaines',
      'subtitle' => 'Administrez les domaines du système.',
      'domain' => 'Domaine',
      'type' => 'Type',
    ],
    'subdomains' => [
      'title' => 'Sous domaines',
      'subtitle' => 'Administrez les sous-domaines du système.',
      'domain' => 'Domaine',
      'type' => 'Type',
    ],
    'group' => [
      'col' => 'Nombre de groupe par ligne dans la page boutique',
      'colproduct' => 'Nombre de produit dans la page du groupe',
      'name' => 'Nom du groupe',
      'add' => 'Ajouter un produit à ce groupe',
      'seeinclientarea' => 'Voir sur l\'espace client',
      'meta_description' => 'Balise meta',
      'title' => 'Groupes',
      'subtitle' => 'Administrez les groupes de la boutique.',
      'headline' => 'Gros titre',
      'parent' => 'Parent',
      'delete' => 'Supprimer ce groupe',
      'products' => 'Produits associés à ce groupe',
      'ribbon_color' => 'Couleur du ruban (Optionnel)',
      'ribbon' => 'Texte du ruban (Optionnel)',
      'upgradable' => 'Les produits de ce groupe sont améliorables',
      'downgradable' => 'Les produits de ce groupe sont rétrogradables',
      'pageheadline' => 'Description dans la page du groupe',
    ],
    'discount' => [
      'global' => 'La remise doit-elle être active sur toute la boutique?',
      'start_at' => 'Début',
      'end_at' => 'Fin',
      'months' => 'Nb. de cycle où la réduction est appliquée',
      'title' => 'Réductions',
      'subtitle' => 'Administrez les remises de la boutique.',
      'month' => 'Nombre de mois',
      'required' => 'Produit est requis',
      'requiredsub' => 'Un des produit doit être dans le panier pour que la réduction soit appliquée',
    ],
    'board' => [
      'conversionRate' => 'Taux de conversion',
      'frombeginning' => 'Depuis le début',
      'title' => 'Tableau des revenus',
      'subtitle' => 'Voici l\'état actuel des revenus.',
      'counts' => [
        'monthly' => 'Ce mois ci',
        'yearly' => 'Cette année',
        'alltime' => 'Depuis toujours',
        'since' => 'Depuis le dernier mois',
        'last' => 'L\'année dernière',
        'today' => 'Aujourd\'hui',
      ],
      'others' => 'Commandes non finalisées',
      'completed' => 'Commandes finalisées',
      'overview' => 'Aperçus',
      'clear' => [
        'development' => 'Ce bouton est disponible uniquement en environment de développement',
        'button' => 'Vider le tableau des revenues',
        'text' => 'En vidant le tableau des revenues, les services, transactions, commandes et tout ce qui est en rapport avec la facturation sera supprimé.',
      ],
    ],
    'banner' => [
      'background' => 'Arrière plan',
      'title' => 'Ajouter une bannière d\'information à votre espace client',
      'content' => 'Contenu',
    ],
    'transaction' => [
      'title' => 'Transactions',
      'subtitle' => 'Administrez les transactions effectuées sur le système.',
      'info' => 'Informations sur la transaction',
      'subtitlecreate' => 'Ajouter une transactions déjà effectuée sur le système.',
      'linktopay' => 'Lien pour payer',
      'sendbyemail' => 'Envoyer par email',
      'createtransaction' => 'Pour créer une facture pour un client rendez vous <a href=\'%link%\'>ici</a>',
    ],
    'product' => [
      'allowqty' => 'Autoriser plusieurs services par client',
      'outstock' => 'Mettre hors stock',
      'paymenttypes' => [
        'title' => 'Type de paiement',
      ],
      'taxes' => [
        'title' => 'Tableau des commissions',
        'subtitle' => 'Vous y retrouverez les prix de vos produits avec les commisions de la passerelle de paiement',
        'paypalfees' => 'Après commissions paypal',
        'stripefees' => 'Après commissions stripe',
        'info' => 'Les commissions sont des prévisionnelles, elles peuvent être différentes lors d\'un paiement.',
        'flash' => [
          'title' => 'Nouveauté ! ',
          'content' => 'Nous avons ajouté un tableau des commissions des passerelles de paiement sur vos offres. <a href=\'%link%\' class=\'text-reset\'>Cliquez ici pour y accéder</a>',
        ],
      ],
      'config' => 'Configuration du produit',
      'title' => 'Produits',
      'group' => 'Groupe',
      'showdomainoptions' => 'Affichage de l\'option domaine',
      'stockcontrol' => 'Contrôle du stocks',
      'subtitle' => 'Administrez les produits de la boutique.',
      'welcomeemail' => '--',
      'link' => 'Lien pour ajouter le produit',
      'recurringcycles' => 'Limitation du nombre de renouvellements pour une souscription (0 = Illimité)',
      'autoterminatedays' => 'Nombre de jours avant la résiliation de l\'offre',
      'autoterminateemail' => '--',
      'autoterminate' => 'Activation durée déterminée (ex essais gratuits, produits à durée limitée)',
      'recurringcyclestitle' => 'Limite (0 = Illimité)',
      'stock' => 'Stock',
      'order' => 'Ordre',
      'ondemand' => 'Offre sur demande',
      'ondemandhelp' => 'Quand votre client voudra acheter cette offre il sera rediriger vers la création d\'une demande d\'aide',
      'name' => 'Nom du produit',
      'crosssellproducts' => 'Produit Cross sell',
      'autocreate' => 'Créer automatiquement le service',
    ],
    'upgrades' => [
      'title' => 'Améliorations',
      'subtitle' => 'Administrez les améliorations services du système.',
      'make' => 'Améliorer un service',
      'clientmustpay' => 'Le client doit-il payer la facture?',
      'cannot' => 'Le produit actuelle ne peut pas être améliorer. Veuillez contacter le support',
      'prorata' => 'Prorata',
      'newproduct' => 'Nouveau produit',
      'oldproduct' => 'Ancien produit',
    ],
    'options' => [
      'title' => 'Options',
      'subtitle' => 'Administrez les options produits du système.',
    ],
    'services' => [
      'manage' => 'Gérer le service depuis votre panel d\'administration',
      'manage2' => 'Gérer le service depuis votre panel client',
      'discount' => [
        'months' => 'Nb. mois',
        'price' => 'Prix de la réduction',
        'details' => 'Ce service sera facturé %price% durant les %months% premiers cycles',
      ],
      'title' => 'Services',
      'subtitle2' => 'Les services qui doivent être livrer s\'affiche ici.',
      'subtitle' => 'Administrez les services du système.',
      'manual' => 'Ajouter manuellement le service',
      'auto' => 'Livrer le service automatiquement',
    ],
    'transactiontemplate' => [
      'title' => 'Transactions',
      'subtitle' => 'Administrez les transactions faites via %type% sur le système.',
    ],
    'payment' => [
      'subtitle' => 'Si vous souhaitez ajouter des taxes directement à chaque paiement afin de recevoir le montant exact de la transaction sans les taxes ajoutées par les modes de paiement',
    ],
    'subscriptions' => [
      'title' => 'Abonnements',
      'subtitle' => 'Administrez les abonnements du système.',
      'lastrenewal' => 'Dernier renouvellement',
      'nextrenewal' => 'Prochain renouvellement prévu',
      'month' => 'Informations prévisionnelles pour le mois de %month% calculées le %date%',
      'income' => 'Revenues des abonnements',
    ],
    'coupon' => [
      'title' => 'Code promotionnels',
      'subtitle' => 'Administrez les codes promotionnels de la boutique.',
      'amount' => 'Autoriser ce code promo à partir d\'un montant du panier',
      'maxuses' => 'Nb utilisations autorisées (0 = Sans limite)',
      'onceperclient' => 'Autoriser une seule utilisation par client',
      'need' => 'Restreindre ce code promo à certains produits déjà possédés par le client ?',
      'usage' => 'Nb utilisation',
    ],
  ],
  'order2' => 'Commande',
  'day_orders' => 'Commandes du jour',
  'groups' => 'Groupes',
  'fromgroup' => 'à partir de %price%',
  'couponmessages' => [
    'success' => 'Code promo ajouté avec succès',
    'error' => 'Code promo invalide',
    'recalculate' => 'Code promo mis à jour',
    'alreadyUsed' => 'Vous ne pouvez pas utiliser deux fois le code promotionnel !',
    'inactive' => 'Ce code promotionnel n\'est pas actif',
    'amount' => 'Le montant du panier doit être au moins de %amount%',
    'items' => 'Le panier doit être avoir au moins de %amount% Element',
    'need' => 'Vous devez avoir les services suivants pour ajouter le code promotionnel : %names%',
    'required' => 'Vous devez avoir un des articles suivantes pour activer la réductions : %names%',
  ],
  'transactionstates' => [
    'Draft' => 'Brouillon',
    'Refused' => 'Refusée',
    'Completed' => 'Complétée',
    'Cancelled' => 'Annulée',
    'Refunded' => 'Remboursée',
    'Pending' => 'En attente',
  ],
  'ordershow' => [
    'order' => [
      'title' => 'Suivi de la commande N°%id%',
    ],
    'items' => [
      'title' => 'Résumé de la commande',
      'pending' => 'Livraison en cours de préparation',
      'delivred' => 'Livraison effectuée le %date%',
      'refunded' => 'Livraison remboursée le %date%',
    ],
    'history' => [
      'title' => 'Historique de votre commande',
    ],
  ],
  'converter' => [
    'title' => 'Convertisseur',
    'mb' => 'Tapez votre chiffre en MB',
    'gb' => 'Tapez votre chiffre en GB',
  ],
  'your_quote' => 'Votre devis',
  'your_transactions' => 'Vos transactions',
  'coupon_input' => 'Code promotionnel',
  'checkout_empty' => 'Vous avez actuellement aucun produit dans votre commande.',
  'checkout_subscription' => 'Je demande un abonnement pour renouveler automatiquement le service si cela est possible par la méthode de paiement',
  'errorallowqty' => 'Vous ne pouvez pas commander une seconde fois le produit %productname% !',
  'must_auth' => 'Vous devez être authentifié pour commander.',
  'must_confirmed' => 'Vous devez être confirmé pour commander.',
  'onetime' => 'À vie',
  'domaindata' => [
    'title' => 'Choisir un domaine',
    'headingUpdate' => 'Utiliser un nom de domaine existant et mettre à jour les serveurs de noms',
    'headingSubdomain' => 'Utiliser un sous domaine de %app_name%',
  ],
  'note' => 'Note',
  'walletinsufficient' => 'Votre solde est insuffisant.',
  'quotestate' => [
    'Refused' => 'Refusée',
    'Accepted' => 'Accepté',
    'Pending' => 'En attente',
    'Draft' => 'Brouillon',
  ],
  'saved' => 'économisé',
  'your_services' => 'Mes services',
  'your_quotes' => 'Mes devis',
  'your_orders' => 'Mes commandes',
  'our_products' => 'Nos produits',
  'order_product' => 'Commander',
  'remaining_time' => 'Temps restant',
  'coupon' => 'Code promotionnel',
  'utilities' => 'Utilitaires',
  'cross_selling_title' => 'Les produits qui pourraient vous plaire',
  'instock' => '%count% en stock(s)',
  'coupons' => 'Codes promotionnels',
  'services' => 'Services',
  'for' => 'Pour',
  'reason' => 'Raison',
  'vat' => 'TVA',
  'products' => 'Produits',
  'order_comment' => [
    'label' => 'Commentaire',
    'placeholder' => 'Commentaire sur votre commande.',
  ],
  'order' => 'Commander',
  'paymenttype' => 'Type de paiement',
  'initial_price' => 'Prix initial',
  'admin' => [
    'servers' => [
      'forms' => [
        'iphelp' => 'Vous pouvez mettre l\'URL du panel',
      ],
    ],
  ],
];