<?php
/**$
    Support - fr_FR
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'department' => 'Département',
  'support.related' => 'Service/Transaction lié(e)',
  'support.admin.department.title' => 'Département',
  'support.admin.department.subtitle' => 'Administrez les différents départements du support',
  'support.show.our_reply' => 'Notre réponse',
  'support.show.your_reply' => 'Votre réponse',
  'support.priority' => 'Priorité',
  'support.priorities.High' => 'Haute',
  'support.priorities.Medium' => 'Moyenne',
  'support.priorities.Low' => 'Faible',
  'departments' => 'Départements',
  'your_tickets' => 'Vos demandes',
  'new_ticket' => 'Nouvelle demande',
  'reply' => 'Réponse',
  'open_tickets' => 'Demandes ouvertes',
  'predefinedreplies' => 'Réponses prédéfinies',
  'predefinedreply' => 'Réponse prédéfinie',
  'support.actions.close' => 'La demande vient d\'être fermée',
  'support.actions.reply' => 'La réponse vient d\'être postée',
  'support.table.last_updated' => 'Dernière mise à jours',
  'support.table.close' => 'Fermer',
  'support.table.priority' => 'Priorité',
  'support.table.department' => 'Département',
  'support.table.subject' => 'Sujet',
  'support.admin.ticket.createsubtitle' => 'Ouvrez un ticket pour un client spécifiquement.',
  'support.email.title' => 'Réponse de notre support pour la demande %subject%',
  'support.email.content' => 'Notre support vient de répondre à votre demande d\'aide. Vous pouvez la consulter en cliquant sur le bouton ci-dessus.',
  'support.email.button' => 'Mon ticket',
  'support.show.reopentext' => 'Votre demande est actuellement fermée, vous pouvez rouvrir celle-ci en cliquant sur le bouton.',
  'support.show.reopen' => 'Rouvrir la demande',
  'support.show.your_question' => 'Votre demande',
  'support.department' => 'Département',
  'support.discussion' => 'Discussion',
  'support.content' => 'Demande',
  'support.newticket' => 'Nouveau ticket',
  'support.submit' => 'Soumettre',
  'tickets' => 'Tickets',
  'support.title' => 'Support technique',
  'support.messages' => 'Messages',
  'support.replied' => 'Vous a répondu',
  'support.icon' => 'Icone',
  'support.informations' => 'Informations',
  'support.actions.reopen' => 'La demande vient d\'être rouverte.',
  'support.actions.submit' => 'La demande vient d\'être ouverte',
  'support.admin.predefined.title' => 'Réponses prédéfinies',
  'support.admin.predefined.create' => 'Vous pouvez créer des réponses prédéfinis <a href="%route%" target="_blank">ici</a>',
  'support.admin.predefined.subtitle' => 'Administrez les différents réponses prédéfinies du support',
  'support.admin.predefined.global' => 'La réponse peut être disponibles pour tout le personnel',
  'support.admin.predefined.tips' => '<strong>[LASTNAME]</strong> - Nom du client  | <strong>[FIRSTNAME]</strong> - Prénom du client | <strong>[EMAIL]</strong> - Email du client |  <strong>[RELATED]</strong> Nom de la transaction/service relié(e) (si définis)',
  'support.admin.ticket.title' => 'Support',
  'support.admin.ticket.subtitle' => 'Administez les différents tickets du support',
  'support.show.reply' => 'Répondre',
  'support.show.textarea' => 'Merci de détailler au maximum votre problème. 
Ne donnez aucune information confidentielle (mots de passe, ...), nos techniciens ont toutes les informations nécessaires pour régler votre problème',
  'support.states.Pending' => 'En attente',
  'support.states.Reply Support' => 'Réponse du support',
  'support.states.Reply Customer' => 'Réponse du client',
  'support.states.Closed' => 'Fermée',
  'support.print' => 'Imprimer',
  'support.admin' => 'Personnels à notifier par mail',
  'servicespage.options.manage' => 'Besoin d\'une IP supplémentaire ou plus d\'espace disque ?',
];