<?php
/**$
    translator - fr_FR
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'translatesitems.positive' => 'La valeur doit être positive.',
  'translatesitems.numeric' => 'La valeur doit être un numérique valide.',
  'translatesitems.between' => 'La valeur doit être comprise entre %d et %d.',
  'translatesitems.inArray' => 'La valeur n\'existe pas dans ces valeurs: %s',
  'translatesitems.notInArray' => 'La valeur ne doit pas exister dans ces valeurs: %s',
  'translatesitems.arrayHasKey' => 'Le tableau doit contenir la clé %s',
  'translatesitems.unique' => 'La valeur doit être unique en base de données',
  'translatesitems.arrayHasNotKey' => 'Le tableau ne doit pas contenir la clé %s',
  'translatesitems.filetype' => 'Le champ n\'est pas un format validé (%s)',
  'translatesitems.maxLength' => 'La valeur doit contenir moins de %d caractères.',
  'translatesitems.betweenLength' => 'La valeur doit contenir entre %d et %d caractères.',
  'translatesitems.bannedEmail' => 'L\'adresse email ou le nom de domaine est banni.',
  'translatesitems.email' => 'La valeur doit être un email valide.',
  'translatesitems.invalidip' => 'la valeur doit être une adresse IP validée.',
  'translatesitems.url' => 'La valeur doit être une url validée.',
  'translatesitems.domain' => 'La valeur doit être un domaine valide.',
  'translatesitems.equals' => 'La valeur doit être égale à sa validation.',
  'translatesitems.ispassword' => 'Le mot de passe doit être celui actuel.',
  'translatesitems.isfuture' => 'La date doit être dans le futur.',
  'translatesitems.startswith' => 'La valeur doit commencer par %s.',
  'translatesitems.endswith' => 'La valeur doit finir par %s.',
  'translatesitems.contains' => 'La valeur doit contenir %s',
  'translatesitems.notcontains' => 'La valeur ne doit pas contenir %s',
  'translatesitems.passwordsecurity' => 'Votre mot de passe n\'est pas sécurisé ! Veuillez en utiliser un autre',
  'translatesitems.sshpublic' => 'La clé SSH doit être une clé valide',
  'translatesitems.boolean' => 'La valeur doit être un booléen validé.',
  'translatesitems.int' => 'La valeur doit être un nombre validé.',
  'translatesitems.negative' => 'La valeur doit être négative.',
  'translatesitems.max' => 'Le nombre doit être inférieur à %d',
  'translatesitems.min' => 'Le nombre doit être au moins de %d',
  'translatesitems.minLength' => 'La valeur doit contenir plus de %d caractères.',
  'translatesitems.license' => 'Cette licence est invalide %s',
  'translatesitems.exists' => 'La valeur doit exister dans la base de données.',
  'translatesitems.ispast' => 'La date doit être dans le passé.',
  'translatesitems.true' => 'La valeur doit être vraie.',
  'translatesitems.false' => 'La valeur doit être fausse.',
  'translatesitems.uploaded' => 'Vous devez uploader un fichier.',
  'translatesitems.required' => 'La valeur doit être requise.',
  'translatesitems.empty' => 'La valeur ne peut pas être vide.',
  'translatesitems.slug' => 'La valeur doit être un slug valide.',
  'translatesitems.phonenumber' => 'La valeur doit être un numéro de téléphone valide.',
  'translatesitems.postcode' => 'La valeur doit être un code postal validé (%s).',
  'translatesitems.numericOrZero' => 'La valeur doit être un numérique valide ou égal à zéro.',
  'translatesitems.positiveOrZero' => 'La valeur doit être positive ou égale à zéro.',
  'translatesitems.ostemplate' => 'Vous devez choisir entre une template ou un OS.',
];