<?php
/**$
    translator - fr_FR
    CLIENTXCMS Translator system - Exported on 2023-07-26 13:50:49
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'translatesitems' => [
    'true' => 'La valeur doit être vraie.',
    'false' => 'La valeur doit être fausse.',
    'boolean' => 'La valeur doit être un booléen validé.',
    'int' => 'La valeur doit être un nombre validé.',
    'negative' => 'La valeur doit être négative.',
    'positive' => 'La valeur doit être positive.',
    'numeric' => 'La valeur doit être un numérique valide.',
    'between' => 'La valeur doit être comprise entre %d et %d.',
    'inArray' => 'La valeur n\'existe pas dans ces valeurs: %s',
    'notInArray' => 'La valeur ne doit pas exister dans ces valeurs: %s',
    'arrayHasKey' => 'Le tableau doit contenir la clé %s',
    'unique' => 'La valeur doit être unique en base de données',
    'arrayHasNotKey' => 'Le tableau ne doit pas contenir la clé %s',
    'filetype' => 'Le champ n\'est pas un format validé (%s)',
    'uploaded' => 'Vous devez uploader un fichier.',
    'required' => 'La valeur doit être requise.',
    'empty' => 'La valeur ne peut pas être vide.',
    'slug' => 'La valeur doit être un slug valide.',
    'max' => 'Le nombre doit être inférieur à %d',
    'min' => 'Le nombre doit être au moins de %d',
    'minLength' => 'La valeur doit contenir plus de %d caractères.',
    'maxLength' => 'La valeur doit contenir moins de %d caractères.',
    'betweenLength' => 'La valeur doit contenir entre %d et %d caractères.',
    'bannedEmail' => 'L\'adresse email ou le nom de domaine est banni.',
    'email' => 'La valeur doit être un email valide.',
    'invalidip' => 'la valeur doit être une adresse IP validée.',
    'url' => 'La valeur doit être une url validée.',
    'domain' => 'La valeur doit être un domaine valide.',
    'equals' => 'La valeur doit être égale à sa validation.',
    'ispassword' => 'Le mot de passe doit être celui actuel.',
    'phonenumber' => 'La valeur doit être un numéro de téléphone valide.',
    'postcode' => 'La valeur doit être un code postal validé (%s).',
    'numericOrZero' => 'La valeur doit être un numérique valide ou égal à zéro.',
    'positiveOrZero' => 'La valeur doit être positive ou égale à zéro.',
    'license' => 'Cette licence est invalide %s',
    'exists' => 'La valeur doit exister dans la base de données.',
    'ispast' => 'La date doit être dans le passé.',
    'isfuture' => 'La date doit être dans le futur.',
    'startswith' => 'La valeur doit commencer par %s.',
    'endswith' => 'La valeur doit finir par %s.',
    'contains' => 'La valeur doit contenir %s',
    'notcontains' => 'La valeur ne doit pas contenir %s',
    'passwordsecurity' => 'Votre mot de passe n\'est pas sécurisé ! Veuillez en utiliser un autre',
    'sshpublic' => 'La clé SSH doit être une clé valide',
    'ostemplate' => 'Vous devez choisir entre une template ou un OS.',
  ],
];