<?php
/**$
    Virtualizor - fr_FR
    CLIENTXCMS Translator system - Exported on 2023-11-12 18:56:11
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'virtualizor.panel.stop' => 'Eteindre',
  'virtualizor.panel.powerstop' => 'Tuer',
  'virtualizor.panel.restart' => 'Redémarrer',
  'virtualizor.panel.os_name' => 'OS',
  'virtualizor.panel.openticket' => 'Ouvrir un ticket!',
  'virtualizor.panel.uptime' => 'Disponibilité',
  'virtualizor.panel.reset' => 'Réinstallation',
  'virtualizor.admin.title' => 'Configuration Virtualizor',
  'virtualizor.productname' => 'Nom du produit',
  'virtualizor.graph' => 'Graphique',
  'virtualizor.panel.button' => 'Connexion',
  'virtualizor.panel.start' => 'Allumer',
  'virtualizor.panel.in' => 'Entrant',
  'virtualizor.panel.out' => 'Sortant',
  'virtualizor.panel.usage' => 'Utilisation',
  'virtualizor.panel.site' => 'Ouvrir le site',
  'virtualizor.panel.information' => 'Informations sur l\'hébergement',
  'virtualizor.panel.problem' => 'Vous avez un problème avec l\'hébergement ?',
  'virtualizor.converter.gb' => 'Tapez votre chiffre en GB',
  'kvm' => 'KVM',
  'openvz' => 'OpenVZ',
  'lxc' => 'LXC',
  'virtualizor.hostname' => 'Hôte',
  'virtualizor.os' => 'OS',
  'virtualizor.offline' => 'éteint',
  'virtualizor.online' => 'Allumé',
  'virtualizor.planname' => 'Nom du plan',
  'virtualizor.panel.bandwidth' => 'Bande passante',
  'virtualizor.panel.ram' => 'RAM',
  'virtualizor.panel.virt' => 'Virtualisation',
  'virtualizor.panel.cpu' => 'CPU',
  'virtualizor.panel.disk' => 'Espace disque',
  'virtualizor.panel.cores' => 'Coeurs',
  'virtualizor.admin.subtitle' => 'Administrez les configurations de vos offres.',
  'virtualizor.admin.planname' => 'Nom du plan',
  'virtualizor.config.title' => 'Configurer votre offre',
  'virtualizor.config.subtitle' => 'Administrez les caractéristiques de l\'offre.',
  'virtualizor.converter.title' => 'Convertisseur',
  'virtualizor.converter.mb' => 'Tapez votre chiffre en MB',
  'virtualizor.choosehostname' => 'Choisir un nom d\'hôte personnalisé',
];