<?php
/**$
    VirtualizorCloud - fr_FR
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'virtualizorcloud.offline' => 'éteint',
  'virtualizorcloud.online' => 'Allumé',
  'virtualizorcloud.planname' => 'Nom du plan',
  'virtualizorcloud.graph' => 'Graphique',
  'virtualizorcloud.panel.disk' => 'Espace disque',
  'virtualizorcloud.panel.cores' => 'Coeurs',
  'virtualizorcloud.panel.in' => 'Entrant',
  'virtualizorcloud.panel.out' => 'Sortante',
  'virtualizorcloud.form.resources.priority' => 'I/O Priorité (OpenVZ)',
  'virtualizorcloud.form.resources.vnc' => 'VNC activé (KVM)',
  'virtualizorcloud.form.resources.speed' => 'Vitesse du réseau en KB / s (0GB / s ou vide pour aucune limite)',
  'virtualizorcloud.form.resources.server' => 'Serveur',
  'virtualizorcloud.form.stockage.space' => 'Espace disque (GB)',
  'virtualizorcloud.form.cpu.cores' => 'Coeurs',
  'virtualizorcloud.form.cpu.units' => 'Unité',
  'virtualizorcloud.form.cpu.cpu' => 'CPU %',
  'virtualizorcloud.form.ips.internalips' => 'Nombre d\'adresse IP interne',
  'virtualizorcloud.form.ips.ips' => 'Nombre d\'IP',
  'virtualizorcloud.admin.title' => 'Configuration Virtualizor',
  'virtualizorcloud.admin.subtitle' => 'Administrez les configurations de vos offres.',
  'virtualizorcloud.admin.planname' => 'Nom du plan',
  'virtualizorcloud.config.title' => 'Configurer votre offre',
  'virtualizorcloud.hostname' => 'Hôte',
  'virtualizorcloud.os' => 'OS',
  'virtualizorcloud.panel.restart' => 'Redémarrer',
  'virtualizorcloud.panel.os_name' => 'OS',
  'virtualizorcloud.panel.bandwidth' => 'Bande passante',
  'virtualizorcloud.panel.ram' => 'RAM',
  'virtualizorcloud.panel.virt' => 'Virtualisation',
  'virtualizorcloud.panel.cpu' => 'CPU',
  'virtualizorcloud.panel.reset' => 'Réinstallation',
  'virtualizorcloud.form.resources.title' => 'Ressources',
  'virtualizorcloud.form.resources.disk' => 'Espace disque (GB)',
  'virtualizorcloud.form.resources.io' => 'Bloc IO',
  'virtualizorcloud.form.resources.bandwidth' => 'Bande passante (0GB ou vide pour aucune limite)',
  'virtualizorcloud.form.resources.inodes' => 'INode (OpenVZ)',
  'virtualizorcloud.form.resources.network_speed' => 'Vitesse du réseau en MB / s',
  'virtualizorcloud.form.resources.upload_speed' => 'Vitesse de téléchargement en MB / s',
  'virtualizorcloud.form.stockage.title' => 'Stockage',
  'virtualizorcloud.form.stockage.ram' => 'Mo de RAM (KVM, LXC)',
  'virtualizorcloud.form.stockage.guaranteed' => 'RAM Garantie (Mo)',
  'virtualizorcloud.form.stockage.burstable' => 'Ram burstable (OpenVZ)',
  'virtualizorcloud.form.configurations.group' => 'Groupe',
  'virtualizorcloud.form.configurations.vnc' => 'VNC',
  'virtualizorcloud.form.ips.ip6subnet' => 'Nombre d\'adresse IPV6',
  'virtualizorcloud.form.ips.ip6' => 'Nombre d\'adresse IPv6 subnet',
  'virtualizorcloud.productname' => 'Nom du produit',
  'virtualizorcloud.choosehostname' => 'Choisir un nom d\'hôte personnalisé',
  'virtualizorcloud.panel.button' => 'Connexion',
  'virtualizorcloud.panel.start' => 'Démarrer',
  'virtualizorcloud.panel.stop' => 'Eteindre',
  'virtualizorcloud.panel.powerstop' => 'Tuer',
  'virtualizorcloud.panel.usage' => 'Utilisation',
  'virtualizorcloud.panel.site' => 'Ouvrir le site',
  'virtualizorcloud.panel.information' => 'Informations sur l\'hébergement',
  'virtualizorcloud.panel.problem' => 'Vous avez un problème avec l\'hébergement ?',
  'virtualizorcloud.panel.openticket' => 'Ouvrir un ticket!',
  'virtualizorcloud.panel.uptime' => 'Disponibilité',
  'virtualizorcloud.form.resources.ip6' => 'IPv6',
  'virtualizorcloud.form.resources.ip6subnet' => 'Ip6 subnet',
  'virtualizorcloud.form.resources.ips' => 'IP',
  'virtualizorcloud.form.resources.oses' => 'Os disponibles (séparé par des virgules)',
  'virtualizorcloud.form.resources.internalips' => 'IP interne',
  'virtualizorcloud.form.resources.portrange' => 'Port à assigner au serveur (séparé par des virgules)',
  'virtualizorcloud.form.cpu.title' => 'CPU',
  'virtualizorcloud.form.converter.title' => 'Convertisseur',
  'virtualizorcloud.form.converter.mb' => 'Tapez votre chiffre en MB',
  'virtualizorcloud.form.converter.gb' => 'Tapez votre chiffre en GB',
  'virtualizorcloud.form.configurations.title' => 'Configuration',
  'virtualizorcloud.form.configurations.server' => 'Serveur',
  'virtualizorcloud.config.subtitle' => 'Administrez les caractéristiques de l\'offre.',
  'virtualizorcloud.converter.title' => 'Convertisseur',
  'virtualizorcloud.converter.mb' => 'Tapez votre chiffre en MB',
  'virtualizorcloud.converter.gb' => 'Tapez votre chiffre en GB',
];