<?php
/**$
    VirtualizorCloud - fr_FR
    CLIENTXCMS Translator system - Exported on 2023-07-26 10:44:27
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'kvm' => 'KVM',
  'openvz' => 'OpenVZ',
  'lxc' => 'LXC',
  'virtualizorcloud' => [
    'hostname' => 'Hôte',
    'os' => 'OS',
    'offline' => 'éteint',
    'online' => 'Allumé',
    'planname' => 'Nom du plan',
    'productname' => 'Nom du produit',
    'choosehostname' => 'Choisir un nom d\'hôte personnalisé',
    'graph' => 'Graphique',
    'panel' => [
      'button' => 'Connexion',
      'start' => 'Démarrer',
      'stop' => 'Eteindre',
      'powerstop' => 'Tuer',
      'restart' => 'Redémarrer',
      'os_name' => 'OS',
      'bandwidth' => 'Bande passante',
      'ram' => 'RAM',
      'virt' => 'Virtualisation',
      'cpu' => 'CPU',
      'disk' => 'Espace disque',
      'cores' => 'Coeurs',
      'in' => 'Entrant',
      'out' => 'Sortante',
      'usage' => 'Utilisation',
      'site' => 'Ouvrir le site',
      'information' => 'Informations sur l\'hébergement',
      'problem' => 'Vous avez un problème avec l\'hébergement ?',
      'openticket' => 'Ouvrir un ticket!',
      'uptime' => 'Disponibilité',
      'reset' => 'Réinstallation',
    ],
    'form' => [
      'resources' => [
        'title' => 'Ressources',
        'disk' => 'Espace disque (GB)',
        'io' => 'Bloc IO',
        'bandwidth' => 'Bande passante (0GB ou vide pour aucune limite)',
        'inodes' => 'INode (OpenVZ)',
        'priority' => 'I/O Priorité (OpenVZ)',
        'vnc' => 'VNC activé (KVM)',
        'speed' => 'Vitesse du réseau en KB / s (0GB / s ou vide pour aucune limite)',
        'server' => 'Serveur',
        'ip6' => 'IPv6',
        'ip6subnet' => 'Ip6 subnet',
        'ips' => 'IP',
        'oses' => 'Os disponibles (séparé par des virgules)',
        'internalips' => 'IP interne',
        'portrange' => 'Port à assigner au serveur (séparé par des virgules)',
        'network_speed' => 'Vitesse du réseau en MB / s',
        'upload_speed' => 'Vitesse de téléchargement en MB / s',
      ],
      'stockage' => [
        'title' => 'Stockage',
        'ram' => 'Mo de RAM (KVM, LXC)',
        'guaranteed' => 'RAM Garantie (Mo)',
        'burstable' => 'Ram burstable (OpenVZ)',
        'space' => 'Espace disque (GB)',
      ],
      'cpu' => [
        'cores' => 'Coeurs',
        'units' => 'Unité',
        'cpu' => 'CPU %',
        'title' => 'CPU',
      ],
      'converter' => [
        'title' => 'Convertisseur',
        'mb' => 'Tapez votre chiffre en MB',
        'gb' => 'Tapez votre chiffre en GB',
      ],
      'configurations' => [
        'title' => 'Configuration',
        'server' => 'Serveur',
        'group' => 'Groupe',
        'vnc' => 'VNC',
      ],
      'ips' => [
        'ip6subnet' => 'Nombre d\'adresse IPV6',
        'ip6' => 'Nombre d\'adresse IPv6 subnet',
        'internalips' => 'Nombre d\'adresse IP interne',
        'ips' => 'Nombre d\'IP',
      ],
    ],
    'admin' => [
      'title' => 'Configuration Virtualizor',
      'subtitle' => 'Administrez les configurations de vos offres.',
      'planname' => 'Nom du plan',
    ],
    'config' => [
      'title' => 'Configurer votre offre',
      'subtitle' => 'Administrez les caractéristiques de l\'offre.',
    ],
    'converter' => [
      'title' => 'Convertisseur',
      'mb' => 'Tapez votre chiffre en MB',
      'gb' => 'Tapez votre chiffre en GB',
    ],
  ],
];