<?php
/**$
    Wisp - fr_FR
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'Wisp.failed.linkserver' => 'Échec de la modification du mot de passe car le serveur lié n\'existe pas',
  'Wisp.failed.retrieveuser' => 'Échec de la récupération de l\'utilisateur, code d\'erreur reçu: %status_code%',
  'Wisp.failed.changepwd' => 'Échec de la modification du mot de passe, code d\'erreur reçu: %status_code%',
  'Wisp.panel.openticket' => 'Ouvrir un ticket!',
  'Wisp.panel.information' => 'Informations sur l\'hébergement',
  'Wisp.panel.start' => 'Démarrer',
  'Wisp.form.resources.title' => 'Ressources',
  'Wisp.form.resources.memory' => 'Mémoire (MB)',
  'Wisp.form.resources.disk' => 'Espace disque (MB)',
  'Wisp.form.configurations.title' => 'Configuration',
  'Wisp.form.configurations.image' => 'Image Docker',
  'Wisp.form.configurations.startup' => 'Commande de lancement',
  'Wisp.failed.alreadycreated' => 'Échec de la création du serveur car il est déjà créé',
  'Wisp.failed.changepkgexist' => 'Échec de la modification du package du serveur car il n\'existe pas',
  'Wisp.failed.suspendexist' => 'Echec de la suspension du serveur car il n\'existe pas.',
  'Wisp.failed.unsuspendexist' => 'Échec de du unsuspend du serveur car il n\'existe pas.',
  'Wisp.failed.terminateexist' => 'Échec de la suppression du serveur car il n\'existe pas.',
  'Wisp.failed.satisfying' => 'Impossible de trouver des nœuds satisfaisant la demande',
  'Wisp.failed.pwdempty' => 'Le mot de passe ne doit pas être vide',
  'Wisp.failed.suspendserver' => 'Échec de la suspension du serveur, code d\'erreur reçu: %status_code%',
  'Wisp.failed.unsuspendserver' => 'Échec de la suspension du serveur, code d\'erreur reçu: %status_code%',
  'Wisp.failed.terminateserver' => 'Échec de la suppression du serveur, code d\'erreur reçu: %status_code%',
  'Wisp.failed.buildserver' => 'Échec de la mise à jour de la version du serveur, code d\'erreur reçu: %status_code%',
  'Wisp.failed.startupserver' => 'Échec de la mise à jour du démarrage du serveur, code d\'erreur reçu: %status_code%',
  'Wisp.panel.disk' => 'Espace disque',
  'Wisp.panel.memory' => 'Mémoire',
  'Wisp.panel.button' => 'Gérer mon serveur',
  'Wisp.panel.problem' => 'Vous avez un problème avec l\'hébergement ?',
  'Wisp.adminindex.subtitle' => 'Administrez les configurations de vos offres.',
  'Wisp.adminindex.memory' => 'Mémoire',
  'Wisp.adminindex.disk' => 'Espace disque',
  'Wisp.adminindex.productname' => 'Nom du produit',
  'Wisp.migrate.title' => 'Migration Wisp',
  'Wisp.migrate.subtitle' => 'Cette page permet de migrer vos configurations Pterodactyl vers Wisp.',
  'Wisp.migrate.info' => 'Cette action changera les types de produits, migrera les configurations du module Pterodactyl vers le module Wisp.',
  'Wisp.config.title' => 'Configuration du serveur',
  'Wisp.config.subtitle' => 'Administrez les différentes caractéristiques de l\'offre.',
  'Wisp.form.features.title' => 'Fonctionnalités',
  'Wisp.form.features.databases' => 'Bases de données à attribuer au serveur',
  'Wisp.form.features.backups' => 'Limite de taille de sauvegarde (MB)',
  'Wisp.form.features.allocations' => 'Allocation (MB)',
  'Wisp.form.core.title' => 'Information',
  'Wisp.form.core.servername' => 'Nom du serveur',
  'Wisp.form.core.egg' => 'ID Egg Wisp',
  'Wisp.form.core.nest' => 'ID Nest Wisp',
  'Wisp.form.core.location' => 'ID Location Wisp',
  'Wisp.form.converter.gb' => 'Tapez votre chiffre en GB',
  'Wisp.offline' => 'éteint',
  'Wisp.online' => 'Allumé',
  'Wisp.failed.createuser' => 'Échec de la création de l\'utilisateur, code d\'erreur reçu: %status_code%',
  'Wisp.failed.geteggs' => 'Échec de l\'obtention des données sur les œufs, code d\'erreur reçu: %status_code%',
  'Wisp.failed.getserver' => 'Échec de l\'obtention des données sur le serveur, code d\'erreur reçu: %status_code%',
  'Wisp.failed.createserver' => 'Échec de la création du serveur, code d\'erreur reçu: %status_code%',
  'Wisp.panel.stop' => 'Eteindre',
  'Wisp.panel.powerstop' => 'Tuer',
  'Wisp.panel.restart' => 'Redémarrer',
  'Wisp.adminindex.title' => 'Configuration de Wisp',
  'Wisp.form.resources.swap' => 'Swap',
  'Wisp.form.resources.io' => 'Bloc IO',
  'Wisp.form.resources.portrange' => 'Port à attribuer au serveur (séparé par des virgules)',
  'Wisp.form.resources.cpu' => 'Limite du processeur (%)',
  'Wisp.form.configurations.oomkiller' => 'Désactiver OOM Killer',
  'Wisp.form.configurations.dedicatedip' => 'Adresse IP dédiée',
  'Wisp.form.converter.title' => 'Convertisseur',
  'Wisp.form.converter.mb' => 'Tapez votre chiffre en MB',
  'wisp.admin.migratebtn' => 'Espace migration',
];