<?php
/**$
    Admin - es_ES
    CLIENTXCMS Translator system - Exported on 2023-06-27 01:56:44
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'admin' => [
    'delivery' => 'Entrega de pedidos',
    'switchtheme' => 'Cambiar tema',
    'backtoadmin' => 'Volver a administración',
    'backtosite' => 'Volver al sitio web',
    'documentation' => 'Documentación',
    'support' => 'Soporte',
    'profile' => [
      'title' => 'Perfil',
      'subtitle' => 'Gestionar perfil de administrador',
    ],
    'database' => [
      'title' => 'Base de datos',
      'subtitle' => 'Gestión de base de datos',
      'available_actions' => 'Acciones disponibles',
      'main' => 'Para más información sobre el uso de phinx, sus comandos y sus muchas opciones',
      'clickhere' => 'Click aquí',
      'version' => 'Versión',
      'start_at' => 'Hora de inicio',
      'end_at' => 'Hora de fina',
      'endpoint' => 'Punto de parada',
      'list' => 'Lista de migraciones realizadas',
      'seed' => 'El comando Seed ejecuta todas las clases de seed disponibles. Para más opciones e información',
      'migrate' => 'El comando Migrar realiza todas las migraciones disponibles. Para más opciones e información',
      'rollback' => 'El comando Rollback se utiliza para deshacer migraciones anteriores realizadas por Phinx. Para más opciones e información',
    ],
    'themes' => [
      'config' => [
        'sections' => [
          'title' => 'Secciones',
          'subtitle' => 'Gestión de secciones personalizadas del tema.',
        ],
        'menus' => [
          'title' => 'Menús',
          'addsubmenu' => 'Añadir un subelemento',
          'subtitle' => 'Gestión de los menús del tema.',
        ],
        'footerlinks' => [
          'title' => 'Enlaces de pie de página',
          'subtitle' => 'Gestión de enlaces a pie de página.',
        ],
      ],
      'title' => 'Temas',
      'subtitle2' => 'Temas disponibles para CLIENTXCMS',
      'author' => 'Autor',
      'actual' => 'Tema actual',
      'viewspath' => 'Ruta de vistas',
      'templatesPath' => 'Ruta de vista principal',
      'assetsPath' => 'Ruta de activos',
      'official' => 'Oficial',
      'ComponentPath' => 'Ruta de assets',
      'PluginsPath' => 'Ruta de plugins',
      'downloaded' => 'Temas descargados',
      'apptitle' => 'Título de la aplicación',
      'appmobile' => 'Título de la aplicación para móviles',
      'htmlsupport' => 'El soporte HTML está activado para el título de la aplicación.',
      'titlehome' => 'Título Inicio',
      'subtitle' => 'Subtítulo de la página web',
      'btnaction' => 'Acción del botón',
      'btnicon' => 'Icono de botón',
      'btntext' => 'Texto del botón',
      'primary' => 'Color primario (sólo Stisla y Regal)',
      'dark' => 'Tema oscuro',
      'updateglobal' => 'En general',
      'updateonlyassets' => 'Sólo activos',
      'updateonlyviews' => 'Sólo vistas',
      'noofficial' => 'Cambiar a un tema no oficial',
      'themeemail' => 'Importe aquí su plantilla de correo',
    ],
    'dashboard' => [
      'subtitle' => 'Bienvenido a su tablero CLIENTXCMS',
      'isLatestVersion' => 'CLIENTXCMS se encuentra actualmente enla version %version%',
      'isBetaOrAlpha' => 'CLIENTXCMS está actualmente en la version %version%. <a href=\'%route%\'>Informar sobre un problema</a>',
      'statistics' => 'Estadísticas de alojamiento',
      'cronhours' => 'Atención: Sus tareas programadas no se han ejecutado durante %hours% horas. Durante este tiempo no se han producido entregas, suspensiones ni expiraciones.',
      'statistiquessub' => 'Encuentre las estadísticas de su anfitrión, ya sean los últimos registros, las facturas generadas y los servicios activos, todo está ahí!',
    ],
    'firewall' => [
      'title' => 'Firewall',
      'subtitle' => 'Verificación y autorización de la identidad',
      'confirm' => 'Confirme su contraseña para continuar',
      'content' => 'Estas entrando en un area administrativa de ClientXCMS y debe confirmar su contraseña para continuar',
      'confirmation' => '¿realmente quieres desconectarte del firewall?',
      'btn' => 'Confirmar',
      'logout_btn' => 'Salir del firewall',
      'actions' => [
        'badpwd' => 'Contraseña incorrecta',
        'success' => 'Autorización concedida',
        'logout' => 'Desconectado con éxito.',
      ],
    ],
    'emailtemplate' => [
      'title' => 'Plantilla de correo electrónico',
      'subtitle' => 'Gestionar plantilla de correo electrónico',
    ],
    'license' => [
      'title' => 'Licencia',
      'subtitle' => 'Información relacionada con su licencia.',
      'registar' => 'Registrado por',
      'key' => 'Licencia ',
      'type' => 'Tipo de licencia',
      'max' => 'Nº de clientes autorizados',
      'customers' => 'Nº de clientes en el sistema',
      'domain' => 'Dominio autorizado (s)',
      'expire' => 'Expiración',
      'types' => [
        'dev' => 'Desarrollo',
        'prod' => 'Producción',
        'demo' => 'Demostración',
        'gift' => 'Regalo',
      ],
    ],
    'modules' => [
      'title' => 'Módulos',
      'subtitle' => 'Módulo disponible.',
      'folder' => 'Archivo',
      'actived' => 'Activado',
      'support' => 'Soporte en línea',
      'updatable' => 'Actualizable a %tag%',
      'official' => 'Módulo oficial',
      'updated' => 'Última actualización',
      'changelogbtn' => 'Ver registro de cambios',
      'changelog' => 'Registro de cambios',
      'about' => 'Acerca de',
      'requiredmodules' => 'Módulo requerido',
      'empty' => 'No se pueden recuperar los módulos del sitio web principal no está disponible actualmente. Por favor, póngase en contacto con el soporte',
      'enable' => 'Activar',
      'refresh' => 'Forzar el refresco',
      'warning' => 'Al desactivar este módulo, es posible que alguna página deje de funcionar debido a ciertas características que ya no serán añadidas por este módulo en el sistema. Nuestro soporte no podrá ayudarle en caso de un problema de este tipo.',
      'disable' => 'Desactivar',
      'download' => 'Descargar',
      'reinstall' => 'Reinstalar',
      'update' => 'Actualización',
      'downloadsucess' => 'Módulo descargado/actualizado correctamente.',
      'config' => [
        'title' => 'Configuración del módulo',
        'subtitle' => 'Configure sus claves API para %name%.',
      ],
    ],
    'update' => [
      'translations' => [
        'content' => 'La última exportación de sus archivos de idioma se remonta a %date%</code>. Puede descargar los nuevos archivos ahora.',
      ],
      'title' => 'Actualización',
      'subtitle' => 'Gestionar las actualizaciones del sistema.',
      'warning' => 'Antes de actualizar CLIENTXCMS, debe hacer una copia de seguridad de su sitio!',
      'download' => 'Descargar',
      'unknown' => 'No se puede actualizar el CMS porque el sitio web principal no funciona o no está disponible. Póngase en contacto con el servicio de asistencia técnica.',
      'info' => 'La versión <code>%version1%</code> de CLIENTXCMS está disponible y estas en la versión <code>%version2%</code>. La última versión de CLIENTXCMS está lista para descargar.',
    ],
    'phpinfo' => 'PHPINFO',
    'logs' => [
      'title' => 'Historia',
      'clear' => 'Borrar historial',
      'subtitle' => 'Gestionar el historial de CLIENXCMS',
      'masseaction' => 'Acción masiva',
      'checkall' => 'Seleccionar todo',
      'delete' => 'Borrar',
      'signal' => 'Informe',
      'deleteall' => 'Borrar lo seleccionado',
    ],
    'report' => [
      'cron' => [
        'successoftask' => 'Éxito de la tarea',
        'last_schedule' => 'Última programación',
        'start_at' => 'Inicio',
        'end_at' => 'Fin',
        'failed' => 'Fallido',
        'output' => 'Salida',
        'exception' => 'Excepción',
        'invokenow' => 'Ejecutar ahora',
        'delete' => 'Eliminar las tareas más antiguas',
        'successfully' => 'Exitosamente',
        'task' => 'Tarea #',
        'time' => 'Tiempo entre dos ejecuciones',
        'minuts' => 'cada %minuts% minutos',
        'minut' => 'cada minuto',
        'hours' => 'cada %hours% horas',
        'hour' => 'cada hora',
      ],
      'general' => [
        'serverstate' => 'Estado del servidor',
        'good' => 'Bueno',
        'suspended' => 'Servicios suspendidos',
        'expired' => 'Servicios caducados',
      ],
    ],
    'settings' => [
      'cache' => 'Borrar caché de la aplicación',
      'title' => 'Ajustes',
      'subtitle' => 'Configure aquí sus ajustes de CLIENTXCMS.',
      'saving' => 'Guardando...',
      'error' => 'Error',
      'saved' => 'Guardado',
      'seo' => [
        'description' => 'Descripción de la página',
        'keywords' => 'Palabras clave',
        'favicon' => 'Favicon',
        'head' => 'Código HTML a incluir en la cabecera de todas las páginas',
        'body' => 'Código HTML a incluir en el cuerpo de todas las páginas',
        'analytics' => 'ID Google analytics',
        'tawk' => 'ID Tawk.to',
        'how_did_you_find_us_options' => '¿Cómo nos has encontrado? Opciones',
        'how_did_you_find_us_options_sub' => 'Dejar en blanco para desactivar.',
      ],
      'security' => [
        'title' => 'Autenticación y limitación',
        'bannedemails' => 'Correos electrónicos o dominios prohibidos al registrarse',
        'authminuts' => 'Minutos que limitan la conexión',
        'authlimit' => 'Nº de intentos',
        'authreset' => 'Es hora de restablecer su contraseña',
        'tosLinks' => 'Enlace a los terminos del servicio',
        'confirmation' => 'Solicita la confirmación de la cuenta del usuario',
        'resetpwd' => 'Permitir el restablecimiento de la contraseña del usuario',
        'autoredirecttologin' => 'Redirección automática del usuario al inicio de sesión al intentar acceder al área de clientes',
        '2fa' => [
          'alert' => 'Debe habilitar el 2FA para utilizar el panel de administración',
          'required_for_admin' => 'Se requieren dos factores de activación para acceder a una cuenta de administrador',
          'minutes_between' => 'Minutos entre comprobaciones de 2FA (sólo para administradores)',
          'minutes_betweendesc' => '(0 para mantener hasta el final de la sesión de PHP)',
        ],
        'register' => 'Permitir el registro de usuarios',
        'captcha' => [
          'title' => 'Proteja sus formularios y evite los bots asegurándolos con HCaptcha o Recapcha',
          'validatewith' => 'Validación con',
          'sitekey' => 'Clave del sitio',
          'secretkey' => 'Clave secreta',
          'recapcha' => [
            'title' => 'Configurar la protección de Google reCaptcha',
            'content' => 'Puede obtener las claves reCaptcha en el<a href="https://www.google.com/recaptcha/" target="_ blank" rel="noopener noreferrer"> Sitio web de Google reCaptcha </a>. Debe utilizar reCaptcha <strong> v2 invisible </strong> claves.',
          ],
          'hcaptcha' => [
            'title' => 'Configurar la protección HCaptcha',
            'content' => 'Puede obtener las claves reCaptcha en el<a href="https://www.hcaptcha.com/" target = "_ blank" rel= "noopener noreferrer"> Sitio web de HCaptcha </a>.',
          ],
        ],
      ],
      'global' => [
        'logopdf' => 'Logo en el PDF',
        'logopdfhelp' => 'Tamaño recomendado: 90x35',
        'makerenewtransaction_days' => 'Nº de días antes de la expiración para generar la factura de renovación',
        'locale2' => 'Desactivar el cambio de idioma',
        'expire_days' => 'Nº de días para dar de baja el servicio tras la suspensión por caducidad',
        'expire_days2' => 'Una vez transcurrido este periodo, el servicio caducará y se eliminará del servidor.',
        'stock_warning' => 'Número de existencias restantes para mostrar el stock restante.',
        'vat' => 'Desactivar el IVA',
        'appname' => 'Nombre del alojamiento',
        'license' => 'Clave de licencia',
        'timezone' => 'Zona horaria',
        'currency' => 'Moneda',
        'lang' => 'Idioma de la página',
        'driver' => 'Extensión del procesamiento de imágenes',
        'enable_addproduct_hidden' => 'Activar la adición de productos ocultos a la cesta',
        'failedcreations_max' => 'Nº de intentos de crear servicios autorizados',
        'locale' => 'Localidad',
        'prefix' => 'Prefijo del área de clientes',
        'logo' => 'Logotipo de alojamiento',
        'scheme' => 'HTTP/HTTPS',
        'address' => 'Dirección de alojamiento',
        'disabled_wallet' => 'Desactivar el pago con cartera',
        'disabled_autocreate' => 'Desactivar el servicio de creación automática',
        'disabled_basket' => 'Desactivar la cesta',
        'upgrade' => [
          'title' => 'Política de tasas de instalación de mejoras de servicios',
          'default' => 'Facturación de los costes de instalación normalmente',
          'diff' => 'Facturación de los costes de instalación restando los costes de instalación de la oferta antigua',
          'disable' => 'Sin gastos de instalación al actualizar el servicio',
        ],
      ],
      'mail' => [
        'mailfrom' => 'Dirección de correo electrónico utilizada para enviar correos electrónicos',
        'sendwithsmtp' => 'Enviar a través de SMTP',
        'password' => 'Contraseña SMTP',
        'username' => 'Nombre de usuario SMTP',
        'hostname' => 'Nombre del host SMTP',
        'port' => 'Puerto SMTP',
        'encryption' => 'Cifrado',
        'title' => 'Prueba de mensajería CLIENTXCMS',
        'content' => 'Esta es una prueba del sistema de correo electrónico ClientXCMS. Está listo para enviar correos electrónicos',
      ],
    ],
    'confirmation' => '¿Realmente quieres realizar esta acción?',
    'account' => 'Cuenta de usuario',
    'reports' => [
      'loginhistory' => [
        'emailsent' => 'Porcentaje de correos electrónicos enviados',
        'login' => 'Número de conexiones por día',
      ],
      'title' => 'Informes',
      'overview' => 'Resumen',
      'subtitle2' => 'Informes del sistema de gestión',
      'subtitle' => 'Los siguientes informes ofrecen un análisis de los datos contenidos en el sistema.',
    ],
    'email' => [
      'title' => 'Enviar email',
      'subtitle' => 'Gestionar los emails enviados en el sistema.',
      'sendtoeveryone' => 'Enviar a todo el mundo',
    ],
    'roles' => [
      'title' => 'Roles',
      'subtitle' => 'Funciones y permisos de administrador del sistema.',
      'info' => 'Cuando el grupo es propietario tiene todos los permisos.',
    ],
    'staffs' => [
      'title' => 'Staff',
      'subtitle' => 'Gestionar el personal con acceso de administración.',
      'owner' => 'Propietario',
      'ownertext' => 'Al activar esta opción, el administrador podría eliminar su propia cuenta sin su permiso. Dar acceso a las personas adecuadas',
    ],
    'bannedips' => [
      'title' => 'IP Banned',
      'subtitle' => 'Gestionar las direcciones IP prohibidas.',
      'punisher' => 'Castigador',
      'definitive' => 'Sanción final',
      'reason' => 'Motivo de la acción',
      'expire' => 'Expiración de la sanción',
      'subtitleForCreate' => 'Puede aplicar la misma sanción para diferentes direcciones IP separándolas con comas.',
    ],
    'servers' => [
      'title' => 'Servidores',
      'nameservers' => 'Servidores de nombres',
      'enablemodule' => 'Debe activar al menos un módulo que proporcione un servicio.',
      'details' => 'Detalles del servidor',
      'subtitle' => 'Gestionar los servidores del sistema',
      'name' => 'Nombre del servidor',
      'authentification' => 'Autenticación',
      'testconnect' => 'Probar la conexión',
      'result' => 'Resultado de la prueba',
      'statuscode' => 'Código de estado',
      'data' => 'Datos devueltos',
      'add' => [
        'title' => 'Añadir un nuevo servidor',
        'subtitle' => 'Se utiliza para vincular un servidor a CLIENTXCMS',
      ],
      'forms' => [
        'secure' => 'Seguridad',
        'primarynameserver' => 'Servidor de nombres principal',
        'username' => 'Nombre de usuario',
        'password' => 'Contraseña',
        'monthlycost' => 'Coste mensual',
        'customport' => 'Puerto personalizado',
        'noc' => 'Ubicación',
        'secondarynameserver' => 'Segundo servidor de nombres',
        'thirdnameserver' => 'Tercer servidor de nombres',
        'fourthnameserver' => 'Cuarto servidor de nombres',
        'fifthnameserver' => 'Quinto servidor de nombres',
        'type' => 'Tipo de servidor',
        'maxaccounts' => 'Nº máximo de cuentas',
      ],
    ],
  ],
  'configuration' => [
    'update' => 'Configuración guardada con éxito.',
    'delete' => 'Configuración eliminada con éxito.',
    'create' => 'Configuración creada con éxito.',
  ],
];