<?php
/**$
    Proxmox - es_ES
    CLIENTXCMS Translator system - Exported on 2023-10-04 11:44:06
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'proxmox.console' => 'Consola',
  'proxmox.disk' => 'Espacio en disco',
  'proxmox.cores' => 'Cores',
  'proxmox.cpuunits' => 'CPU',
  'proxmox.net' => 'Net',
  'proxmox.panel.problem' => 'Tienes un problema con el alojamiento ?',
  'proxmox.panel.openticket' => 'Abrir ticket!',
  'proxmox.network.title' => 'Red',
  'proxmox.reboot' => 'Reiniciar',
  'proxmox.snapshots.title' => 'Instantáneas',
  'proxmox.snapshots.remaining' => 'Tienes %remaining% instantáneas permitidas.',
  'proxmox.backups.success2' => 'Backup eliminado.',
  'proxmox.backups.unauthorized' => 'No puedes hacer una copia de seguridad',
  'proxmox.form.converter.title' => 'Convertidor',
  'proxmox.form.converter.mb' => 'Introduzca el número en MB',
  'proxmox.form.converter.gb' => 'Introduzca su número en GB',
  'proxmox.admin.title' => 'Configuración de Promox',
  'proxmox.admin.subtitle' => 'Administrar configuraciones ofrecidas.',
  'proxmox.admin.productname' => 'Nombre del producto',
  'proxmox.memory' => 'Memoria',
  'proxmox.bwlimit' => 'Ancho de banda',
  'proxmox.graph' => 'Gráficos',
  'proxmox.unlimited' => 'Ilimitado',
  'proxmox.network.type' => 'Tipo',
  'proxmox.network.link_down' => 'Desconectado',
  'proxmox.network.virtio' => 'Virtio',
  'proxmox.network.rate' => 'Velocidad de red',
  'proxmox.backups.success3' => 'Backup restaurado.',
  'proxmox.reinstall.title' => 'Reinstalación',
  'proxmox.reinstall.remaining' => 'Tienes %remaining% instalaciones permitidas.',
  'proxmox.reinstall.limit' => 'Ha alcanzado el número máximo de desinstalaciones permitidas.',
  'proxmox.reinstall.success' => 'Instalación en curso.',
  'proxmox.form.restrictions.reinstall' => 'Número de reinstalaciones permitidas',
  'proxmox.form.restrictions.nolimit' => '0 para ilimitado',
  'proxmox.form.restrictions.unauthorized' => '0 para desactivar',
  'proxmox.admin.templates.subtitle' => 'Administrar las diferentes plantillas de Proxmox',
  'proxmox.admin.oses.title' => 'Huesos',
  'proxmox.admin.oses.subtitle' => 'Administrez les différents OS Proxmox',
  'proxmox.os' => 'Os',
  'proxmox.template' => 'Modelo de SO',
  'proxmox.offline' => 'offline',
  'proxmox.online' => 'Online',
  'proxmox.format' => 'Formato de disco',
  'proxmox.size' => 'Tamaño del disco',
  'proxmox.hostname' => 'Host',
  'proxmox.tasks' => 'Tareas',
  'proxmox.uptime' => 'Disponibilidad',
  'proxmox.cpu' => 'CPU',
  'proxmox.button' => 'Conexión',
  'proxmox.informations' => 'Información',
  'proxmox.start' => 'Iniciar',
  'proxmox.stop' => 'Parar',
  'proxmox.shutdown' => 'Forzar apagado',
  'proxmox.choosehostname' => 'Elige un nombre de host personalizado',
  'proxmox.network.gw' => 'Puerta de enlace',
  'proxmox.network.gw6' => 'Puerta de enlace v6',
  'proxmox.network.ip' => 'Dirección IP',
  'proxmox.network.firewall' => 'Firewall',
  'proxmox.network.mtu' => 'Unidad máxima de transferencia de la interfaz',
  'proxmox.network.ip6' => 'Dirección IP v6',
  'proxmox.network.name' => 'Nombre',
  'proxmox.network.bridge' => 'Puente',
  'proxmox.network.hwaddr' => 'Dirección Mac',
  'proxmox.snapshots.limit' => 'Ha alcanzado el número máximo de instantáneas permitidas.',
  'proxmox.snapshots.success' => 'Instantánea guardada.',
  'proxmox.snapshots.success2' => 'Instantánea borrada.',
  'proxmox.snapshots.success3' => 'Instantánea restaurada.',
  'proxmox.snapshots.unauthorized' => 'No puedes hacer una instantánea',
  'proxmox.backups.title' => 'Backups',
  'proxmox.backups.remaining' => 'Tienes %remaining% backups permitidos.',
  'proxmox.backups.limit' => 'Ha alcanzado el número máximo de copias de seguridad permitidas.',
  'proxmox.backups.success' => 'Backup Creado.',
  'proxmox.config.title' => 'Proxmox',
  'proxmox.config.subtitle' => 'Configure tu oferta proxmox aquí',
  'proxmox.form.title' => 'Configuración de Proxmox',
  'proxmox.form.block' => 'Bloque IP (por ejemplo, 123.223.134.XX / 24)',
  'proxmox.form.importertitle' => 'Importador de bloques IP',
  'proxmox.form.range' => 'Rango IP (Ej: 1-16)',
  'proxmox.form.btn' => 'Importación rápida',
  'proxmox.form.global.title' => 'Información general',
  'proxmox.form.restrictions.title' => 'Restricciones',
  'proxmox.form.restrictions.snapshot' => 'Número de instantáneas permitido',
  'proxmox.form.restrictions.backup' => 'Número de backups permitido',
  'proxmox.settings.password' => 'Establezca una contraseña raíz aleatoria y envíela por correo electrónico a la entrega',
  'proxmox.settings.lxcparams' => 'Añadir parámetros al agregar la red',
  'proxmox.settings.lxcparamshelp' => 'Ejemplo: bridge=vmbr0,',
  'proxmox.settings.sshcommand' => 'Comando ejecutado al instalar un VPS',
  'proxmox.settings.sshexecutehelp' => 'Variables disponibles. Más información en<a href="%link%">documentación</a>',
  'proxmox.settings.sshexecutehelp2' => 'Si este comando está vacío, el comando configurado<a href="/admin/settings#proxmox">aqi</a>se ejecutará.',
  'proxmox.admin.ipaddress.title' => 'Configuración IP',
  'proxmox.admin.ipaddress.subtitle' => 'Gestionar las diferentes direcciones IP.',
  'proxmox.admin.ipaddress.used' => 'Usada ?',
  'proxmox.admin.templates.title' => 'Modelo',
  'proxmox.admin.type' => 'Tipo',
  'proxmox.settings.defaultdisk' => 'Disco por defecto a modificar',
  'proxmox.settings.vpsprefix' => 'Prefijo de nombre de host por defecto',
  'proxmox.settings.backupstorage' => 'Servidor de almacenamiento de copias de seguridad',
];