<?php
/**$
    Pterobox - es_ES
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'pterobox.cannot.core' => 'No puedes exceder el limite de %limit% de VCores de CPU.',
  'pterobox.cannot.empty' => 'No puedes poner un valor vacío o 0',
  'pterobox.panel.disk' => 'Espacio del disco',
  'pterobox.config.subtitle' => 'Administrar las diferentes características de la oferta.',
  'pterobox.form.resources.title' => 'Recursos',
  'pterobox.form.resources.servers' => 'Número de servidores que se pueden crear',
  'pterobox.form.resources.cores' => 'Uso de CPU (%)',
  'pterobox.form.features.allocations' => 'Puertos',
  'pterobox.form.features.backups' => 'Backups',
  'pterobox.form.features.servers' => 'Servidores',
  'pterobox.form.features.cores' => 'Núcleos de CPU',
  'pterobox.form.core.title' => 'Información',
  'pterobox.form.core.egg' => 'ID Egg Ptérodactyl',
  'pterobox.cannot.database' => 'No puedes exceder el límite de %limit% bases de datos.',
  'pterobox.cannot.backup' => 'No puedes exceder el límite de %limit% backups.',
  'pterobox.cannot.allocation' => 'No puedes exceder el límite de %limit% puertos.',
  'pterobox.cannot.server' => 'No puedes exceder el límite de %limit% servidores.',
  'pterobox.adminindex.disk' => 'Espacio del disco',
  'pterobox.adminindex.productname' => 'Nombre del producto',
  'pterobox.config.title' => 'Configuración del servidor',
  'pterobox.form.features.databases' => 'Base de datos',
  'pterobox.createserver' => 'Crear un servidor',
  'pterobox.updateserver' => 'Modificar el servidor',
  'pterobox.button' => 'Editar',
  'pterobox.servername' => 'Nombre del servidor',
  'pterobox.used' => 'utilizado',
  'pterobox.used2' => 'utilizado',
  'pterobox.cannot.memory' => 'No puedes exceder el limite de %limit% GB de memoria.',
  'pterobox.cannot.disk' => 'No puedes exceder el límite de %limit% GB de espacio en disco.',
  'pterobox.panel.memory' => 'Memoria',
  'pterobox.panel.button' => 'Crear un servidor',
  'pterobox.panel.problem' => '¿Tienes algún problema con el alojamiento?',
  'pterobox.panel.openticket' => 'Abrir ticket!',
  'pterobox.panel.information' => 'Información sobre el servicio',
  'pterobox.panel.backupswisp' => 'Tamaño límite de la copia de seguridad',
  'pterobox.panel.backupswisphelp' => 'El número total de gigabytes que el servidor puede utilizar para las copias de seguridad.',
  'pterobox.adminindex.title' => 'Configuración de Pterodactyl',
  'pterobox.adminindex.subtitle' => 'Gestiona las configuraciones de tus ofertas.',
  'pterobox.adminindex.memory' => 'Memoria',
  'pterobox.form.resources.memory' => 'Memoria (GB)',
  'pterobox.form.resources.disk' => 'Almacenamiento (GB)',
  'pterobox.form.resources.help' => 'Disponible para toda la caja',
  'pterobox.form.resources.portrange' => 'Puerto a asignar al servidor (Ejemplo: 3000-4000)',
  'pterobox.form.resources.cpu' => 'Límite del procesador (%)',
  'pterobox.form.resources.swap' => 'Swap',
  'pterobox.form.resources.swaphelp' => '0 desactivará el intercambio para el servidor. -1 permitirá sin restricciones',
  'pterobox.form.resources.io' => 'Block IO',
  'pterobox.form.features.title' => 'Características',
  'pterobox.form.core.nest' => 'ID Nido (nest) Pterodáctilo',
  'pterobox.form.core.location' => 'ID Ubicación Pterodactyl',
];