<?php
/**$
    Pterodactyl - es_ES
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'pterodactyl.failed.pwdempty' => 'La contraseña no debe estar vacía.',
  'pterodactyl.failed.linkserver' => 'No se ha podido cambiar la contraseña porque el servidor vinculado no existe.',
  'pterodactyl.failed.retrieveuser' => 'Error en la recuperación del usuario, código de error recibido: %status_code%',
  'pterodactyl.failed.changepwd' => 'Cambio de contraseña fallido, código de error recibido: %status_code%',
  'pterodactyl.panel.problem' => '¿Tienes problemas con el servicio?',
  'pterodactyl.panel.openticket' => 'Abrir ticket',
  'pterodactyl.panel.information' => 'Información sobre el alojamiento',
  'pterodactyl.panel.start' => 'Iniciar',
  'pterodactyl.form.resources.disk' => 'Espacio en disco (MB)',
  'pterodactyl.form.resources.swap' => 'Swap',
  'pterodactyl.form.resources.swaphelp' => '0 desactivará el intercambio para el servidor. -1 permitirá sin restricciones',
  'pterodactyl.form.resources.io' => 'Block IO',
  'pterodactyl.form.configurations.image' => 'Imagen Docker',
  'pterodactyl.form.configurations.startup' => 'Comando de inicio ',
  'pterodactyl.form.configurations.oomkiller' => 'Desactivado OOM Killer',
  'pterodactyl.form.configurations.dedicatedip' => 'Dirección IP dedicada',
  'pterodactyl.failed.unsuspendexist' => 'Fallo en la desconexión del servidor porque no existe.',
  'pterodactyl.failed.terminateexist' => 'No se ha podido eliminar el servidor porque no existe .',
  'pterodactyl.failed.satisfying' => 'Imposibilidad de encontrar nodos que satisfagan la demanda.',
  'pterodactyl.panel.disk' => 'Espacio en disco ',
  'pterodactyl.panel.memory' => 'Memoria',
  'pterodactyl.panel.button' => 'Gestionar mi servidor',
  'pterodactyl.config.subtitle' => 'Gestionar las características de la oferta .',
  'pterodactyl.form.resources.title' => 'Recursos',
  'pterodactyl.form.resources.memory' => 'Memoria (MB)',
  'pterodactyl.form.core.nest' => 'ID Nido (nest) Pterodáctilo',
  'pterodactyl.form.core.location' => 'ID Ubicación Pterodactyl',
  'pterodactyl.form.configurations.title' => 'Configuración',
  'pterodactyl.offline' => 'Fuera de linea',
  'pterodactyl.online' => 'En linea',
  'pterodactyl.failed.alreadycreated' => 'No se ha podido crear el servidor porque ya está creado.',
  'pterodactyl.failed.changepkgexist' => 'No se ha podido modificar el paquete del servidor porque no existe.',
  'pterodactyl.failed.suspendexist' => 'Fallo al suspender el servidor porque no existe.',
  'pterodactyl.failed.createuser' => 'Creación de usuario fallida, código de error recibido: %status_code%',
  'pterodactyl.failed.geteggs' => 'No se han podido obtener los datos del huevo, se ha recibido un código de error: %status_code%',
  'pterodactyl.failed.getserver' => 'Fallo en la obtención de datos del servidor, código de error recibido: %status_code%',
  'pterodactyl.failed.createserver' => 'Fallo en la creación del servidor, código de error recibido: %status_code%',
  'pterodactyl.failed.suspendserver' => 'Fallo en la suspensión del servidor, código de error recibido: %status_code%',
  'pterodactyl.failed.unsuspendserver' => 'Fallo en la suspensión del servidor, código de error recibido: %status_code%',
  'pterodactyl.failed.terminateserver' => 'Fallo en la suspensión del servidor, código de error recibido: %status_code%',
  'pterodactyl.failed.buildserver' => 'Error en la actualización de la versión del servidor, código de error recibid: %status_code%',
  'pterodactyl.failed.startupserver' => 'Error en la actualización de inicio del servidor, código de error recibido: %status_code%',
  'pterodactyl.panel.stop' => 'Detener',
  'pterodactyl.panel.powerstop' => 'Forzar apagado',
  'pterodactyl.panel.restart' => 'Reiniciar',
  'pterodactyl.adminindex.title' => 'Configuración de Pterodactyl',
  'pterodactyl.adminindex.subtitle' => 'Gestionar las configuraciones de la oferta.',
  'pterodactyl.adminindex.memory' => 'Memoria',
  'pterodactyl.adminindex.disk' => 'Espacio en disco',
  'pterodactyl.adminindex.productname' => 'Nombre del producto',
  'pterodactyl.config.title' => 'Configuración del servidor',
  'pterodactyl.form.resources.portrange' => 'Puerto a asignar al servidor (Ejemplo: 3000-4000)',
  'pterodactyl.form.resources.cpu' => 'Límite del procesador (%)',
  'pterodactyl.form.features.title' => 'Características',
  'pterodactyl.form.features.databases' => 'Bases de datos que se asignarán al servidor',
  'pterodactyl.form.features.allocations' => 'Asignaciones adicionales para el servidor',
  'pterodactyl.form.features.backups' => 'Backups para asignar al servidor',
  'pterodactyl.form.core.title' => 'Información',
  'pterodactyl.form.core.servername' => 'Nombre del servidor',
  'pterodactyl.form.core.egg' => 'ID Egg Ptérodactyl',
];