<?php
/**$
    Shop - es_ES
    CLIENTXCMS Translator system - Exported on 2023-08-01 14:13:28
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'active_services' => 'Servicios activos',
  'see_product' => 'Ver productos',
  'active' => 'Activación',
  'percentage' => 'Porcentaje',
  'group' => 'Grupos',
  'discounts' => 'Descuentos',
  'servicestate' => [
    'Pending' => 'Entrega en curso',
    'Online' => 'En línea',
    'Terminated' => 'Terminado',
    'Suspended' => 'Suspendido',
    'Expired' => 'Caducado',
    'Refunded' => 'Reembolsado',
  ],
  'pdf' => [
    'payable' => 'Neto a pagar impuestos incluidos ',
    'title' => 'Nº de factura %createdat%-%id%',
    'totalht' => 'Total antes de impuestos: ',
    'deadline' => 'Fecha Vencimiento',
    'qty' => 'Cantidad',
    'label' => 'Etiqueta',
    'totalvat' => 'Total IVA: ',
    'discount' => 'Descuento: ',
    'totalprice' => 'Precio IVA incl: ',
  ],
  'serviceactions' => [
    'transactions' => [
      'cancel' => 'Transacción cancelada.',
      'success' => 'Transacción completada.',
    ],
    'rename' => [
      'length' => 'El nombre del servicio debe tener entre 1 y 100 caracteres.',
      'success' => 'Nombre del servicio modificado con éxito.',
    ],
    'password' => [
      'length' => 'La contraseña debe tener 8 caracteres como mínimo.',
      'success' => 'Contraseña modificada con éxito.',
      'error' => 'No puedo cambiar la contraseña.',
    ],
    'recurring' => [
      'success' => 'Ciclo de facturación modificado con éxito.',
      'error' => 'No se puede cambiar el ciclo de facturación.',
      'discount' => 'Debe esperar a que finalice su(s) ciclo(s) de %months% para poder cambiar el ciclo de facturación.',
    ],
    'renew' => [
      'success' => 'Renovación completada',
      'cancel' => 'Renovación cancelada.',
      'manage' => 'Paga la renovación de tu servicio.',
      'renewinfo' => 'Este servicio expira en %days% días. Puede renovarlo haciendo clic en el botón de abajo para evitar la interrupción del servicio.',
      'warning' => 'Atención',
      'information' => 'Información',
    ],
  ],
  'servicespage' => [
    'crontab' => 'Si su servicio tarda más de 3 minutos en entregarse, verifique que <a href=\'%link%\'>sus tareas CRON</a>  se estén ejecutando correctamente.',
    'renewbywallet' => 'Renovación automática mediante la cartera',
    'renewtitle' => 'Gestor de renovación',
    'expire_at' => 'Expira el',
    'recurringcycle' => 'Ciclo de facturación',
    'servicename' => 'Nombre del servicio',
    'title' => 'Gestión de servicios',
    'subscription' => [
      'title' => 'Anular la suscripción de %method%',
      'title2' => 'Reactivar suscripción de %method%',
      'subtitle' => 'Ya no le cobraremos automáticamente por renovar su servicio.',
      'last4' => 'Los cuatro últimos dígitos de la tarjeta',
      'cancel' => 'Se ha cancelado la suscripción a su servicio',
      'lastpayment' => 'Tu última retirada fue el %date%',
      'uncancel' => 'Tu suscripción al servicio acaba de ser reactivada. La próxima facturación será el %date%',
      'addsubscription' => 'Puede solicitar una suscripción automática a este servicio. Se le cargarán %price% el %date%',
      'makesubscription' => 'Suscribirse',
      'manage' => 'Gestionar la suscripción',
    ],
    'password' => 'Cambiar contraseña',
    'subscriptioninfo' => 'Su servicio se renovará automáticamente él %date% mediante %method%.',
    'removetransactionitem' => 'Eliminar la transacción a pagar',
    'renewwarning' => 'Hay que pagar una factura para continuar con la suscripción del servicio.  <a href=\'%link%\'>Haga clic aquí para pagarlo</a>. Tras la expiración del servicio será imposible utilizarlo.',
    'autoterminate' => 'Fin programado en',
    'cannotRenew' => 'Se ha alcanzado el ciclo límite de servicio',
    'suspend_expire' => 'Su servicio expirará %date%. Después de este período, el servicio será eliminado del servidor.',
    'created_at' => 'Creado el',
    'recurring' => 'Recurrente',
    'cycles' => 'Ciclos',
    'maxcycles' => 'Nº de renovación máximo',
    'currentcycle' => 'Nº de renovación actual',
    'noc' => 'Localización',
    'price' => 'Precio',
    'changestate' => 'Estado cambiado con éxito.',
    'renew' => 'Renovar',
    'terminate' => 'Terminar',
    'suspend' => 'Suspender',
    'unsuspend' => 'Quitar suspenso',
    'refund' => 'Reembolso',
    'upgrade' => [
      'title' => 'Mejorar',
      'manage' => 'Mejora del servicio',
      'actual' => 'Oferta actual',
      'btn' => 'Cambiar a esta oferta',
    ],
    'cancel' => [
      'title' => 'Cancelar el servicio',
      'subtitle' => 'Su servicio se detendrá el %date%',
      'reason' => 'Motivo de la cancelación',
      'button' => 'Parar',
      'uncancelbtn' => 'Reanudar',
      'uncancel' => 'La cancelación de su servicio acaba de ser anulada',
      'cancel' => 'Se acaba de solicitar la cancelación del servicio',
    ],
    'makeaction' => 'Realizar la acción',
    'options' => [
      'title' => 'Gestión de opciones',
      'empty' => 'No hay opcion disponible para este servicio',
      'your_options' => 'Opciones',
      'new_price' => 'Precio nuevo',
      'prorata' => 'Prorata',
      'per_month' => 'Cada %months% meses',
      'today' => 'a pagar hoy',
    ],
  ],
  'transactionpage' => [
    'summary' => 'Resumen del pedido',
    'summarysub' => 'No todos los elementos de esta lista pueden ser eliminados.',
    'issuedby' => 'Emitido por',
    'delivred' => 'Entrega',
    'success' => 'Exitosamente',
    'refunded' => 'Reembolsado',
    'pending' => 'En curso',
    'pending2' => 'Entrega en curso',
    'make' => 'Pagar ahora',
    'id' => 'Identificador',
    'info' => 'Información sobre las transacciones',
    'items' => 'Nº de artículos',
  ],
  'options' => [
    'core' => [
      'title' => 'Cores adicionales',
      'unit' => 'Core(s)',
    ],
    'swap' => [
      'title' => 'Swap adicional',
      'unit' => 'options.swap.unit',
    ],
    'min_value' => 'Valor mínimo',
    'min_valuesub' => '(0 recomendado para la opción adicional, 3 para la opción obligatoria requerida)',
    'max_value' => 'Valor máximo',
    'backup' => [
      'title' => 'Copia de seguridad adicional',
      'unit' => 'Copia(s) de seguridad',
    ],
    'additional' => 'Complemento',
    'unit_price' => 'Precio por unidad',
    'createcustom' => 'Nueva opción de personalización',
    'values' => 'Valores permitidos (Sólo a elegir)',
    'fieldname' => 'Etiqueta del campo',
    'title' => 'Opciones adicionales',
    'disk' => [
      'title' => 'Espacio en disco adicional',
    ],
    'ip' => [
      'title' => 'Dirección IP adicional',
      'unit' => 'Dirección(es) IP',
    ],
    'servername' => [
      'title' => 'Nombre del servidor',
    ],
    'memory' => [
      'title' => 'Memoria adicional',
    ],
    'database' => [
      'title' => 'Base de datos adicional',
      'unit' => 'Base(s) de datos',
    ],
    'allocation' => [
      'title' => 'Asignación adicional',
      'unit' => 'Asignación(es)',
    ],
    'bandwidth' => [
      'title' => 'Ancho de banda del servidor',
      'unit' => 'gb/s',
    ],
    'server' => [
      'title' => 'Servidor adicional',
      'unit' => 'Servidor(es)',
    ],
  ],
  'best_sales' => 'Mas vendidos',
  'discount' => 'Descuento',
  'your_order' => 'Pedido',
  'recurring' => 'Recurrente',
  'deals' => 'Ofertas',
  'pay_with' => 'Pagar con',
  'payment_cancel' => 'Pago cancelado con éxito.',
  'return' => [
    'btn' => 'Más detalles',
    'Pending' => [
      'state' => 'Pendiente',
      'title' => 'Pedido en espera.',
      'content' => 'Su pedido acaba de ser puesto en espera.',
    ],
    'Refunded' => [
      'state' => 'Reembolsado',
      'title' => 'Pedido reembolsado.',
      'content' => 'Su pedido acaba de ser reembolsado.',
    ],
    'title' => 'Seguimiento de su pedido',
    'Draft' => [
      'state' => 'Proyecto',
      'title' => 'Proyecto pedido.',
      'content' => 'Tu proyecto acaba de ser elaborado.',
    ],
    'Completed' => [
      'state' => 'Completado',
      'title' => 'Pedido validado con éxito.',
      'content' => 'Su pedido acaba de ser validado',
    ],
    'Cancelled' => [
      'state' => 'Cancelado',
      'title' => 'Pedido anulado.',
      'content' => 'Su pedido acaba de ser cancelado.',
    ],
    'Refused' => [
      'state' => 'Rechazado',
      'title' => 'Pedido rechazado.',
      'content' => 'Para más información, póngase en contacto con el servicio de asistencia técnica.',
    ],
  ],
  'shopadmin' => [
    'dashboard' => [
      'transactions' => 'Transacciones realizadas',
      'transactionmustbecancelled' => 'Algunos productos han sido eliminados, algunas transacciones no pueden ser entregadas. Anule las transacciones de %ids% para entregar las otras transacciones que esperan ser entregadas.',
    ],
    'quotes' => [
      'info' => 'Información del presupuesto',
      'details' => 'Detalles del presupuesto',
      'sendmail' => 'Enviar correo',
      'description' => 'Descripción',
      'maketransaction' => 'Realizar la transacción',
      'refuse' => 'Rechazar',
      'accept' => 'Aceptar',
      'seetransaction' => 'Ver transacción',
      'addrow' => 'Añadir fila',
      'finish' => 'Completar la oferta',
      'title' => 'Presupuestos',
      'subtitle' => 'Gestionar los presupuestos del sistema.',
      'note_admin' => 'Nota para los administradores',
      'note' => 'Nota para el cliente',
    ],
    'orders' => [
      'webhook' => [
        'url' => 'Url del webhook',
        'title' => 'Ejecutar el webhook en el pedido',
        'variables' => 'Variable disponible',
      ],
      'title' => 'Pedidos',
      'subtitle' => 'Gestionar los pedidos del sistema.',
      'confirmed' => 'Confirmado',
      'validateorder' => 'Validar los pedidos',
      'data' => 'Gestionar el orden de los datos %id%',
    ],
    'domains' => [
      'title' => 'Dominios',
      'subtitle' => 'Manage the domains of the system.',
      'domain' => 'Domain',
      'type' => 'Tipo',
    ],
    'subdomains' => [
      'title' => 'Subdominios',
      'subtitle' => 'Gestionar los subdominios del sistema.',
      'domain' => 'Dominio',
      'type' => 'Tipo',
    ],
    'group' => [
      'col' => 'Número de columnas',
      'colproduct' => 'Número de productos en la página del grupo',
      'name' => 'Nombre del grupo',
      'add' => 'Añadir un producto en este grupo',
      'seeinclientarea' => 'Ver en el área de clientes',
      'meta_description' => 'Meta descripción',
      'title' => 'Grupos',
      'subtitle' => 'Gestionar los grupos de la tienda.',
      'headline' => 'Línea principal',
      'parent' => 'Padre',
      'delete' => 'Eliminar el grupo',
      'products' => 'Productos asociados al grupo',
      'ribbon_color' => 'Color de la cinta (opcional)',
      'ribbon' => 'Texto de la cinta (opcional)',
      'upgradable' => 'Los productos de este grupo son mejorables',
      'downgradable' => 'Los productos de este grupo pueden degradarse',
      'pageheadline' => 'Descripción en la página de grupo',
    ],
    'discount' => [
      'global' => '¿El descuento debe estar activo en toda la tienda?',
      'start_at' => 'Inicio',
      'end_at' => 'Fin',
      'months' => 'No. de ciclo donde se aplica la reducción',
      'title' => 'Descuentos',
      'subtitle' => 'Gestionar los descuentos de la tienda.',
      'month' => 'Nº de meses',
      'required' => 'Producto requerido',
      'requiredsub' => 'Uno de los productos debe estar en la cesta para que se aplique el descuento',
    ],
    'board' => [
      'conversionRate' => 'Índice de conversión',
      'frombeginning' => 'Desde el inicio',
      'title' => 'Tabla de ingresos',
      'subtitle' => 'Esta es la declaración actual de los ingresos.',
      'counts' => [
        'monthly' => 'Este mes',
        'yearly' => 'This yearly',
        'alltime' => 'Desde siempre',
        'since' => 'Desde el mes pasado',
        'last' => 'El año pasado',
        'today' => 'Hoy',
      ],
      'others' => 'Pedidos sin finalizar',
      'completed' => 'Pedidos finalizados',
      'overview' => 'Resumen',
      'clear' => [
        'development' => 'Este botón sólo está disponible en el entorno de desarrollo',
        'button' => 'Vaciar la tabla de ingresos',
        'text' => 'Al borrar la tabla de ingresos, se eliminarán los servicios, transacciones, pedidos y todo lo relacionado con la facturación.',
      ],
    ],
    'banner' => [
      'background' => 'Background',
      'title' => 'Añade un banner informativo a tu zona de clientes',
      'content' => 'Contenido',
    ],
    'transaction' => [
      'title' => 'Transacciones',
      'subtitle' => 'Gestionar las transacciones de la tienda.',
      'info' => 'Información sobre las transacciones',
      'subtitlecreate' => 'Añadir una transacción ya realizada en el sistema.',
      'linktopay' => 'Enlace al pago',
      'sendbyemail' => 'Enviar por email',
      'createtransaction' => 'Para crear una transacción para un cliente vaya a <a href=\'%link%\'>aquí</a>',
    ],
    'product' => [
      'allowqty' => 'Permitir múltiples servicios por cliente',
      'outstock' => 'Poner fuera de stock',
      'paymenttypes' => [
        'title' => 'Forma de pago',
      ],
      'taxes' => [
        'title' => 'Tablas de comisiones',
        'subtitle' => 'Encontrará los precios de sus productos con las comisiones de la pasarela de pago',
        'paypalfees' => 'Después de las comisiones de Paypal',
        'stripefees' => 'Después de las comisiones de Stripe',
        'info' => 'Las comisiones son previsiones, pueden ser diferentes cuando se realiza un pago.',
        'flash' => [
          'title' => '¡Novedad! ',
          'content' => 'Hemos añadido una tabla con las tarifas de las pasarelas de pago en sus ofertas. <a href=\'%link%\' class=\'text-reset\'>Pulse aquí para acceder</a>',
        ],
      ],
      'config' => 'Configuración del producto',
      'title' => 'Productos',
      'group' => 'Grupo',
      'showdomainoptions' => 'Mostrar la opción de dominio',
      'stockcontrol' => 'Control de stock',
      'subtitle' => 'Gestionar los productos de la tienda',
      'welcomeemail' => '--',
      'link' => 'Enlace para añadir un producto',
      'recurringcycles' => 'Limitar el número de renovaciones de una suscripción (0 = ilimitado)',
      'autoterminatedays' => 'Número de días antes de la finalización de la oferta',
      'autoterminateemail' => '--',
      'autoterminate' => 'Activación de duración determinada (por ejemplo, pruebas gratuitas, productos de duración limitada)',
      'recurringcyclestitle' => 'Límite (0 = ilimitado)',
      'stock' => 'Stocks',
      'order' => 'Pedir',
      'ondemand' => 'Oferta bajo petición',
      'ondemandhelp' => 'Cuando su cliente quiera comprar esta oferta será redirigido a la creación de una solicitud de ayuda',
      'name' => 'Nombre del producto',
      'crosssellproducts' => 'Venta cruzada de productos',
      'autocreate' => 'Creación automática del servicio',
    ],
    'upgrades' => [
      'title' => 'Mejoras',
      'subtitle' => 'Administrar las mejoras del servicio del sistema.',
      'make' => 'Mejorar un servicio',
      'clientmustpay' => '¿El cliente tiene que pagar la factura?',
      'cannot' => 'El producto real no puede mejorarse. Póngase en contacto con el servicio de asistencia',
      'prorata' => 'Prorata',
      'newproduct' => 'Nuevo producto',
      'oldproduct' => 'Producto antiguo',
    ],
    'options' => [
      'title' => 'Opciones',
      'subtitle' => 'Administrar las opciones de productos del sistema.',
    ],
    'services' => [
      'manage' => 'Manage the service from your administration area',
      'manage2' => 'Manage the service from your client area',
      'discount' => [
        'months' => 'Nº de meses',
        'price' => 'Precio de reducción',
        'details' => 'Este servicio se cobrará %price% durante los primeros ciclos de %months%',
      ],
      'title' => 'Servicios',
      'subtitle2' => 'Services that must be delivered are displayed here.',
      'subtitle' => 'Manage the services of the system.',
      'manual' => 'Manually add the service',
      'auto' => 'Deliver a service automatically',
    ],
    'transactiontemplate' => [
      'title' => 'Transacciones',
      'subtitle' => 'Gestionar las transacciones a través de %type% hecho de la tienda.',
    ],
    'payment' => [
      'subtitle' => 'Si desea añadir los impuestos directamente a cada pago para recibir el importe exacto de la transacción sin los impuestos añadidos por los medios de pago',
    ],
    'subscriptions' => [
      'title' => 'Subscripciones',
      'subtitle' => 'Administrar las suscripciones al sistema.',
      'lastrenewal' => 'Última renovación',
      'nextrenewal' => 'Próxima renovación',
      'month' => 'Información de previsión para el mes de %month% calculada sobre %date%',
      'income' => 'Ingresos por suscripción',
    ],
    'coupon' => [
      'title' => 'Cupones',
      'subtitle' => 'Gestionar los cupones de la tienda.',
      'amount' => 'Importe mínimo de la cesta para acceder a este cupón',
      'maxuses' => 'Número de usos autorizados (0 = Sin límite)',
      'onceperclient' => 'Permitir sólo un uso por cliente',
      'need' => 'Restringir el código del cupón a productos específicos que ya posee el cliente',
      'usage' => 'Número de usos',
    ],
  ],
  'order2' => 'Comprar',
  'day_orders' => 'Compras de dias',
  'groups' => 'Grupos',
  'fromgroup' => 'Desde %price%',
  'couponmessages' => [
    'success' => 'Cupón añadido con éxito',
    'error' => 'El cupón no es válido',
    'recalculate' => 'Cupón actualizado',
    'alreadyUsed' => 'No puedes usar el código promocional dos veces!',
    'inactive' => 'Este código promocional no está activo',
    'amount' => 'El importe del carro debe ser como mínimo %amount%',
    'items' => 'El carro debe tener al menos  %amount% Elementos',
    'need' => 'Debes tener los siguientes servicios para añadir el código promocional: %names%',
    'required' => 'Debe tener uno de los siguientes artículos para activar el descuento: %names%.',
  ],
  'transactionstates' => [
    'Draft' => 'Proyecto',
    'Refused' => 'Rechazado',
    'Completed' => 'Terminado',
    'Cancelled' => 'Cancelado',
    'Refunded' => 'Reintegrado',
    'Pending' => 'Pendiente',
  ],
  'ordershow' => [
    'order' => [
      'title' => 'Seguimiento del pedido N° %id%',
    ],
    'items' => [
      'title' => 'Resumen del pedido',
      'pending' => 'Entrega en preparación',
      'delivred' => 'Entrega realizada el %date%',
      'refunded' => 'Entrega reembolsada el %date%',
    ],
    'history' => [
      'title' => 'Su historial de pedidos',
    ],
  ],
  'converter' => [
    'title' => 'Convertidor',
    'mb' => 'Escriba su número en MB',
    'gb' => 'Escriba su número en GB',
  ],
  'your_quote' => 'Presupuesto',
  'your_transactions' => 'Transacciones',
  'coupon_input' => 'Código del cupón',
  'checkout_empty' => 'Actualmente no tiene productos en su pedido.',
  'checkout_subscription' => 'Solicito una suscripción para renovar automáticamente el servicio si es posible mediante el método de pago',
  'errorallowqty' => 'No puedes pedir el producto %productname% por segunda vez.',
  'must_auth' => 'Debe iniciar sesión para hacer un pedido',
  'must_confirmed' => 'Debe estar confirmado para hacer un pedido',
  'onetime' => 'Una sola vez',
  'domaindata' => [
    'title' => 'Elija un dominio',
    'headingUpdate' => 'Utilizar un nombre de dominio existente y actualizar los servidores de nombres',
    'headingSubdomain' => 'Usar un subdominio de %app_name%',
  ],
  'note' => 'Nota',
  'walletinsufficient' => 'Tu saldo es insuficiente',
  'quotestate' => [
    'Refused' => 'Rechazado',
    'Accepted' => 'Aceptado',
    'Pending' => 'Pendiente',
    'Draft' => 'Proyecto',
  ],
  'saved' => 'de ahorro',
  'your_services' => 'Servicios',
  'your_quotes' => 'Presupuestos',
  'your_orders' => 'Compras',
  'our_products' => 'Productos',
  'order_product' => 'Comprar',
  'remaining_time' => 'Tiempo restante',
  'coupon' => 'Cupón',
  'utilities' => 'Utilidades',
  'cross_selling_title' => 'Productos que te pueden interesar',
  'instock' => '%count% en stock',
  'coupons' => 'Cupones',
  'services' => 'Servicios',
  'for' => 'Para',
  'reason' => 'Razón',
  'vat' => 'VAT',
  'products' => 'Productos',
  'order_comment' => [
    'label' => 'Comentario',
    'placeholder' => 'Comenta tu pedido.',
  ],
  'order' => 'Comprar',
  'paymenttype' => 'Tipo de pago',
  'initial_price' => 'Precio inicial',
];