<?php
/**$
    Support - es_ES
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'department' => 'Departamento',
  'support.related' => 'Servicio/Transacción relacionada',
  'support.admin.department.title' => 'Departamento',
  'support.admin.department.subtitle' => 'Gestionar los diferentes departamentos de soporte',
  'support.show.our_reply' => 'Nuestra respuesta',
  'support.show.your_reply' => 'Tu respuesta',
  'support.priority' => 'Prioridad',
  'support.priorities.High' => 'Alta',
  'support.priorities.Medium' => 'Media',
  'support.priorities.Low' => 'Baja',
  'departments' => 'Departamentos',
  'your_tickets' => 'Tus tickets',
  'new_ticket' => 'Nuevo ticket',
  'reply' => 'Respuesta',
  'open_tickets' => 'Tickets abiertos',
  'predefinedreplies' => 'Respuestas predefinidas',
  'predefinedreply' => 'Respuesta predefinida',
  'support.actions.close' => 'Ticket creado con éxito',
  'support.actions.reply' => 'La respuesta acaba de ser publicada',
  'support.table.last_updated' => 'Última actualización',
  'support.table.close' => 'Cerrar',
  'support.table.priority' => 'Prioridad',
  'support.table.department' => 'Departamento',
  'support.table.subject' => 'Asunto',
  'support.admin.ticket.createsubtitle' => 'Abrir un ticket para un cliente específico.',
  'support.email.title' => 'Respuesta de nuestro soporte para el ticket %subject%',
  'support.email.content' => 'Nuestro soporte acaba de responder a su solicitud de ayuda. Puede consultarlo haciendo clic en el botón de arriba.',
  'support.email.button' => 'Mi ticket',
  'support.show.reopentext' => 'Su ticket está actualmente cerrado, puede reabrirlo haciendo clic en el botón.',
  'support.show.reopen' => 'Reabrir ticket',
  'support.show.your_question' => 'Tu pregunta',
  'support.department' => 'Departamento',
  'support.discussion' => 'Discusión',
  'support.content' => 'Contenido',
  'support.newticket' => 'Nuevo ticket',
  'support.submit' => 'Enviar',
  'tickets' => 'Tickets',
  'support.title' => 'Soporte técnico',
  'support.messages' => 'Mensajes',
  'support.replied' => 'Usted respondió',
  'support.icon' => 'Icono',
  'support.informations' => 'Información',
  'support.actions.reopen' => 'El ticket acaba de ser reabierto.',
  'support.actions.submit' => 'Ticket creado con éxito',
  'support.admin.predefined.title' => 'Respuestas predefinidas',
  'support.admin.predefined.create' => 'Puede crear respuestas predefinidas <a href="%route%" target="_blank">aquí</a>',
  'support.admin.predefined.subtitle' => 'Gestionar las diferentes respuestas predefinidas del soporte',
  'support.admin.predefined.global' => 'La respuesta puede estar disponible para todo el personal',
  'support.admin.predefined.tips' => '<strong>[LASTNAME]</strong> - Apellido del cliente  | <strong>[FIRSTNAME]</strong> - Nombre del cliente | <strong>[EMAIL]</strong> - Correo electrónico del cliente | <strong>[RELATED]</strong> Nombre de la transacción/servicio relacionado (si se define)',
  'support.admin.ticket.title' => 'Soporte',
  'support.admin.ticket.subtitle' => 'Administrar los diferentes tickets de soporte',
  'support.show.reply' => 'Respuesta',
  'support.show.textarea' => 'Por favor, detalle su problema lo más posible. 
 No dé ninguna información confidencial (contraseñas, ...), nuestros técnicos tienen toda la información necesaria para resolver su problema',
  'support.states.Pending' => 'Pendiente',
  'support.states.Reply Support' => 'Respuesta del soporte',
  'support.states.Reply Customer' => 'Respuesta del cliente',
  'support.states.Closed' => 'Cerrado',
  'support.print' => 'Imprimir',
  'support.admin' => 'Notificación al personal por correo electrónico',
  'servicespage.options.manage' => '¿Necesita una IP adicional o más espacio en disco?',
];