<?php
/**$
    translator - es_ES
    CLIENTXCMS Translator system - Exported on 2023-06-25 22:02:19
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'translatesitems' => [
    'true' => 'El valor debe ser verdadero.',
    'false' => 'El valor debe ser falso.',
    'boolean' => 'El valor debe ser un booleano válido.',
    'int' => 'El valor debe ser un número válido.',
    'negative' => 'El valor debe ser negativo.',
    'positive' => 'El valor debe ser positivo.',
    'numeric' => 'El valor debe ser numérico.',
    'between' => 'El valor debe estar entre %d y %d.',
    'inArray' => 'El valor no existe en estos valores : %s',
    'notInArray' => 'El valor no tiene por qué existir en estos valores : %s',
    'arrayHasKey' => 'La tabla debe contener la clave %s',
    'unique' => 'El valor debe ser único en la base de datos',
    'arrayHasNotKey' => 'La tabla no debe contener la clave %s',
    'filetype' => 'El campo no es un formato válido (%s)',
    'uploaded' => 'Debe cargar un archivo.',
    'required' => 'El valor debe ser requerido.',
    'empty' => 'El valor no puede estar vacío.',
    'slug' => 'El valor debe ser un slug válido.',
    'max' => 'El número debe ser inferior a %d',
    'min' => 'El número debe ser como mínimo %d',
    'minLength' => 'El valor debe contener más de %d caracteres.',
    'maxLength' => 'El valor debe contener menos de %d caracteres.',
    'betweenLength' => 'El valor debe contener entre %d y %d caracteres.',
    'bannedEmail' => 'La dirección de correo electrónico o el nombre de dominio están prohibidos.',
    'email' => 'El valor debe ser un email válido.',
    'invalidip' => 'el valor debe ser una dirección IP válida.',
    'url' => 'El valor debe ser una url válida.',
    'domain' => 'El valor debe ser un dominio válido.',
    'equals' => 'El valor debe ser igual a su confirmación.',
    'ispassword' => 'La contraseña debe ser la actual.',
    'phonenumber' => 'El valor debe ser un número de teléfono válido.',
    'postcode' => 'El valor debe ser un código postal válido (%s).',
    'numericOrZero' => 'El valor debe ser un número válido o igual a cero.',
    'positiveOrZero' => 'El valor debe ser positivo o igual a cero.',
    'license' => '%s',
    'exists' => 'El valor debe existir en la base de datos.',
    'ispast' => 'La fecha debe ser pasada.',
    'isfuture' => 'La fecha debe estar en el futuro.',
    'startswith' => 'El valor debe comenzar con %s.',
    'endswith' => 'El valor debe terminar con %s.',
    'contains' => 'El valor debe contener %s',
    'notcontains' => 'El valor no debe contener %s',
    'passwordsecurity' => 'Su contraseña no es segura. Por favor, utilice otra',
    'sshpublic' => 'La clave SSH debe ser una clave válida',
    'ostemplate' => 'Debe elegir entre una plantilla o un sistema operativo.',
  ],
];