<?php
/**$
    translator - es_ES
    CLIENTXCMS Translator system - Exported on 2023-10-29 12:19:58
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'translatesitems.positive' => 'El valor debe ser positivo.',
  'translatesitems.numeric' => 'El valor debe ser numérico.',
  'translatesitems.between' => 'El valor debe estar entre %d y %d.',
  'translatesitems.inArray' => 'El valor no existe en estos valores : %s',
  'translatesitems.notInArray' => 'El valor no tiene por qué existir en estos valores : %s',
  'translatesitems.arrayHasKey' => 'La tabla debe contener la clave %s',
  'translatesitems.unique' => 'El valor debe ser único en la base de datos',
  'translatesitems.arrayHasNotKey' => 'La tabla no debe contener la clave %s',
  'translatesitems.filetype' => 'El campo no es un formato válido (%s)',
  'translatesitems.maxLength' => 'El valor debe contener menos de %d caracteres.',
  'translatesitems.betweenLength' => 'El valor debe contener entre %d y %d caracteres.',
  'translatesitems.bannedEmail' => 'La dirección de correo electrónico o el nombre de dominio están prohibidos.',
  'translatesitems.email' => 'El valor debe ser un email válido.',
  'translatesitems.invalidip' => 'el valor debe ser una dirección IP válida.',
  'translatesitems.url' => 'El valor debe ser una url válida.',
  'translatesitems.domain' => 'El valor debe ser un dominio válido.',
  'translatesitems.equals' => 'El valor debe ser igual a su confirmación.',
  'translatesitems.ispassword' => 'La contraseña debe ser la actual.',
  'translatesitems.isfuture' => 'La fecha debe estar en el futuro.',
  'translatesitems.startswith' => 'El valor debe comenzar con %s.',
  'translatesitems.endswith' => 'El valor debe terminar con %s.',
  'translatesitems.contains' => 'El valor debe contener %s',
  'translatesitems.notcontains' => 'El valor no debe contener %s',
  'translatesitems.passwordsecurity' => 'Su contraseña no es segura. Por favor, utilice otra',
  'translatesitems.sshpublic' => 'La clave SSH debe ser una clave válida',
  'translatesitems.boolean' => 'El valor debe ser un booleano válido.',
  'translatesitems.int' => 'El valor debe ser un número válido.',
  'translatesitems.negative' => 'El valor debe ser negativo.',
  'translatesitems.max' => 'El número debe ser inferior a %d',
  'translatesitems.min' => 'El número debe ser como mínimo %d',
  'translatesitems.minLength' => 'El valor debe contener más de %d caracteres.',
  'translatesitems.license' => '%s',
  'translatesitems.exists' => 'El valor debe existir en la base de datos.',
  'translatesitems.ispast' => 'La fecha debe ser pasada.',
  'translatesitems.true' => 'El valor debe ser verdadero.',
  'translatesitems.false' => 'El valor debe ser falso.',
  'translatesitems.uploaded' => 'Debe cargar un archivo.',
  'translatesitems.required' => 'El valor debe ser requerido.',
  'translatesitems.empty' => 'El valor no puede estar vacío.',
  'translatesitems.slug' => 'El valor debe ser un slug válido.',
  'translatesitems.phonenumber' => 'El valor debe ser un número de teléfono válido.',
  'translatesitems.postcode' => 'El valor debe ser un código postal válido (%s).',
  'translatesitems.numericOrZero' => 'El valor debe ser un número válido o igual a cero.',
  'translatesitems.positiveOrZero' => 'El valor debe ser positivo o igual a cero.',
  'translatesitems.ostemplate' => 'Debe elegir entre una plantilla o un sistema operativo.',
  'translatesitems.domainIsAlreadyRegistered' => 'Este dominio ya está registrado',
];