<?php
/**$
    VirtualizorCloud - es_ES
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'virtualizorcloud.offline' => 'offline',
  'virtualizorcloud.online' => 'Online',
  'virtualizorcloud.planname' => 'Nombre del plan',
  'virtualizorcloud.graph' => 'Gráfico',
  'virtualizorcloud.panel.disk' => 'Espacio del disco',
  'virtualizorcloud.panel.cores' => 'Cores',
  'virtualizorcloud.panel.in' => 'Acceso',
  'virtualizorcloud.panel.out' => 'Salir',
  'virtualizorcloud.form.resources.priority' => 'Prioridad de E/S (OpenVZ)',
  'virtualizorcloud.form.resources.vnc' => 'VNC habilitado (KVM)',
  'virtualizorcloud.form.resources.speed' => 'Velocidad de la red en KB/s (0GB/s o vacío para no tener límite)',
  'virtualizorcloud.form.resources.server' => 'Servidor',
  'virtualizorcloud.form.stockage.space' => 'Espacio en disco (GB)',
  'virtualizorcloud.form.cpu.cores' => 'Cores',
  'virtualizorcloud.form.cpu.units' => 'Unidades',
  'virtualizorcloud.form.cpu.cpu' => 'CPU en %',
  'virtualizorcloud.form.ips.internalips' => 'Número de direcciones IP internas',
  'virtualizorcloud.form.ips.ips' => 'Nombre d\'IPs',
  'virtualizorcloud.admin.title' => 'Configuración del Virtualizor',
  'virtualizorcloud.admin.subtitle' => 'Administrar las configuraciones de sus ofertas.',
  'virtualizorcloud.admin.planname' => 'Nombre del plan',
  'virtualizorcloud.config.title' => 'Configurar su oferta',
  'virtualizorcloud.hostname' => 'Alojamiento',
  'virtualizorcloud.os' => 'OS',
  'virtualizorcloud.panel.restart' => 'Reiniciar',
  'virtualizorcloud.panel.os_name' => 'Os',
  'virtualizorcloud.panel.bandwidth' => 'Ancho de banda',
  'virtualizorcloud.panel.ram' => 'RAM',
  'virtualizorcloud.panel.virt' => 'Virtualización',
  'virtualizorcloud.panel.cpu' => 'CPU',
  'virtualizorcloud.panel.reset' => 'Reinstalar',
  'virtualizorcloud.form.resources.title' => 'Recursos',
  'virtualizorcloud.form.resources.disk' => 'Espacio en disco (GB)',
  'virtualizorcloud.form.resources.io' => 'Block IO',
  'virtualizorcloud.form.resources.bandwidth' => 'Ancho de banda (0GB o vacío para no tener límite)',
  'virtualizorcloud.form.resources.inodes' => 'INode (OpenVZ)',
  'virtualizorcloud.form.resources.network_speed' => 'Velocidad de la red en MB/s',
  'virtualizorcloud.form.resources.upload_speed' => 'Velocidad de descarga en MB/s',
  'virtualizorcloud.form.stockage.title' => 'Almacenamiento',
  'virtualizorcloud.form.stockage.ram' => 'RAM MB  (KVM, LXC)',
  'virtualizorcloud.form.stockage.guaranteed' => 'Ram garantizada (MB)',
  'virtualizorcloud.form.stockage.burstable' => 'Ram cotizable (OpenVZ)',
  'virtualizorcloud.form.configurations.group' => 'Grupo',
  'virtualizorcloud.form.configurations.vnc' => 'VNC',
  'virtualizorcloud.form.ips.ip6subnet' => 'Número de direcciones IPV6',
  'virtualizorcloud.form.ips.ip6' => 'Número de direcciones de subred IPv6',
  'virtualizorcloud.productname' => 'Nombre del producto',
  'virtualizorcloud.choosehostname' => 'Elige un nombre de host personalizado',
  'virtualizorcloud.panel.button' => 'Conexión',
  'virtualizorcloud.panel.start' => 'Iniciar',
  'virtualizorcloud.panel.stop' => 'Detener',
  'virtualizorcloud.panel.powerstop' => 'Forzar apagado',
  'virtualizorcloud.panel.usage' => 'Uso',
  'virtualizorcloud.panel.site' => 'Abrir el sitio',
  'virtualizorcloud.panel.information' => 'Información sobre el servicio',
  'virtualizorcloud.panel.problem' => '¿Tienes problemas con el servicio?',
  'virtualizorcloud.panel.openticket' => 'Abrir ticket!',
  'virtualizorcloud.panel.uptime' => 'Tiempo de funcionamiento',
  'virtualizorcloud.form.resources.ip6' => 'IPv6',
  'virtualizorcloud.form.resources.ip6subnet' => 'Ip6subnet',
  'virtualizorcloud.form.resources.ips' => 'Ips',
  'virtualizorcloud.form.resources.oses' => 'Os disponibles (separados por comas)',
  'virtualizorcloud.form.resources.internalips' => 'IP interna',
  'virtualizorcloud.form.resources.portrange' => 'Puerto a asignar al servidor (separado por comas)',
  'virtualizorcloud.form.cpu.title' => 'CPU',
  'virtualizorcloud.form.converter.title' => 'Convertidor',
  'virtualizorcloud.form.converter.mb' => 'Escriba su número en MB',
  'virtualizorcloud.form.converter.gb' => 'Escriba su número en GB',
  'virtualizorcloud.form.configurations.title' => 'Configuración',
  'virtualizorcloud.form.configurations.server' => 'Servidor',
  'virtualizorcloud.config.subtitle' => 'Administrar las características de la oferta.',
  'virtualizorcloud.converter.title' => 'Convertidor',
  'virtualizorcloud.converter.mb' => 'Escriba su número en MB',
  'virtualizorcloud.converter.gb' => 'Escriba su número en GB',
];