<?php
/**$
    VirtualizorCloud - es_ES
    CLIENTXCMS Translator system - Exported on 2023-07-26 13:50:50
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'kvm' => 'KVM',
  'openvz' => 'OpenVZ',
  'lxc' => 'LXC',
  'virtualizorcloud' => [
    'hostname' => 'Alojamiento',
    'os' => 'OS',
    'offline' => 'offline',
    'online' => 'Online',
    'planname' => 'Nombre del plan',
    'productname' => 'Nombre del producto',
    'choosehostname' => 'Elige un nombre de host personalizado',
    'graph' => 'Gráfico',
    'panel' => [
      'button' => 'Conexión',
      'start' => 'Iniciar',
      'stop' => 'Detener',
      'powerstop' => 'Forzar apagado',
      'restart' => 'Reiniciar',
      'os_name' => 'Os',
      'bandwidth' => 'Ancho de banda',
      'ram' => 'RAM',
      'virt' => 'Virtualización',
      'cpu' => 'CPU',
      'disk' => 'Espacio del disco',
      'cores' => 'Cores',
      'in' => 'Acceso',
      'out' => 'Salir',
      'usage' => 'Uso',
      'site' => 'Abrir el sitio',
      'information' => 'Información sobre el servicio',
      'problem' => '¿Tienes problemas con el servicio?',
      'openticket' => 'Abrir ticket!',
      'uptime' => 'Tiempo de funcionamiento',
      'reset' => 'Reinstalar',
    ],
    'form' => [
      'resources' => [
        'title' => 'Recursos',
        'disk' => 'Espacio en disco (GB)',
        'io' => 'Block IO',
        'bandwidth' => 'Ancho de banda (0GB o vacío para no tener límite)',
        'inodes' => 'INode (OpenVZ)',
        'priority' => 'Prioridad de E/S (OpenVZ)',
        'vnc' => 'VNC habilitado (KVM)',
        'speed' => 'Velocidad de la red en KB/s (0GB/s o vacío para no tener límite)',
        'server' => 'Servidor',
        'ip6' => 'IPv6',
        'ip6subnet' => 'Ip6subnet',
        'ips' => 'Ips',
        'oses' => 'Os disponibles (separados por comas)',
        'internalips' => 'IP interna',
        'portrange' => 'Puerto a asignar al servidor (separado por comas)',
        'network_speed' => 'Velocidad de la red en MB/s',
        'upload_speed' => 'Velocidad de descarga en MB/s',
      ],
      'stockage' => [
        'title' => 'Almacenamiento',
        'ram' => 'RAM MB  (KVM, LXC)',
        'guaranteed' => 'Ram garantizada (MB)',
        'burstable' => 'Ram cotizable (OpenVZ)',
        'space' => 'Espacio en disco (GB)',
      ],
      'cpu' => [
        'cores' => 'Cores',
        'units' => 'Unidades',
        'cpu' => 'CPU en %',
        'title' => 'CPU',
      ],
      'converter' => [
        'title' => 'Convertidor',
        'mb' => 'Escriba su número en MB',
        'gb' => 'Escriba su número en GB',
      ],
      'configurations' => [
        'title' => 'Configuración',
        'server' => 'Servidor',
        'group' => 'Grupo',
        'vnc' => 'VNC',
      ],
      'ips' => [
        'ip6subnet' => 'Número de direcciones IPV6',
        'ip6' => 'Número de direcciones de subred IPv6',
        'internalips' => 'Número de direcciones IP internas',
        'ips' => 'Nombre d\'IPs',
      ],
    ],
    'admin' => [
      'title' => 'Configuración del Virtualizor',
      'subtitle' => 'Administrar las configuraciones de sus ofertas.',
      'planname' => 'Nombre del plan',
    ],
    'config' => [
      'title' => 'Configurar su oferta',
      'subtitle' => 'Administrar las características de la oferta.',
    ],
    'converter' => [
      'title' => 'Convertidor',
      'mb' => 'Escriba su número en MB',
      'gb' => 'Escriba su número en GB',
    ],
  ],
];