<?php
/**$
    Virtualizor - es_ES
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'virtualizor.panel.stop' => 'Detener',
  'virtualizor.panel.powerstop' => 'Forzar apagado',
  'virtualizor.panel.restart' => 'Reiniciar',
  'virtualizor.panel.os_name' => 'Os',
  'virtualizor.panel.openticket' => 'Abrir ticket!',
  'virtualizor.panel.uptime' => 'Tiempo de actividad',
  'virtualizor.panel.reset' => 'Reinstalar',
  'virtualizor.admin.title' => 'Configuración del Virtualizor',
  'virtualizor.productname' => 'Nombre del producto',
  'virtualizor.graph' => 'Gráfico',
  'virtualizor.panel.button' => 'Conexión',
  'virtualizor.panel.start' => 'Iniciar',
  'virtualizor.panel.in' => 'Acceso',
  'virtualizor.panel.out' => 'Salir',
  'virtualizor.panel.usage' => 'Uso',
  'virtualizor.panel.site' => 'Abrir el sitio',
  'virtualizor.panel.information' => 'Información sobre el servicio',
  'virtualizor.panel.problem' => '¿Tienes problemas con el servicio?',
  'virtualizor.converter.gb' => 'Introduce tu número en GB',
  'kvm' => 'KVM',
  'openvz' => 'OpenVZ',
  'lxc' => 'LXC',
  'virtualizor.hostname' => 'Alojamiento',
  'virtualizor.os' => 'OS',
  'virtualizor.offline' => 'offline',
  'virtualizor.online' => 'Online',
  'virtualizor.planname' => 'Nombre del plan',
  'virtualizor.panel.bandwidth' => 'Ancho de banda',
  'virtualizor.panel.ram' => 'RAM',
  'virtualizor.panel.virt' => 'Virtualización',
  'virtualizor.panel.cpu' => 'CPU',
  'virtualizor.panel.disk' => 'Espacio del disco',
  'virtualizor.panel.cores' => 'Cores',
  'virtualizor.admin.subtitle' => 'Administrar las configuraciones de sus ofertas.',
  'virtualizor.admin.planname' => 'Nombre del plan',
  'virtualizor.config.title' => 'Configura tu oferta',
  'virtualizor.config.subtitle' => 'Administrar las características de la oferta.',
  'virtualizor.converter.title' => 'Convertidor',
  'virtualizor.converter.mb' => 'Introduzca el número en MB',
];