<?php
/**$
    Wisp - es_ES
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'Wisp.failed.linkserver' => 'No se ha podido cambiar la contraseña porque el servidor vinculado no existe.',
  'Wisp.failed.retrieveuser' => 'Error en la recuperación del usuario, código de error recibido: %status_code%',
  'Wisp.failed.changepwd' => 'Cambio de contraseña fallido, código de error recibido: %status_code%',
  'Wisp.panel.openticket' => 'Abrir ticket',
  'Wisp.panel.information' => 'Información sobre el alojamiento',
  'Wisp.panel.start' => 'Iniciar',
  'Wisp.form.resources.title' => 'Recursos',
  'Wisp.form.resources.memory' => 'Memoria (MB)',
  'Wisp.form.resources.disk' => 'Espacio en disco (MB)',
  'Wisp.form.configurations.title' => 'Configuración',
  'Wisp.form.configurations.image' => 'Imagen Docker',
  'Wisp.form.configurations.startup' => 'Comando de inicio ',
  'Wisp.failed.alreadycreated' => 'No se ha podido crear el servidor porque ya está creado.',
  'Wisp.failed.changepkgexist' => 'No se ha podido modificar el paquete del servidor porque no existe.',
  'Wisp.failed.suspendexist' => 'Fallo al suspender el servidor porque no existe.',
  'Wisp.failed.unsuspendexist' => 'Fallo en la desconexión del servidor porque no existe.',
  'Wisp.failed.terminateexist' => 'No se ha podido eliminar el servidor porque no existe .',
  'Wisp.failed.satisfying' => 'Imposibilidad de encontrar nodos que satisfagan la demanda.',
  'Wisp.failed.pwdempty' => 'La contraseña no debe estar vacía.',
  'Wisp.failed.suspendserver' => 'Fallo en la suspensión del servidor, código de error recibido: %status_code%',
  'Wisp.failed.unsuspendserver' => 'Fallo en la suspensión del servidor, código de error recibido: %status_code%',
  'Wisp.failed.terminateserver' => 'Fallo en la suspensión del servidor, código de error recibido: %status_code%',
  'Wisp.failed.buildserver' => 'Error en la actualización de la versión del servidor, código de error recibid: %status_code%',
  'Wisp.failed.startupserver' => 'Error en la actualización de inicio del servidor, código de error recibido: %status_code%',
  'Wisp.panel.disk' => 'Espacio en disco ',
  'Wisp.panel.memory' => 'Memoria',
  'Wisp.panel.button' => 'Gestionar mi servidor',
  'Wisp.panel.problem' => '¿Tienes problemas con el servicio?',
  'Wisp.adminindex.subtitle' => 'Gestiona las configuraciones de tus ofertas.',
  'Wisp.adminindex.memory' => 'Memoria',
  'Wisp.adminindex.disk' => 'Espacio en disco',
  'Wisp.adminindex.productname' => 'Nombre del producto',
  'Wisp.migrate.title' => 'Migración Wisp',
  'Wisp.migrate.subtitle' => 'Esta página le permite migrar sus configuraciones de Pterodactyl a Wisp.',
  'Wisp.migrate.info' => 'Esta acción cambiará los tipos de producto, migrará las configuraciones del módulo Pterodactyl al módulo Wisp.',
  'Wisp.config.title' => 'Configuración del servidor',
  'Wisp.config.subtitle' => 'Administrar las diferentes características de la oferta.',
  'Wisp.form.features.title' => 'Características',
  'Wisp.form.features.databases' => 'Bases de datos que se asignarán al servidor',
  'Wisp.form.features.backups' => 'Límite de tamaño de copia de seguridad (MB)',
  'Wisp.form.features.allocations' => 'Asignación (MB)',
  'Wisp.form.core.title' => 'Información',
  'Wisp.form.core.servername' => 'Nombre del servidor',
  'Wisp.form.core.egg' => 'ID Huevo (egg) Wisp',
  'Wisp.form.core.nest' => 'ID Nido (nest) Wisp',
  'Wisp.form.core.location' => 'ID Ubicación Wisp',
  'Wisp.form.converter.gb' => 'Introduce tu número en GB',
  'Wisp.offline' => 'Fuera de linea',
  'Wisp.online' => 'En linea',
  'Wisp.failed.createuser' => 'Creación de usuario fallida, código de error recibido: %status_code%',
  'Wisp.failed.geteggs' => 'No se han podido obtener los datos del huevo, se ha recibido un código de error: %status_code%',
  'Wisp.failed.getserver' => 'Fallo en la obtención de datos del servidor, código de error recibido: %status_code%',
  'Wisp.failed.createserver' => 'Fallo en la creación del servidor, código de error recibido: %status_code%',
  'Wisp.panel.stop' => 'Detener',
  'Wisp.panel.powerstop' => 'Forzar apagado',
  'Wisp.panel.restart' => 'Reiniciar',
  'Wisp.adminindex.title' => 'Configuración de Wisp',
  'Wisp.form.resources.swap' => 'intercambio',
  'Wisp.form.resources.io' => 'Block IO',
  'Wisp.form.resources.portrange' => 'Puerto a asignar al servidor (Ejemplo: 3000-4000)',
  'Wisp.form.resources.cpu' => 'Límite del procesador (%)',
  'Wisp.form.configurations.oomkiller' => 'Desactivado OOM Killer',
  'Wisp.form.configurations.dedicatedip' => 'Dirección IP dedicada',
  'Wisp.form.converter.title' => 'Convertidor',
  'Wisp.form.converter.mb' => 'Introduce tu número en MB',
  'wisp.admin.migratebtn' => 'Migraciones',
];