<?php
/**$
    Admin - en_GB
    CLIENTXCMS Translator system - Exported on 2023-07-04 21:11:55
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'admin' => [
    'delivery' => 'Order delivery',
    'switchtheme' => 'Change theme',
    'backtoadmin' => 'Back to administration',
    'backtosite' => 'Back to the website',
    'documentation' => 'Documentation',
    'support' => 'Support',
    'profile' => [
      'title' => 'Profile',
      'subtitle' => 'Manage your administrator profile',
    ],
    'database' => [
      'title' => 'Database',
      'subtitle' => 'Database management',
      'available_actions' => 'Actions available',
      'main' => 'For more information on how to use phinx, its commands and its many options',
      'clickhere' => 'Click here',
      'version' => 'Version',
      'start_at' => 'Start time',
      'end_at' => 'End time',
      'endpoint' => 'Stopping point',
      'list' => 'List of migrations already carried out',
      'seed' => 'The Seed command runs all available seed classes. For more options and informations',
      'migrate' => 'The Migrate command performs all available migrations. For more options and information',
      'rollback' => 'The Rollback command is used to undo previous migrations performed by Phinx. For more options and information',
    ],
    'themes' => [
      'config' => [
        'sections' => [
          'title' => 'Sections',
          'subtitle' => 'Management of sections of the theme.',
        ],
        'menus' => [
          'title' => 'Menus',
          'addsubmenu' => 'Add sub menu',
          'subtitle' => 'Management of the theme menus.',
        ],
        'footerlinks' => [
          'title' => 'Footer links',
          'subtitle' => 'Footer links management.',
        ],
      ],
      'title' => 'Themes',
      'subtitle2' => 'CLIENTXCMS themes available',
      'author' => 'Author',
      'actual' => 'Current theme',
      'viewspath' => 'Path of views',
      'templatesPath' => 'Main view path',
      'assetsPath' => 'Path of assets',
      'official' => 'Official',
      'ComponentPath' => 'Component path',
      'PluginsPath' => 'Plugin path',
      'downloaded' => 'Downloaded themes',
      'apptitle' => 'Application title',
      'appmobile' => 'Application title for mobile',
      'htmlsupport' => 'HTML support is enabled for the app title.',
      'titlehome' => 'Title Home',
      'subtitle' => 'Home subtitle',
      'btnaction' => 'Button action',
      'btnicon' => 'Button icon',
      'btntext' => 'Button text',
      'primary' => 'Primary color (Stisla and Regal only)',
      'dark' => 'Dark theme',
      'updateglobal' => 'Globally',
      'updateonlyassets' => 'Only assets',
      'updateonlyviews' => 'Only views',
      'noofficial' => 'Switch with unofficial theme',
      'themeemail' => 'Upload email template here',
    ],
    'dashboard' => [
      'subtitle' => 'Welcome to your CLIENTXCMS board',
      'isLatestVersion' => 'CLIENTXCMS is currently in %version%',
      'isBetaOrAlpha' => 'CLIENTXCMS is currently in %version%. <a href=\'%route%\'>Report a problem</a>',
      'statistics' => 'Hosting statistics',
      'cronhours' => 'Warning: your scheduled tasks have not been executed for %hours% hours. Deliveries, suspensions and expirations were not made during this times.',
      'statistiquessub' => 'Find the statistics of your host, whether it is the last registrations, the generated invoices and the active services, everything is there!',
    ],
    'firewall' => [
      'title' => 'Firewall',
      'subtitle' => 'Identity Verification & Authorisation',
      'confirm' => 'Confirm your password to continue',
      'content' => 'You enter an administrative area of ClientXCMS and must confirm your password to continue',
      'confirmation' => 'do you really want to disconnect from the firewall?',
      'btn' => 'Confirm',
      'logout_btn' => 'Exit the firewall',
      'actions' => [
        'badpwd' => 'Bad password',
        'success' => 'Authorisation granted',
        'logout' => 'Successfully disconnected.',
      ],
    ],
    'emailtemplate' => [
      'title' => 'Template Email',
      'subtitle' => 'Manage email template',
    ],
    'license' => [
      'title' => 'License',
      'subtitle' => 'Information related to your licence.',
      'registar' => 'Registered by',
      'key' => 'Licence Key',
      'type' => 'Type of licence',
      'max' => 'No. of Authorised clients',
      'customers' => 'No. of Clients on system',
      'domain' => 'Authorized domain (s)',
      'expire' => 'Expiry',
      'types' => [
        'dev' => 'Development',
        'prod' => 'Production',
        'demo' => 'Demonstration',
        'gift' => 'Gift',
      ],
    ],
    'modules' => [
      'title' => 'Modules',
      'subtitle' => 'Available module.',
      'folder' => 'File',
      'actived' => 'Activated',
      'support' => 'Online support',
      'updatable' => 'Updatable to %tag%',
      'official' => 'Official module',
      'updated' => 'Last updated',
      'changelogbtn' => 'See changelog',
      'changelog' => 'Changelog',
      'about' => 'About',
      'requiredmodules' => 'Required modules',
      'empty' => 'Unable to retrieve modules from the main website is currently unavailable. Please contact support',
      'enable' => 'Enable',
      'refresh' => 'Force refresh',
      'warning' => 'By deactivating this module, it is possible that some page no longer works due to certain features which will no longer be added by this module on the system. Our support will not be able to help you in the event of a problem of this type.',
      'disable' => 'Disable',
      'download' => 'Download',
      'reinstall' => 'Reinstall',
      'update' => 'Update',
      'downloadsucess' => 'Module downloaded/updated successfully.',
      'config' => [
        'title' => 'Module Configuration',
        'subtitle' => 'Configure your API keys for %name%.',
      ],
    ],
    'update' => [
      'translations' => [
        'content' => 'Your language files were last exported on <code>%date%</code>. You can download the new files now.',
      ],
      'title' => 'Update',
      'subtitle' => 'Manage system updates.',
      'warning' => 'Before updating CLIENTXCMS, you should make a backup of your site!',
      'download' => 'Download',
      'unknown' => 'Cannot update CMS because master website is currently down or not available. Please contact support.',
      'info' => 'The version <code>%version1%</code> of CLIENTXCMS is available and you are on version <code>%version2%</code>. The latest version of CLIENTXCMS is ready for download.',
    ],
    'phpinfo' => 'PHPINFO',
    'logs' => [
      'title' => 'History',
      'clear' => 'Clear history',
      'subtitle' => 'Manage the history of CLIENXCMS',
      'masseaction' => 'Mass action',
      'checkall' => 'Select All',
      'delete' => 'Delete',
      'signal' => 'Report',
      'deleteall' => 'Delete selected',
    ],
    'report' => [
      'cron' => [
        'successoftask' => 'Task success',
        'last_schedule' => 'Last Schedule',
        'start_at' => 'Start',
        'end_at' => 'End',
        'failed' => 'Failed',
        'output' => 'Output',
        'exception' => 'Exception',
        'invokenow' => 'Run now',
        'delete' => 'Delete the oldest tasks',
        'successfully' => 'Successfully',
        'task' => 'Task #',
        'time' => 'Time between two executions',
        'minuts' => 'every %minuts% minuts',
        'minut' => 'every minute',
        'hours' => 'every %hours% hours',
        'hour' => 'every hour',
      ],
      'general' => [
        'serverstate' => 'Server state',
        'good' => 'Good',
        'suspended' => 'Suspended services',
        'expired' => 'Expired Services',
      ],
    ],
    'settings' => [
      'cache' => 'Clear app cache',
      'title' => 'Settings',
      'subtitle' => 'Configure your CLIENTXCMS settings here.',
      'saving' => 'Saving...',
      'error' => 'Error',
      'saved' => 'Saved',
      'seo' => [
        'description' => 'Page description',
        'keywords' => 'Key words',
        'favicon' => 'Favicon',
        'head' => 'HTML code to include in the head of all pages',
        'body' => 'HTML code to include in the body of all pages',
        'analytics' => 'ID google analytics',
        'tawk' => 'ID Tawk.to',
        'how_did_you_find_us_options' => '\'How did you find us\' Options',
        'how_did_you_find_us_options_sub' => 'Left blank to deactivate.',
      ],
      'security' => [
        'title' => 'Authentication & Limitation',
        'bannedemails' => 'Banned emails or domains upon registration',
        'authminuts' => 'Minutes limiting connection',
        'authlimit' => 'No. of attempt',
        'authreset' => 'Time to reset your password',
        'tosLinks' => 'Link to the TOS',
        'confirmation' => 'Asks for user account confirmation',
        'resetpwd' => 'Allow user password reset',
        'autoredirecttologin' => 'Automatic redirection of the user to the login page when he tries to access the clientarea',
        '2fa' => [
          'alert' => 'You must enable 2FA to use the administration panel',
          'required_for_admin' => 'Two factor enable to required to access an administrator account',
          'minutes_between' => 'Minutes between 2FA checks (Admin only)',
          'minutes_betweendesc' => '(0 to keep until end of PHP session)',
        ],
        'register' => 'Allow user registration',
        'captcha' => [
          'title' => 'Protect your forms and avoid bots by securing with HCaptcha or Recapcha',
          'validatewith' => 'Validation with',
          'sitekey' => 'Site key',
          'secretkey' => 'Secret key',
          'recapcha' => [
            'title' => 'Configure Google reCaptcha protection',
            'content' => 'You can get reCaptcha keys on the <a href="https://www.google.com/recaptcha/" target="_ blank" rel="noopener noreferrer"> Google reCaptcha website </a>. You must use reCaptcha <strong> v2 invisible </strong> keys.',
          ],
          'hcaptcha' => [
            'title' => 'Configure HCaptcha protection',
            'content' => 'You can get reCaptcha keys on the <a href="https://www.hcaptcha.com/" target = "_ blank" rel= "noopener noreferrer"> HCaptcha website </a>.',
          ],
        ],
      ],
      'global' => [
        'logopdf' => 'Logo on the PDF',
        'logopdfhelp' => 'Recommended height : 90x35',
        'makerenewtransaction_days' => 'No. days before expiration to generate invoice for renewal',
        'locale2' => 'Disable language change',
        'expire_days' => 'Nb. days to terminate service after suspension for expiration',
        'expire_days2' => 'After this period, the service will be expired, and the service will be deleted from the server.',
        'stock_warning' => 'No. of remaining stock to display the remaining stock.',
        'vat' => 'Disable VAT',
        'appname' => 'Hosting name',
        'license' => 'License key',
        'timezone' => 'Time zone',
        'currency' => 'Currency',
        'lang' => 'Language of the page',
        'driver' => 'Image processing extension',
        'enable_addproduct_hidden' => 'Enable add hidden product to basket',
        'failedcreations_max' => 'No. of attempts to create authorised services',
        'locale' => 'Locale',
        'prefix' => 'Client area prefix',
        'logo' => 'Hosting Logo',
        'scheme' => 'HTTP/HTTPS',
        'address' => 'Hosting address',
        'disabled_wallet' => 'Disable wallet payment',
        'disabled_autocreate' => 'Disable automatic creation service',
        'disabled_basket' => 'Disable basket system',
        'upgrade' => [
          'title' => 'Installation fee policy during a service upgrade',
          'default' => 'Charge installation fee normally',
          'diff' => 'Billing the installation fee by subtracting the installation fee from the old product',
          'disable' => 'No billing of installation fees during a service upgrade',
        ],
        'enabledpaywithcredit' => 'Activate the possibility of partially paying invoices with account credits',
      ],
      'mail' => [
        'mailfrom' => 'E-mail address used to send e-mails',
        'sendwithsmtp' => 'Send via SMTP',
        'password' => 'SMTP password',
        'username' => 'SMTP user name',
        'hostname' => 'SMTP host name',
        'port' => 'SMTP port',
        'encryption' => 'Encryption',
        'title' => 'Testing CLIENTXCMS messaging',
        'content' => 'This is a test of the ClientXCMS email system. You are ready to send emails',
      ],
    ],
    'confirmation' => 'Do you really want to do this action?',
    'account' => 'User account',
    'reports' => [
      'loginhistory' => [
        'emailsent' => 'Percentage of emails sent',
        'login' => 'Number of connections per day',
      ],
      'title' => 'Reports',
      'overview' => 'Overview',
      'subtitle2' => 'Manager system reports',
      'subtitle' => 'The reports below provide an analysis of the data held in the system.',
    ],
    'email' => [
      'title' => 'Send email',
      'subtitle' => 'Manage emails sent in system.',
      'sendtoeveryone' => 'Send to everyone',
    ],
    'roles' => [
      'title' => 'Roles',
      'subtitle' => 'Manager roles and permissions of system.',
      'info' => 'When the group is owner it has all the permissions.',
    ],
    'staffs' => [
      'title' => 'Staff',
      'subtitle' => 'Manage staff with access to the administration.',
      'owner' => 'Owner',
      'ownertext' => 'By enabling this option, the administrator could delete your own account without your permission. Give access to the right people',
    ],
    'bannedips' => [
      'title' => 'IP Banned',
      'subtitle' => 'Manage the banned IP addresses.',
      'punisher' => 'Punisher',
      'definitive' => 'Final sanction',
      'reason' => 'Reason for action',
      'expire' => 'Expiry of the sanction',
      'subtitleForCreate' => 'You can apply the same penalty for different IP addresses by separating them with commas.',
    ],
    'servers' => [
      'title' => 'Servers',
      'nameservers' => 'Nameservers',
      'enablemodule' => 'You must at least activate a module providing a service.',
      'details' => 'Server details',
      'subtitle' => 'Manage the servers in the system',
      'name' => 'Name of the Server',
      'authentification' => 'Authentication',
      'testconnect' => 'Test the connection',
      'result' => 'Test result',
      'statuscode' => 'Status code',
      'data' => 'Returned data',
      'add' => [
        'title' => 'Add a new server',
        'subtitle' => 'Used to link a server to CLIENTXCMS',
      ],
      'forms' => [
        'secure' => 'Security',
        'primarynameserver' => 'Primary nameserver',
        'username' => 'Username',
        'password' => 'Password',
        'monthlycost' => 'Monthly cost',
        'customport' => 'Custom port',
        'noc' => 'Location',
        'secondarynameserver' => 'Second Nameserver',
        'thirdnameserver' => 'Third Nameserver',
        'fourthnameserver' => 'Fourth Nameserver',
        'fifthnameserver' => 'Fifth Nameserver',
        'type' => 'Type of server',
        'maxaccounts' => 'Maximum no. of accounts',
      ],
    ],
  ],
  'configuration' => [
    'update' => 'Configuration successfully saved.',
    'delete' => 'Configuration successfully deleted.',
    'create' => 'Configuration successfully created.',
  ],
];