<?php
/**$
    Proxmox - en_GB
    CLIENTXCMS Translator system - Exported on 2023-09-18 18:25:43
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'proxmox.console' => 'Console',
  'proxmox.disk' => 'Disk space',
  'proxmox.cores' => 'Cores',
  'proxmox.cpuunits' => 'CPU',
  'proxmox.net' => 'Net',
  'proxmox.panel.problem' => 'You have a problem with the hosting ?',
  'proxmox.panel.openticket' => 'Open ticket!',
  'proxmox.network.title' => 'Network',
  'proxmox.reboot' => 'Restart',
  'proxmox.snapshots.title' => 'Snapshots',
  'proxmox.snapshots.remaining' => 'You have %remaining% allowed snapshots.',
  'proxmox.backups.success2' => 'Backup deleted.',
  'proxmox.backups.unauthorized' => 'You cannot make a backup',
  'proxmox.form.converter.title' => 'Converter',
  'proxmox.form.converter.mb' => 'Enter your number in MB',
  'proxmox.form.converter.gb' => 'Enter your number in GB',
  'proxmox.admin.title' => 'Promox Configuration',
  'proxmox.admin.subtitle' => 'Manager offers configurations.',
  'proxmox.admin.productname' => 'Product name',
  'proxmox.memory' => 'Memory',
  'proxmox.bwlimit' => 'Bandwidth',
  'proxmox.graph' => 'Graphics',
  'proxmox.unlimited' => 'Unlimited',
  'proxmox.network.type' => 'Type',
  'proxmox.network.link_down' => 'Disconnect',
  'proxmox.network.virtio' => 'Virtio',
  'proxmox.network.rate' => 'Rate',
  'proxmox.backups.success3' => 'Backup restored.',
  'proxmox.reinstall.title' => 'Reinstall',
  'proxmox.reinstall.remaining' => 'You have %remaining% allowed reinstall.',
  'proxmox.reinstall.limit' => 'You have reached the maximum number of reinstall allowed.',
  'proxmox.reinstall.success' => 'Reinstall in progress.',
  'proxmox.form.restrictions.reinstall' => 'Number of reinstall allowed',
  'proxmox.form.restrictions.nolimit' => '0 for unlimited',
  'proxmox.form.restrictions.unauthorized' => '0 to deactivate',
  'proxmox.admin.templates.subtitle' => 'Manage the Proxmox templates',
  'proxmox.admin.oses.title' => 'Oses',
  'proxmox.admin.oses.subtitle' => 'Manage the Proxmox oses',
  'proxmox.os' => 'Os',
  'proxmox.template' => 'Template',
  'proxmox.offline' => 'Offline',
  'proxmox.online' => 'Online',
  'proxmox.format' => 'Disk format',
  'proxmox.size' => 'Disk size',
  'proxmox.hostname' => 'Host',
  'proxmox.tasks' => 'Tasks',
  'proxmox.uptime' => 'Uptime',
  'proxmox.cpu' => 'CPU',
  'proxmox.button' => 'Connection',
  'proxmox.informations' => 'Information',
  'proxmox.start' => 'Start',
  'proxmox.stop' => 'Stop',
  'proxmox.shutdown' => 'Power stop',
  'proxmox.choosehostname' => 'Choose a custom hostname',
  'proxmox.network.gw' => 'Gateway',
  'proxmox.network.gw6' => 'v6 Gateway',
  'proxmox.network.ip' => 'IP Address',
  'proxmox.network.firewall' => 'Firewall',
  'proxmox.network.mtu' => 'Maximum transfer unit of the interface',
  'proxmox.network.ip6' => 'v6 IP Address',
  'proxmox.network.name' => 'Name',
  'proxmox.network.bridge' => 'Bridge',
  'proxmox.network.hwaddr' => 'Mac Address',
  'proxmox.snapshots.limit' => 'You have reached the maximum number of snapshots allowed.',
  'proxmox.snapshots.success' => 'Snapshot saved.',
  'proxmox.snapshots.success2' => 'Snapshot deleted.',
  'proxmox.snapshots.success3' => 'Snapshot rollback.',
  'proxmox.snapshots.unauthorized' => 'You cannot make a snapshot',
  'proxmox.backups.title' => 'Backups',
  'proxmox.backups.remaining' => 'You have %remaining% allowed backups.',
  'proxmox.backups.limit' => 'You have reached the maximum number of backup allowed.',
  'proxmox.backups.success' => 'Backup in progress.',
  'proxmox.config.title' => 'Proxmox',
  'proxmox.config.subtitle' => 'Configure your proxmox offer here',
  'proxmox.form.title' => 'Proxmox Configuration',
  'proxmox.form.block' => 'IP Block (ex: 123.223.134.XX/24)',
  'proxmox.form.importertitle' => 'Block Importer',
  'proxmox.form.range' => 'Range IP (Ex: 1-16)',
  'proxmox.form.btn' => 'Import easily',
  'proxmox.form.global.title' => 'Global information',
  'proxmox.form.restrictions.title' => 'Restrictions',
  'proxmox.form.restrictions.snapshot' => 'Number of snapshots allowed',
  'proxmox.form.restrictions.backup' => 'Number of backups allowed',
  'proxmox.settings.password' => 'Set random root password and send it on delivery',
  'proxmox.settings.lxcparams' => 'Add parameters on when adding networks to a CT',
  'proxmox.settings.lxcparamshelp' => 'Example : bridge=vmbr0,',
  'proxmox.settings.sshcommand' => 'Command executed when installing a VPS',
  'proxmox.settings.sshexecutehelp' => 'Variables are available. More information on our <a href="%link%">documentation</a>',
  'proxmox.settings.sshexecutehelp2' => 'If this command is empty, the configured command <a href="/admin/settings#proxmox">here</a> will be executed.',
  'proxmox.admin.ipaddress.title' => 'IP configuration',
  'proxmox.admin.ipaddress.subtitle' => 'Manage the different IP addresses.',
  'proxmox.admin.ipaddress.used' => 'Used ?',
  'proxmox.admin.templates.title' => 'Templates',
  'proxmox.admin.type' => 'Type',
  'proxmox.settings.defaultdisk' => 'Default disk to modify',
  'proxmox.settings.vpsprefix' => 'Default hostname prefix',
  'proxmox.settings.backupstorage' => 'Backup Storage Server',
];