<?php
/**$
    Pterodactyl - en_GB
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'pterodactyl.failed.pwdempty' => 'Password must not be empty.',
  'pterodactyl.failed.linkserver' => 'Failed to change password because linked server does not exist.',
  'pterodactyl.failed.retrieveuser' => 'User recovery failed, error code received : %status_code%',
  'pterodactyl.failed.changepwd' => 'Password change failed, error code received : %status_code%',
  'pterodactyl.panel.problem' => 'You have a problem with the hosting ?',
  'pterodactyl.panel.openticket' => 'Open ticket!',
  'pterodactyl.panel.information' => 'Hosting information',
  'pterodactyl.panel.start' => 'Start',
  'pterodactyl.form.resources.disk' => 'Disk space (MB)',
  'pterodactyl.form.resources.swap' => 'Swap',
  'pterodactyl.form.resources.swaphelp' => '0 will disable swap for the server. -1 will allow no throttling',
  'pterodactyl.form.resources.io' => 'Block IO',
  'pterodactyl.form.configurations.image' => 'Docker image',
  'pterodactyl.form.configurations.startup' => 'Startup command ',
  'pterodactyl.form.configurations.oomkiller' => 'Disabled OOM Killer',
  'pterodactyl.form.configurations.dedicatedip' => 'IP Address dedicatedip',
  'pterodactyl.failed.unsuspendexist' => 'Failed to unsuspend server because it does not exist.',
  'pterodactyl.failed.terminateexist' => 'Failed to delete server because it does not exist .',
  'pterodactyl.failed.satisfying' => 'Unable to find nodes meeting demand.',
  'pterodactyl.panel.disk' => 'Disk space',
  'pterodactyl.panel.memory' => 'Memory',
  'pterodactyl.panel.button' => 'Manage my server',
  'pterodactyl.config.subtitle' => 'Manage the characteristics of the offer .',
  'pterodactyl.form.resources.title' => 'Resources',
  'pterodactyl.form.resources.memory' => 'Memory (MB)',
  'pterodactyl.form.core.nest' => 'ID Nest Pterodactyl',
  'pterodactyl.form.core.location' => 'ID Location Pterodactyl',
  'pterodactyl.form.configurations.title' => 'Configuration',
  'pterodactyl.offline' => 'Offline',
  'pterodactyl.online' => 'Online',
  'pterodactyl.failed.alreadycreated' => 'Failed to create the server because it is already created.',
  'pterodactyl.failed.changepkgexist' => 'Failed to modify server package because it does not exist.',
  'pterodactyl.failed.suspendexist' => 'Failed to suspend server because it does not exist.',
  'pterodactyl.failed.createuser' => 'User creation failed, error code received : %status_code%',
  'pterodactyl.failed.geteggs' => 'Failed to get egg data, error code received : %status_code%',
  'pterodactyl.failed.getserver' => 'Failed to get data from server, error code received : %status_code%',
  'pterodactyl.failed.createserver' => 'Failed to create server, error code received : %status_code%',
  'pterodactyl.failed.suspendserver' => 'Failed to suspend server, error code received : %status_code%',
  'pterodactyl.failed.unsuspendserver' => 'Failed to unsuspend server, error code received : %status_code%',
  'pterodactyl.failed.terminateserver' => 'Failed to delete server, error code received : %status_code%',
  'pterodactyl.failed.buildserver' => 'Server version update failed, error code received : %status_code%',
  'pterodactyl.failed.startupserver' => 'Server startup update failed, error code received : %status_code%',
  'pterodactyl.panel.stop' => 'Stop',
  'pterodactyl.panel.powerstop' => 'Power stop',
  'pterodactyl.panel.restart' => 'Restart',
  'pterodactyl.adminindex.title' => 'Pterodactyl Configuration',
  'pterodactyl.adminindex.subtitle' => 'Manage the offer configurations.',
  'pterodactyl.adminindex.memory' => 'Memory',
  'pterodactyl.adminindex.disk' => 'Disk space',
  'pterodactyl.adminindex.productname' => 'Product Name',
  'pterodactyl.config.title' => 'Server configuration',
  'pterodactyl.form.resources.portrange' => 'Port to assign to the server (Example: 3000-4000)',
  'pterodactyl.form.resources.cpu' => 'CPU limit (%)',
  'pterodactyl.form.features.title' => 'Features',
  'pterodactyl.form.features.databases' => 'Databases to assign to the server',
  'pterodactyl.form.features.allocations' => 'Additional Allocations to assign to the server',
  'pterodactyl.form.features.backups' => 'Saves to assign to the server',
  'pterodactyl.form.core.title' => 'Information',
  'pterodactyl.form.core.servername' => 'Serveur name',
  'pterodactyl.form.core.egg' => 'ID Egg Pterodactyl',
];