<?php
/**$
    Pterobox - en_GB
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'pterobox.cannot.core' => 'You cannot exceed %limit% CPU VCores.',
  'pterobox.cannot.empty' => 'You cannot put an empty value or 0.',
  'pterobox.panel.disk' => 'Disk Space',
  'pterobox.config.subtitle' => 'Manage the different features of the offer.',
  'pterobox.form.resources.title' => 'Resources',
  'pterobox.form.resources.servers' => 'Number of servers that can be created',
  'pterobox.form.resources.cores' => 'CPU usage (%)',
  'pterobox.form.features.allocations' => 'Allocations',
  'pterobox.form.features.backups' => 'Backups',
  'pterobox.form.features.servers' => 'Servers',
  'pterobox.form.features.cores' => 'CPU cores',
  'pterobox.form.core.title' => 'Information',
  'pterobox.form.core.egg' => 'Pterodactyl Egg ID',
  'pterobox.cannot.database' => 'You cannot exceed %limit% databases.',
  'pterobox.cannot.backup' => 'You cannot exceed %limit% backups.',
  'pterobox.cannot.allocation' => 'You cannot exceed %limit% allocations.',
  'pterobox.cannot.server' => 'You cannot exceed %limit% servers.',
  'pterobox.adminindex.disk' => 'Disk Space',
  'pterobox.adminindex.productname' => 'Product Name',
  'pterobox.config.title' => 'Server Configuration',
  'pterobox.form.features.databases' => 'Databases',
  'pterobox.createserver' => 'Create Server',
  'pterobox.updateserver' => 'Edit Server',
  'pterobox.button' => 'Modify',
  'pterobox.servername' => 'Server Name',
  'pterobox.used' => 'used',
  'pterobox.used2' => 'used',
  'pterobox.cannot.memory' => 'You cannot exceed %limit% GB of memory.',
  'pterobox.cannot.disk' => 'You cannot exceed %limit% GB of disk space.',
  'pterobox.panel.memory' => 'Memory',
  'pterobox.panel.button' => 'Manage my server',
  'pterobox.panel.problem' => 'Experiencing an issue with your hosting?',
  'pterobox.panel.openticket' => 'Open a ticket!',
  'pterobox.panel.information' => 'Hosting Information',
  'pterobox.panel.backupswisp' => 'Backup Limit Size',
  'pterobox.panel.backupswisphelp' => 'The total number of Gigabyte that the server can use for its backups.',
  'pterobox.adminindex.title' => 'Pterobox Configuration',
  'pterobox.adminindex.subtitle' => 'Manage your offer configurations.',
  'pterobox.adminindex.memory' => 'Memory',
  'pterobox.form.resources.memory' => 'Memory (GB)',
  'pterobox.form.resources.disk' => 'Disk Space (GB)',
  'pterobox.form.resources.help' => 'Available for the entire box',
  'pterobox.form.resources.portrange' => 'Port to assign to the server (Example: 3000-4000)',
  'pterobox.form.resources.cpu' => 'CPU Limit (%)',
  'pterobox.form.resources.swap' => 'Swap',
  'pterobox.form.resources.swaphelp' => '0 will disable swap for the server. -1 will allow unlimited',
  'pterobox.form.resources.io' => 'IO Block',
  'pterobox.form.features.title' => 'Features',
  'pterobox.form.core.nest' => 'Pterodactyl Nest ID',
  'pterobox.form.core.location' => 'Pterodactyl Location ID',
];