<?php
/**$
    SEO - en_GB
    CLIENTXCMS Translator system - Exported on 2023-09-10 14:40:46
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'seo.admin.title' => 'SEO',
  'seo.admin.subtitle' => 'Manage your system\'s SEO',
  'seo.admin.content' => 'Tag in the head tag',
  'seo.admin.example' => 'Variables : %url%, %app_name%, %theme_primary%',
  'seo.admin.urlmatch' => 'URL where tags will be added',
  'seo.admin.help' => '"*" To display on all pages',
  'seo.admin.generated' => 'Sitemap generated by CLIENTXCMS',
  'seo.admin.modifiable' => 'Modified sitemap',
];