<?php
/**$
    Support - en_GB
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'department' => 'Department',
  'support.related' => 'Service/Transaction related',
  'support.admin.department.title' => 'Department',
  'support.admin.department.subtitle' => 'Manage the different support departments.',
  'support.show.our_reply' => 'Our reply',
  'support.show.your_reply' => 'Your reply',
  'support.priority' => 'Priority',
  'support.priorities.High' => 'High',
  'support.priorities.Medium' => 'Medium',
  'support.priorities.Low' => 'Low',
  'departments' => 'Departments',
  'your_tickets' => 'Yours tickets',
  'new_ticket' => 'New ticket',
  'reply' => 'Reply',
  'open_tickets' => 'Open tickets ',
  'predefinedreplies' => 'Predefined Replies',
  'predefinedreply' => 'Predefined Reply',
  'support.actions.close' => 'The ticket has just been closed.',
  'support.actions.reply' => 'The answer has just been posted.',
  'support.table.last_updated' => 'Last update',
  'support.table.close' => 'Close',
  'support.table.priority' => 'Priority',
  'support.table.department' => 'Department',
  'support.table.subject' => 'Subject',
  'support.admin.ticket.createsubtitle' => 'Open a ticket for a specific customer.',
  'support.email.title' => 'Response from our support for the %subject% ticket',
  'support.email.content' => 'Our support has just responded to your ticket for help. You can consult it by clicking on the button above.',
  'support.email.button' => 'My ticket',
  'support.show.reopentext' => 'Your ticket is currently closed, you can reopen it by clicking on the button.',
  'support.show.reopen' => 'Reopen the ticket',
  'support.show.your_question' => 'Your question',
  'support.department' => 'Department',
  'support.discussion' => 'Discussion',
  'support.content' => 'Content',
  'support.newticket' => 'New ticket',
  'support.submit' => 'Submit',
  'tickets' => 'Tickets',
  'support.title' => 'Technical support ',
  'support.messages' => 'Messages',
  'support.replied' => 'Answered you ',
  'support.icon' => 'Icon',
  'support.informations' => 'Information',
  'support.actions.reopen' => 'The ticket has just been reopened.',
  'support.actions.submit' => 'The ticket has just been opened.',
  'support.admin.predefined.title' => 'Predefined Replies',
  'support.admin.predefined.create' => 'You can create predefined replies <a href="%route%" target="_blank">here</a>',
  'support.admin.predefined.subtitle' => 'Manage the different support predefined replies.',
  'support.admin.predefined.global' => 'The answer may be available to all staff',
  'support.admin.predefined.tips' => '<strong>[LASTNAME]</strong> - Ticket Submitter Name | <strong>[FIRSTNAME]</strong> - First Name | <strong>[EMAIL]</strong> - Ticket Submitter Email | <strong>[RELATED]</strong> transaction/service related name (if defined)',
  'support.admin.ticket.title' => 'Support',
  'support.admin.ticket.subtitle' => 'Manage the different support tickets.',
  'support.show.reply' => 'Reply',
  'support.show.textarea' => 'Please detail your problem as much as possible. 
 Do not give any confidential information (passwords, ...), our technicians have all the information necessary to solve your problem ',
  'support.states.Pending' => 'Pending',
  'support.states.Reply Support' => 'Support reply ',
  'support.states.Reply Customer' => 'Customer Reply',
  'support.states.Closed' => 'Closed',
  'support.print' => 'Print',
  'support.admin' => 'Staff to be notified by email',
  'servicespage.options.manage' => 'Need an additional IP or more disk space?',
];