<?php
/**$
    translator - en_GB
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'translatesitems.positive' => 'The value must be positive.',
  'translatesitems.numeric' => 'The value must be a valid numeric.',
  'translatesitems.between' => 'The value must be between %d and %d.',
  'translatesitems.inArray' => 'The value does not exist in these values: %s',
  'translatesitems.notInArray' => 'The value must not exist in these values: %s',
  'translatesitems.arrayHasKey' => 'The table must contain the key %s',
  'translatesitems.unique' => 'The value must be unique in the database',
  'translatesitems.arrayHasNotKey' => 'The table must not contain the key %s',
  'translatesitems.filetype' => 'The field is not a valid format (%s)',
  'translatesitems.maxLength' => 'The value must contain less than %d characters.',
  'translatesitems.betweenLength' => 'The value must contain between %d and %d characters.',
  'translatesitems.bannedEmail' => 'The email address or domain name is banned.',
  'translatesitems.email' => 'The value must be a valid email.',
  'translatesitems.invalidip' => 'The value must be a valid IP address.',
  'translatesitems.url' => 'The value must be a valid url.',
  'translatesitems.domain' => 'The value must be a valid domain.',
  'translatesitems.equals' => 'The value must be the same as confirmation.',
  'translatesitems.ispassword' => 'The password must be the current one.',
  'translatesitems.isfuture' => 'The date must be in the future.',
  'translatesitems.startswith' => 'The value must start with %s.',
  'translatesitems.endswith' => 'The value must end in %s.',
  'translatesitems.contains' => 'The value must contain %s',
  'translatesitems.notcontains' => 'The value must not contain %s',
  'translatesitems.passwordsecurity' => 'Your password is not secure! Please use another one',
  'translatesitems.sshpublic' => 'The SSH key must be a valid key',
  'translatesitems.boolean' => 'The value must be a valid boolean.',
  'translatesitems.int' => 'The value must be a valid number.',
  'translatesitems.negative' => 'The value must be negative.',
  'translatesitems.max' => 'The number must be less than %d',
  'translatesitems.min' => 'The number must be at least %d',
  'translatesitems.minLength' => 'The value must contain more than %d characters.',
  'translatesitems.license' => 'This license is invalid %s',
  'translatesitems.exists' => 'The value must exist in the database.',
  'translatesitems.ispast' => 'The date must be in the past.',
  'translatesitems.true' => 'The value must be true.',
  'translatesitems.false' => 'The value must be false.',
  'translatesitems.uploaded' => 'You must upload a file.',
  'translatesitems.required' => 'The value must be required.',
  'translatesitems.empty' => 'The value cannot be empty.',
  'translatesitems.slug' => 'The value must be a valid slug.',
  'translatesitems.phonenumber' => 'The value must be a valid phone number.',
  'translatesitems.postcode' => 'The value must be a valid postal code (%s).',
  'translatesitems.numericOrZero' => 'The value must be a valid numeric or equal to zero.',
  'translatesitems.positiveOrZero' => 'The value must be positive or equal to zero.',
  'translatesitems.ostemplate' => 'You must choose between a template or an OS.',
];