<?php
/**$
    translator - en_GB
    CLIENTXCMS Translator system - Exported on 2023-07-26 13:50:50
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'translatesitems' => [
    'true' => 'The value must be true.',
    'false' => 'The value must be false.',
    'boolean' => 'The value must be a valid boolean.',
    'int' => 'The value must be a valid number.',
    'negative' => 'The value must be negative.',
    'positive' => 'The value must be positive.',
    'numeric' => 'The value must be a valid numeric.',
    'between' => 'The value must be between %d and %d.',
    'inArray' => 'The value does not exist in these values: %s',
    'notInArray' => 'The value must not exist in these values: %s',
    'arrayHasKey' => 'The table must contain the key %s',
    'unique' => 'The value must be unique in the database',
    'arrayHasNotKey' => 'The table must not contain the key %s',
    'filetype' => 'The field is not a valid format (%s)',
    'uploaded' => 'You must upload a file.',
    'required' => 'The value must be required.',
    'empty' => 'The value cannot be empty.',
    'slug' => 'The value must be a valid slug.',
    'max' => 'The number must be less than %d',
    'min' => 'The number must be at least %d',
    'minLength' => 'The value must contain more than %d characters.',
    'maxLength' => 'The value must contain less than %d characters.',
    'betweenLength' => 'The value must contain between %d and %d characters.',
    'bannedEmail' => 'The email address or domain name is banned.',
    'email' => 'The value must be a valid email.',
    'invalidip' => 'The value must be a valid IP address.',
    'url' => 'The value must be a valid url.',
    'domain' => 'The value must be a valid domain.',
    'equals' => 'The value must be the same as confirmation.',
    'ispassword' => 'The password must be the current one.',
    'phonenumber' => 'The value must be a valid phone number.',
    'postcode' => 'The value must be a valid postal code (%s).',
    'numericOrZero' => 'The value must be a valid numeric or equal to zero.',
    'positiveOrZero' => 'The value must be positive or equal to zero.',
    'license' => 'This license is invalid %s',
    'exists' => 'The value must exist in the database.',
    'ispast' => 'The date must be in the past.',
    'isfuture' => 'The date must be in the future.',
    'startswith' => 'The value must start with %s.',
    'endswith' => 'The value must end in %s.',
    'contains' => 'The value must contain %s',
    'notcontains' => 'The value must not contain %s',
    'passwordsecurity' => 'Your password is not secure! Please use another one',
    'sshpublic' => 'The SSH key must be a valid key',
    'ostemplate' => 'You must choose between a template or an OS.',
  ],
];