<?php
/**$
    VirtualizorCloud - en_GB
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'virtualizorcloud.offline' => 'Offline',
  'virtualizorcloud.online' => 'Online',
  'virtualizorcloud.planname' => 'Plan name',
  'virtualizorcloud.graph' => 'Graphic',
  'virtualizorcloud.panel.disk' => 'Disk space',
  'virtualizorcloud.panel.cores' => 'Cores',
  'virtualizorcloud.panel.in' => 'In',
  'virtualizorcloud.panel.out' => 'Out',
  'virtualizorcloud.form.resources.priority' => 'I/O Priority (OpenVZ)',
  'virtualizorcloud.form.resources.vnc' => 'VNC Enabled (KVM)',
  'virtualizorcloud.form.resources.speed' => 'Network speed in KB/s (KB/s zero or empty for unlimited)',
  'virtualizorcloud.form.resources.server' => 'Server',
  'virtualizorcloud.form.stockage.space' => 'Space disk (GB)',
  'virtualizorcloud.form.cpu.cores' => 'Cores',
  'virtualizorcloud.form.cpu.units' => 'Units',
  'virtualizorcloud.form.cpu.cpu' => 'CPU in %',
  'virtualizorcloud.form.ips.internalips' => 'Number of Internal IP Address',
  'virtualizorcloud.form.ips.ips' => 'Number of IPs',
  'virtualizorcloud.admin.title' => 'Virtualizor Configuration',
  'virtualizorcloud.admin.subtitle' => 'Manage the offer configurations.',
  'virtualizorcloud.admin.planname' => 'Plan name',
  'virtualizorcloud.config.title' => 'Virtual Server configuration',
  'virtualizorcloud.hostname' => 'Host',
  'virtualizorcloud.os' => 'OS',
  'virtualizorcloud.panel.restart' => 'Restart',
  'virtualizorcloud.panel.os_name' => 'Os',
  'virtualizorcloud.panel.bandwidth' => 'Bandwidth',
  'virtualizorcloud.panel.ram' => 'RAM',
  'virtualizorcloud.panel.virt' => 'Virtualization',
  'virtualizorcloud.panel.cpu' => 'CPU',
  'virtualizorcloud.panel.reset' => 'Reset',
  'virtualizorcloud.form.resources.title' => 'Resources',
  'virtualizorcloud.form.resources.disk' => 'Disk space (GB)',
  'virtualizorcloud.form.resources.io' => 'Block IO',
  'virtualizorcloud.form.resources.bandwidth' => 'Bandwidth (GB Zero or empty for unlimited)',
  'virtualizorcloud.form.resources.inodes' => 'INode (OpenVZ)',
  'virtualizorcloud.form.resources.network_speed' => 'Network speed in MB/s',
  'virtualizorcloud.form.resources.upload_speed' => 'Upload Speed in MB/s',
  'virtualizorcloud.form.stockage.title' => 'STORAGE Section',
  'virtualizorcloud.form.stockage.ram' => 'RAM MB (KVM, LXC)',
  'virtualizorcloud.form.stockage.guaranteed' => 'Guaranteed Ram (MB)',
  'virtualizorcloud.form.stockage.burstable' => 'Burstable Ram (OpenVZ)',
  'virtualizorcloud.form.configurations.group' => 'Group',
  'virtualizorcloud.form.configurations.vnc' => 'VNC',
  'virtualizorcloud.form.ips.ip6subnet' => 'Number of IPv6 Address',
  'virtualizorcloud.form.ips.ip6' => 'Number of IPv6 Subnets',
  'virtualizorcloud.productname' => 'Product name',
  'virtualizorcloud.choosehostname' => 'Choose a custom hostname',
  'virtualizorcloud.panel.button' => 'Login',
  'virtualizorcloud.panel.start' => 'Start',
  'virtualizorcloud.panel.stop' => 'Stop',
  'virtualizorcloud.panel.powerstop' => 'Power stop',
  'virtualizorcloud.panel.usage' => 'Usage',
  'virtualizorcloud.panel.site' => 'Open the site',
  'virtualizorcloud.panel.information' => 'Hosting information',
  'virtualizorcloud.panel.problem' => 'You have a problem with the hosting ?',
  'virtualizorcloud.panel.openticket' => 'Open ticket!',
  'virtualizorcloud.panel.uptime' => 'Uptime',
  'virtualizorcloud.form.resources.ip6' => 'IPv6',
  'virtualizorcloud.form.resources.ip6subnet' => 'Ip6subnet',
  'virtualizorcloud.form.resources.ips' => 'Ips',
  'virtualizorcloud.form.resources.oses' => 'Os available (separated by commas)',
  'virtualizorcloud.form.resources.internalips' => 'Internal IP',
  'virtualizorcloud.form.resources.portrange' => 'Port to assign to the server (separated by commas)',
  'virtualizorcloud.form.cpu.title' => 'CPU Section',
  'virtualizorcloud.form.converter.title' => 'Converter',
  'virtualizorcloud.form.converter.mb' => 'Enter your number in MB',
  'virtualizorcloud.form.converter.gb' => 'Enter your number in GB',
  'virtualizorcloud.form.configurations.title' => 'Configurations',
  'virtualizorcloud.form.configurations.server' => 'Server',
  'virtualizorcloud.config.subtitle' => 'Manage the characteristics of the offer.',
  'virtualizorcloud.converter.title' => 'Converter',
  'virtualizorcloud.converter.mb' => 'Enter your number in MB',
  'virtualizorcloud.converter.gb' => 'Enter your number in GB',
];