<?php
/**$
    Virtualizor - en_GB
    CLIENTXCMS Translator system - Exported on 2023-11-12 18:56:14
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'virtualizor.panel.stop' => 'Stop',
  'virtualizor.panel.powerstop' => 'Power stop',
  'virtualizor.panel.restart' => 'Restart',
  'virtualizor.panel.os_name' => 'Os',
  'virtualizor.panel.openticket' => 'Open ticket!',
  'virtualizor.panel.uptime' => 'Uptime',
  'virtualizor.panel.reset' => 'Reset',
  'virtualizor.admin.title' => 'Virtualizor Configuration',
  'virtualizor.productname' => 'Product name',
  'virtualizor.graph' => 'Graphic',
  'virtualizor.panel.button' => 'Login',
  'virtualizor.panel.start' => 'Start',
  'virtualizor.panel.in' => 'In',
  'virtualizor.panel.out' => 'Out',
  'virtualizor.panel.usage' => 'Usage',
  'virtualizor.panel.site' => 'Open the site',
  'virtualizor.panel.information' => 'Hosting information',
  'virtualizor.panel.problem' => 'You have a problem with the hosting ?',
  'virtualizor.converter.gb' => 'Enter your number in GB',
  'kvm' => 'KVM',
  'openvz' => 'OpenVZ',
  'lxc' => 'LXC',
  'virtualizor.hostname' => 'Host',
  'virtualizor.os' => 'OS',
  'virtualizor.offline' => 'Offline',
  'virtualizor.online' => 'Online',
  'virtualizor.planname' => 'Plan name',
  'virtualizor.panel.bandwidth' => 'Bandwidth',
  'virtualizor.panel.ram' => 'RAM',
  'virtualizor.panel.virt' => 'Virtualization',
  'virtualizor.panel.cpu' => 'CPU',
  'virtualizor.panel.disk' => 'Disk space',
  'virtualizor.panel.cores' => 'Cores',
  'virtualizor.admin.subtitle' => 'Manage the offer configurations.',
  'virtualizor.admin.planname' => 'Plan name',
  'virtualizor.config.title' => 'Virtual Server configuration',
  'virtualizor.config.subtitle' => 'Manage the characteristics of the offer.',
  'virtualizor.converter.title' => 'Converter',
  'virtualizor.converter.mb' => 'Enter your number in MB',
  'virtualizor.choosehostname' => 'Choose a custom hostname',
];