<?php
/**$
    VirtualizorCloud - en_GB
    CLIENTXCMS Translator system - Exported on 2023-07-26 10:57:47
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'kvm' => 'KVM',
  'openvz' => 'OpenVZ',
  'lxc' => 'LXC',
  'virtualizorcloud' => [
    'hostname' => 'Host',
    'os' => 'OS',
    'offline' => 'Offline',
    'online' => 'Online',
    'planname' => 'Plan name',
    'productname' => 'Product name',
    'choosehostname' => 'Choose a custom hostname',
    'graph' => 'Graphic',
    'panel' => [
      'button' => 'Login',
      'start' => 'Start',
      'stop' => 'Stop',
      'powerstop' => 'Power stop',
      'restart' => 'Restart',
      'os_name' => 'Os',
      'bandwidth' => 'Bandwidth',
      'ram' => 'RAM',
      'virt' => 'Virtualization',
      'cpu' => 'CPU',
      'disk' => 'Disk space',
      'cores' => 'Cores',
      'in' => 'In',
      'out' => 'Out',
      'usage' => 'Usage',
      'site' => 'Open the site',
      'information' => 'Hosting information',
      'problem' => 'You have a problem with the hosting ?',
      'openticket' => 'Open ticket!',
      'uptime' => 'Uptime',
      'reset' => 'Reset',
    ],
    'form' => [
      'resources' => [
        'title' => 'Resources',
        'disk' => 'Disk space (GB)',
        'io' => 'Block IO',
        'bandwidth' => 'Bandwidth (GB Zero or empty for unlimited)',
        'inodes' => 'INode (OpenVZ)',
        'priority' => 'I/O Priority (OpenVZ)',
        'vnc' => 'VNC Enabled (KVM)',
        'speed' => 'Network speed in KB/s (KB/s zero or empty for unlimited)',
        'server' => 'Server',
        'ip6' => 'IPv6',
        'ip6subnet' => 'Ip6subnet',
        'ips' => 'Ips',
        'oses' => 'Os available (separated by commas)',
        'internalips' => 'Internal IP',
        'portrange' => 'Port to assign to the server (separated by commas)',
        'network_speed' => 'Network speed in MB/s',
        'upload_speed' => 'Upload Speed in MB/s',
      ],
      'stockage' => [
        'title' => 'STORAGE Section',
        'ram' => 'RAM MB (KVM, LXC)',
        'guaranteed' => 'Guaranteed Ram (MB)',
        'burstable' => 'Burstable Ram (OpenVZ)',
        'space' => 'Space disk (GB)',
      ],
      'cpu' => [
        'cores' => 'Cores',
        'units' => 'Units',
        'cpu' => 'CPU in %',
        'title' => 'CPU Section',
      ],
      'converter' => [
        'title' => 'Converter',
        'mb' => 'Enter your number in MB',
        'gb' => 'Enter your number in GB',
      ],
      'configurations' => [
        'title' => 'Configurations',
        'server' => 'Server',
        'group' => 'Group',
        'vnc' => 'VNC',
      ],
      'ips' => [
        'ip6subnet' => 'Number of IPv6 Address',
        'ip6' => 'Number of IPv6 Subnets',
        'internalips' => 'Number of Internal IP Address',
        'ips' => 'Number of IPs',
      ],
    ],
    'admin' => [
      'title' => 'Virtualizor Configuration',
      'subtitle' => 'Manage the offer configurations.',
      'planname' => 'Plan name',
    ],
    'config' => [
      'title' => 'Virtual Server configuration',
      'subtitle' => 'Manage the characteristics of the offer.',
    ],
    'converter' => [
      'title' => 'Converter',
      'mb' => 'Enter your number in MB',
      'gb' => 'Enter your number in GB',
    ],
  ],
];