<?php
/**$
    Wisp - en_GB
    CLIENTXCMS Translator system - Exported on 2023-08-19 13:28:38
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'Wisp.failed.linkserver' => 'Failed to change password because linked server does not exist.',
  'Wisp.failed.retrieveuser' => 'User recovery failed, error code received : %status_code%',
  'Wisp.failed.changepwd' => 'Password change failed, error code received : %status_code%',
  'Wisp.panel.openticket' => 'Open ticket!',
  'Wisp.panel.information' => 'Hosting information',
  'Wisp.panel.start' => 'Start',
  'Wisp.form.resources.title' => 'Resources',
  'Wisp.form.resources.memory' => 'Memory (MB)',
  'Wisp.form.resources.disk' => 'Disk space (MB)',
  'Wisp.form.configurations.title' => 'Configuration',
  'Wisp.form.configurations.image' => 'Docker image',
  'Wisp.form.configurations.startup' => 'Startup command ',
  'Wisp.failed.alreadycreated' => 'Failed to create the server because it is already created.',
  'Wisp.failed.changepkgexist' => 'Failed to modify server package because it does not exist.',
  'Wisp.failed.suspendexist' => 'Failed to suspend server because it does not exist.',
  'Wisp.failed.unsuspendexist' => 'Failed to unsuspend server because it does not exist.',
  'Wisp.failed.terminateexist' => 'Failed to delete server because it does not exist .',
  'Wisp.failed.satisfying' => 'Unable to find nodes meeting demand.',
  'Wisp.failed.pwdempty' => 'Password must not be empty.',
  'Wisp.failed.suspendserver' => 'Failed to suspend server, error code received : %status_code%',
  'Wisp.failed.unsuspendserver' => 'Failed to unsuspend server, error code received : %status_code%',
  'Wisp.failed.terminateserver' => 'Failed to delete server, error code received : %status_code%',
  'Wisp.failed.buildserver' => 'Server version update failed, error code received : %status_code%',
  'Wisp.failed.startupserver' => 'Server startup update failed, error code received : %status_code%',
  'Wisp.panel.disk' => 'Disk space',
  'Wisp.panel.memory' => 'Memory',
  'Wisp.panel.button' => 'Manage my server',
  'Wisp.panel.problem' => 'You have a problem with the hosting ?',
  'Wisp.adminindex.subtitle' => 'Manage the configurations of your offers.',
  'Wisp.adminindex.memory' => 'Memory',
  'Wisp.adminindex.disk' => 'Disk space',
  'Wisp.adminindex.productname' => 'Product Name',
  'Wisp.migrate.title' => 'Wisp Migration',
  'Wisp.migrate.subtitle' => 'This page lets you migrate your Pterodactyl configurations to Wisp.',
  'Wisp.migrate.info' => 'This action will change product types and migrate configurations from the Pterodactyl module to the Wisp module.',
  'Wisp.config.title' => 'Server configuration',
  'Wisp.config.subtitle' => 'Manage the different features of the offer',
  'Wisp.form.features.title' => 'Features',
  'Wisp.form.features.databases' => 'Databases to assign to the server ',
  'Wisp.form.features.backups' => 'Backup size limit (MB)',
  'Wisp.form.features.allocations' => 'Allocation (MB)',
  'Wisp.form.core.title' => 'Information',
  'Wisp.form.core.servername' => 'Serveur name',
  'Wisp.form.core.egg' => 'ID Egg Wisp',
  'Wisp.form.core.nest' => 'ID Nest Wisp',
  'Wisp.form.core.location' => 'ID Location Wisp',
  'Wisp.form.converter.gb' => 'Type your number in GB',
  'Wisp.offline' => 'Offline',
  'Wisp.online' => 'Online',
  'Wisp.failed.createuser' => 'User creation failed, error code received : %status_code%',
  'Wisp.failed.geteggs' => 'Failed to get egg data, error code received : %status_code%',
  'Wisp.failed.getserver' => 'Failed to get data from server, error code received : %status_code%',
  'Wisp.failed.createserver' => 'Failed to create server, error code received : %status_code%',
  'Wisp.panel.stop' => 'Stop',
  'Wisp.panel.powerstop' => 'Power stop',
  'Wisp.panel.restart' => 'Restart',
  'Wisp.adminindex.title' => 'Wisp Configuration',
  'Wisp.form.resources.swap' => 'Swap',
  'Wisp.form.resources.io' => 'Block IO',
  'Wisp.form.resources.portrange' => 'Port to assign to the server (separated by commas)',
  'Wisp.form.resources.cpu' => 'CPU limit (%)',
  'Wisp.form.configurations.oomkiller' => 'Disabled OOM Killer',
  'Wisp.form.configurations.dedicatedip' => 'Addresse IP dedicatedip',
  'Wisp.form.converter.title' => 'Converter',
  'Wisp.form.converter.mb' => 'Type your number in MB',
];