<?php
/**$
    License - it_IT
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:39:55
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'your_licenses' => 'Le tue licenze',
  'max_domains' => 'No. Domini consentiti',
  'max_customers' => 'N. Clienti autorizzati',
  'your_domains' => 'I tuoi domini autorizzati',
  'serverstatus' => 'Stato del server',
  'add2' => 'Aggiungere',
  'upgradenow' => 'Aggiorna subito la tua licenza',
  'upgradedays' => '%giorni% giorni offerti',
  'reset2' => 'Resettare',
  'automaticrenewal' => 'Rinnovo automatico',
  'manualrenewal' => 'Rinnovo manuale',
  'licenseexpired' => 'Attenzione: la tua licenza è scaduta per continuare a utilizzare CLIENTXCMS, rinnova la tua chiave di licenza.',
  'ordernow' => 'Ordina ora',
  'ordernow2' => 'Ordina la tua licenza CLIENTXCMS a partire da € 9,99 /mese',
  'checkoutpage.modules.modulechoose2' => 'È possibile scegliere i componenti aggiuntivi <b>di conteggio</b> per l\'offerta',
  'checkoutpage.modules.primarymodule' => 'Primo modulo',
  'checkoutpage.modules.secondarymodule' => 'Secondo Modulo',
  'checkoutpage.modules.tertiarymodule' => 'Terzo Modulo',
  'checkoutpage.modules.canchangemodule' => 'Potrai cambiare i tuoi moduli al prossimo rinnovo',
  'checkoutpage.modules.canchange' => 'Potrai comunque modificare questo dominio dopo l\'acquisto',
  'checkoutpage.modules.canchange2' => 'Sarai comunque in grado di modificare questo dominio dopo il rinnovo',
  'checkoutpage.modules.modulechoose3' => 'I moduli acquistati con la licenza sono a vita',
  'checkoutpage.modules.modulechoose' => 'Scegli un componente aggiuntivo',
  'checkoutpage.installation.title' => 'Installazione',
  'checkoutpage.installation.subtitle' => 'Il nostro team creerà la tua area clienti per te non appena riceverai il tuo ordine.',
  'licensechecker' => 'Verifica della licenza',
  'licencepage.reset' => 'Le chiavi di licenza vengono reimpostate correttamente.',
  'licencepage.reinstall' => 'I token vengono reimpostati correttamente',
  'licencepage.save' => 'Informazioni modificate con successo.',
  'reinstall' => 'Reinstallare',
  'onetimemodule' => 'Modulo a vita',
  'downloadablefromadmin' => 'Modulo scaricabile dalla tua area di amministrazione.',
  'experimental.title' => 'Modalità sperimentale',
  'experimental.help' => 'La modalità sperimentale consente di avere funzionalità in anticipo ma può causare bug, da usare con cautela.',
  'downloadmodal.title' => 'Il download è pronto nella versione %version%',
  'downloadmodal.description' => 'Se reinstallato, il token deve essere reimpostato.',
  'downloadmodal.button1' => 'Scarica l\'archivio',
  'downloadmodal.button2' => 'Ripristina token',
  'downloadmodal.button3' => 'Reimposta chiave di licenza',
  'renewlicense' => 'Rinnova licenza',
  'renewmodule' => 'Rinnova modulo',
];