<?php
/**$
    Proxmox - it_IT
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:39:44
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'proxmox.console' => 'Confortare',
  'proxmox.disk' => 'Spazio su disco',
  'proxmox.cores' => 'Cuori',
  'proxmox.cpuunits' => 'CPU',
  'proxmox.net' => 'Rete',
  'proxmox.panel.problem' => 'Hai un problema con l\'hosting?',
  'proxmox.panel.openticket' => 'Apri un ticket!',
  'proxmox.network.title' => 'Rete',
  'proxmox.reboot' => 'Riavviare',
  'proxmox.snapshots.title' => 'Istantanee',
  'proxmox.snapshots.remaining' => 'Rimangono %istantanee rimanenti% consentite.',
  'proxmox.backups.success2' => 'Backup eliminato.',
  'proxmox.backups.unauthorized' => 'Non è possibile eseguire un backup.',
  'proxmox.form.converter.title' => 'Convertitore',
  'proxmox.form.converter.mb' => 'Digita il tuo numero in MB',
  'proxmox.form.converter.gb' => 'Digita il tuo numero in GB',
  'proxmox.admin.title' => 'Configurazione di Proxmox',
  'proxmox.admin.subtitle' => 'Gestire le configurazioni dell\'offerta.',
  'proxmox.admin.productname' => 'Nome del prodotto',
  'proxmox.memory' => 'Memoria',
  'proxmox.bwlimit' => 'Larghezza di banda',
  'proxmox.graph' => 'Grafica',
  'proxmox.unlimited' => 'Illimitato',
  'proxmox.network.type' => 'Digitare',
  'proxmox.network.link_down' => 'Disconnettere',
  'proxmox.network.virtio' => 'Virtio',
  'proxmox.network.rate' => 'Milza',
  'proxmox.backups.success3' => 'Backup ripristinato.',
  'proxmox.reinstall.title' => 'Reinstallazione',
  'proxmox.reinstall.remaining' => 'Rimangono %rimanenti% installazioni autorizzate.',
  'proxmox.reinstall.limit' => 'È stato raggiunto il numero massimo di disinstallazioni consentite.',
  'proxmox.reinstall.success' => 'Installazione.',
  'proxmox.form.restrictions.reinstall' => 'Numero di ricollocazioni autorizzate',
  'proxmox.form.restrictions.nolimit' => '0 per illimitato',
  'proxmox.form.restrictions.unauthorized' => '0 per disabilitare',
  'proxmox.admin.templates.subtitle' => 'Amministrare i diversi modelli Proxmox',
  'proxmox.admin.oses.title' => 'Osare',
  'proxmox.admin.oses.subtitle' => 'Gestisci i diversi sistemi operativi Proxmox',
  'proxmox.os' => 'OSSO',
  'proxmox.template' => 'Modello di sistema operativo',
  'proxmox.offline' => 'estinto',
  'proxmox.online' => 'Illuminato',
  'proxmox.format' => 'Formato disco',
  'proxmox.size' => 'Dimensione del disco',
  'proxmox.hostname' => 'Ospite',
  'proxmox.tasks' => 'Punti',
  'proxmox.uptime' => 'Disponibilità',
  'proxmox.cpu' => 'CPU',
  'proxmox.button' => 'Connessione',
  'proxmox.informations' => 'Informazione',
  'proxmox.start' => 'Inizio',
  'proxmox.stop' => 'Per disattivare',
  'proxmox.shutdown' => 'Uccidere',
  'proxmox.choosehostname' => 'Scegliere un nome host personalizzato',
  'proxmox.network.gw' => 'Gateway',
  'proxmox.network.gw6' => 'Gateway v6',
  'proxmox.network.ip' => 'Indirizzo IP',
  'proxmox.network.firewall' => 'Antifuoco',
  'proxmox.network.mtu' => 'Trasferimento massimo dell\'interfaccia',
  'proxmox.network.ip6' => 'Indirizzo IP v6',
  'proxmox.network.name' => 'Nome',
  'proxmox.network.bridge' => 'Ponte',
  'proxmox.network.hwaddr' => 'Indirizzo MAC',
  'proxmox.snapshots.limit' => 'È stato raggiunto il numero massimo di istantanee consentite.',
  'proxmox.snapshots.success' => 'Istantanea salvata.',
  'proxmox.snapshots.success2' => 'Snapshot eliminato.',
  'proxmox.snapshots.success3' => 'Istantanea ripristinata.',
  'proxmox.snapshots.unauthorized' => 'Non è possibile scattare un\'istantanea.',
  'proxmox.backups.title' => 'Backup',
  'proxmox.backups.remaining' => 'Rimane %remaining% backup(s) consentito.',
  'proxmox.backups.limit' => 'È stato raggiunto il numero massimo di backup consentiti.',
  'proxmox.backups.success' => 'Backup salvato.',
  'proxmox.config.title' => 'Proxmox',
  'proxmox.config.subtitle' => 'Amministrare le funzionalità dell\'offerta.',
  'proxmox.form.title' => 'Configurazione proxmox',
  'proxmox.form.block' => 'Blocco IP (ad es. 123.223.134.XX / 24)',
  'proxmox.form.importertitle' => 'Importatore di blocchi IP',
  'proxmox.form.range' => 'Intervallo IP (Es: 1-16)',
  'proxmox.form.btn' => 'Importazione rapida',
  'proxmox.form.global.title' => 'Generalità',
  'proxmox.form.restrictions.title' => 'Restrizione',
  'proxmox.form.restrictions.snapshot' => 'Numero di istantanee consentite',
  'proxmox.form.restrictions.backup' => 'Numero di backup consentiti',
  'proxmox.settings.password' => 'Imposta una password di root casuale e inviala via e-mail al momento della consegna',
  'proxmox.settings.lxcparams' => 'Aggiunta di parametri durante l\'aggiunta della rete',
  'proxmox.settings.lxcparamshelp' => 'Esempio: bridge=vmbr0,',
  'proxmox.settings.sshcommand' => 'Comando eseguito durante l\'installazione di un VPS',
  'proxmox.settings.sshexecutehelp' => 'Sono disponibili delle variabili. Maggiori informazioni sulla nostra <a href="%link%">documentation</a>',
  'proxmox.settings.sshexecutehelp2' => 'Se questo comando è vuoto, verrà eseguito il comando configurato <a href="/admin/settings#proxmox"> qui</a>.',
  'proxmox.admin.ipaddress.title' => 'IP di configurazione',
  'proxmox.admin.ipaddress.subtitle' => 'Amministrare i diversi indirizzi IP.',
  'proxmox.admin.ipaddress.used' => 'Usato?',
  'proxmox.admin.templates.title' => 'Modello',
  'proxmox.admin.type' => 'Digitare',
  'proxmox.settings.defaultdisk' => 'Disco predefinito da modificare',
  'proxmox.settings.vpsprefix' => 'Prefisso del nome host predefinito',
  'proxmox.settings.backupstorage' => 'Server di archiviazione di backup',
];