<?php
/**$
    Pterodactyl - it_IT
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:39:46
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'pterodactyl.failed.pwdempty' => 'La password non deve essere vuota',
  'pterodactyl.failed.linkserver' => 'La modifica della password non è riuscita perché il server collegato non esiste',
  'pterodactyl.failed.retrieveuser' => 'Ripristino dell\'utente non riuscito, codice di errore ricevuto: %status_code%',
  'pterodactyl.failed.changepwd' => 'Modifica della password non riuscita, codice di errore ricevuto: %status_code%',
  'pterodactyl.panel.problem' => 'Hai un problema con l\'hosting?',
  'pterodactyl.panel.openticket' => 'Apri un ticket!',
  'pterodactyl.panel.information' => 'Informazioni sulla struttura',
  'pterodactyl.panel.start' => 'Inizio',
  'pterodactyl.form.resources.disk' => 'Spazio su disco (MB)',
  'pterodactyl.form.resources.swap' => 'Barattare',
  'pterodactyl.form.resources.swaphelp' => '0 disabiliterà lo swap per il server. -1 non ammetterà alcuna limitazione',
  'pterodactyl.form.resources.io' => 'Blocco I/O',
  'pterodactyl.form.configurations.image' => 'Finestra mobile Immagine',
  'pterodactyl.form.configurations.startup' => 'Comando di avvio',
  'pterodactyl.form.configurations.oomkiller' => 'Disabilita OOM Killer',
  'pterodactyl.form.configurations.dedicatedip' => 'Indirizzo IP dedicato',
  'pterodactyl.failed.unsuspendexist' => 'L\'annullamento della sospensione del server non è riuscito perché non esiste.',
  'pterodactyl.failed.terminateexist' => 'Impossibile eliminare il server perché non esiste.',
  'pterodactyl.failed.satisfying' => 'Impossibile trovare nodi che soddisfino la domanda',
  'pterodactyl.panel.disk' => 'Spazio su disco',
  'pterodactyl.panel.memory' => 'Memoria',
  'pterodactyl.panel.button' => 'Gestisci il mio server',
  'pterodactyl.config.subtitle' => 'Gestire le diverse funzionalità dell\'offerta.',
  'pterodactyl.form.resources.title' => 'Risorse',
  'pterodactyl.form.resources.memory' => 'Memoria (MB)',
  'pterodactyl.form.core.nest' => 'ID Nido Pterodattilo',
  'pterodactyl.form.core.location' => 'ID Posizione Pterodattilo',
  'pterodactyl.form.configurations.title' => 'Configurazione',
  'pterodactyl.offline' => 'estinto',
  'pterodactyl.online' => 'Illuminato',
  'pterodactyl.failed.alreadycreated' => 'La creazione del server non è riuscita perché è già stato creato',
  'pterodactyl.failed.changepkgexist' => 'Impossibile modificare il pacchetto del server perché non esiste',
  'pterodactyl.failed.suspendexist' => 'Impossibile sospendere il server perché non esiste.',
  'pterodactyl.failed.createuser' => 'Creazione dell\'utente non riuscita, codice di errore ricevuto: %status_code%',
  'pterodactyl.failed.geteggs' => 'Impossibile ottenere i dati sull\'uovo, codice di errore ricevuto: %status_code%',
  'pterodactyl.failed.getserver' => 'Impossibile trasferire i dati al server, codice di errore ricevuto: %status_code%',
  'pterodactyl.failed.createserver' => 'Creazione del server non riuscita, codice di errore ricevuto: %status_code%',
  'pterodactyl.failed.suspendserver' => 'Sospensione del server non riuscita, codice di errore ricevuto: %status_code%',
  'pterodactyl.failed.unsuspendserver' => 'Sospensione del server non riuscita, codice di errore ricevuto: %status_code%',
  'pterodactyl.failed.terminateserver' => 'Eliminazione del server non riuscita, codice di errore ricevuto: %status_code%',
  'pterodactyl.failed.buildserver' => 'Aggiornamento della versione del server non riuscito, codice di errore ricevuto: %status_code%',
  'pterodactyl.failed.startupserver' => 'Aggiornamento all\'avvio del server non riuscito, codice di errore ricevuto: %status_code%',
  'pterodactyl.panel.stop' => 'Spegnere',
  'pterodactyl.panel.powerstop' => 'Uccidere',
  'pterodactyl.panel.restart' => 'Riavviare',
  'pterodactyl.adminindex.title' => 'Configurazione dello pterodattilo',
  'pterodactyl.adminindex.subtitle' => 'Gestire le configurazioni dell\'offerta.',
  'pterodactyl.adminindex.memory' => 'Memoria',
  'pterodactyl.adminindex.disk' => 'Spazio su disco',
  'pterodactyl.adminindex.productname' => 'Nome del prodotto',
  'pterodactyl.config.title' => 'Configurazione del server',
  'pterodactyl.form.resources.portrange' => 'Porta da assegnare al server (Esempio: 3000-4000)',
  'pterodactyl.form.resources.cpu' => 'Limite CPU (%)',
  'pterodactyl.form.features.title' => 'Tratti somatici',
  'pterodactyl.form.features.databases' => 'Database da assegnare al server',
  'pterodactyl.form.features.allocations' => 'Allocazioni aggiuntive da allocare al server',
  'pterodactyl.form.features.backups' => 'Backup dei dati da assegnare al server',
  'pterodactyl.form.core.title' => 'Informazione',
  'pterodactyl.form.core.servername' => 'Nome del server',
  'pterodactyl.form.core.egg' => 'ID Uovo Pterodattilo',
];