<?php
/**$
    Pterobox - it_IT
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:39:45
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'pterobox.cannot.core' => 'Non è possibile superare %limit% cores.',
  'pterobox.cannot.empty' => 'Non è possibile impostare un valore vuoto o 0',
  'pterobox.panel.disk' => 'Spazio su disco',
  'pterobox.config.subtitle' => 'Gestire le diverse funzionalità dell\'offerta.',
  'pterobox.form.resources.title' => 'Risorse',
  'pterobox.form.resources.servers' => 'Numero di server che è possibile creare',
  'pterobox.form.resources.cores' => 'Utilizzo della CPU (%)',
  'pterobox.form.features.allocations' => 'Indennità',
  'pterobox.form.features.backups' => 'Backup',
  'pterobox.form.features.servers' => 'Server',
  'pterobox.form.features.cores' => 'Cuori',
  'pterobox.form.core.title' => 'Informazione',
  'pterobox.form.core.egg' => 'ID Uovo Pterodattilo',
  'pterobox.cannot.database' => 'Non è possibile superare %limit% database.',
  'pterobox.cannot.backup' => 'Non è possibile superare %limit% backup.',
  'pterobox.cannot.allocation' => 'Non è possibile superare le allocazioni %limit%.',
  'pterobox.cannot.server' => 'Non è possibile superare %limit% server.',
  'pterobox.adminindex.disk' => 'Spazio su disco',
  'pterobox.adminindex.productname' => 'Nome del prodotto',
  'pterobox.config.title' => 'Configurazione del server',
  'pterobox.form.features.databases' => 'Banche dati',
  'pterobox.createserver' => 'Creare un server',
  'pterobox.updateserver' => 'Modificare il server',
  'pterobox.button' => 'Modificare',
  'pterobox.servername' => 'Nome del server',
  'pterobox.used' => 'usato',
  'pterobox.used2' => 'Usato',
  'pterobox.cannot.memory' => 'Non è possibile superare %limit% GB di memoria.',
  'pterobox.cannot.disk' => 'Non è possibile superare %limit% GB di spazio su disco.',
  'pterobox.panel.memory' => 'Memoria',
  'pterobox.panel.button' => 'Gestisci il mio server',
  'pterobox.panel.problem' => 'Hai un problema con l\'hosting?',
  'pterobox.panel.openticket' => 'Apri un ticket!',
  'pterobox.panel.information' => 'Informazioni sulla struttura',
  'pterobox.panel.backupswisp' => 'Dimensione limite di backup',
  'pterobox.panel.backupswisphelp' => 'Numero totale di Gigabyte che il server può utilizzare per i backup.',
  'pterobox.adminindex.title' => 'Configurazione Pterobox',
  'pterobox.adminindex.subtitle' => 'Gestire le configurazioni dell\'offerta.',
  'pterobox.adminindex.memory' => 'Memoria',
  'pterobox.form.resources.memory' => 'Memoria (GB)',
  'pterobox.form.resources.disk' => 'Spazio (GB)',
  'pterobox.form.resources.help' => 'Disponibile per l\'intera scatola',
  'pterobox.form.resources.portrange' => 'Porta da assegnare al server (Esempio: 3000-4000)',
  'pterobox.form.resources.cpu' => 'Limite CPU (%)',
  'pterobox.form.resources.swap' => 'Barattare',
  'pterobox.form.resources.swaphelp' => '0 disabiliterà lo swap per il server. -1 non ammetterà alcuna limitazione',
  'pterobox.form.resources.io' => 'Blocco I/O',
  'pterobox.form.features.title' => 'Tratti somatici',
  'pterobox.form.core.nest' => 'ID Nido Pterodattilo',
  'pterobox.form.core.location' => 'ID Posizione Pterodattilo',
];