<?php
/**$
    Support - it_IT
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:39:48
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'department' => 'Dipartimento',
  'support.related' => 'Servizio/transazione correlati',
  'support.admin.department.title' => 'Dipartimento',
  'support.admin.department.subtitle' => 'Amministrare i diversi reparti di supporto',
  'support.show.our_reply' => 'La nostra risposta',
  'support.show.your_reply' => 'La tua risposta',
  'support.priority' => 'Priorità',
  'support.priorities.High' => 'Alto',
  'support.priorities.Medium' => 'Nella media',
  'support.priorities.Low' => 'Debole',
  'departments' => 'Reparti',
  'your_tickets' => 'Le tue richieste',
  'new_ticket' => 'Nuova applicazione',
  'reply' => 'Risposta',
  'open_tickets' => 'Richieste aperte',
  'predefinedreplies' => 'Risposte predefinite',
  'predefinedreply' => 'Risposta preimpostata',
  'support.actions.close' => 'L\'applicazione è stata appena chiusa',
  'support.actions.reply' => 'La risposta è stata appena pubblicata',
  'support.table.last_updated' => 'Ultimo aggiornamento',
  'support.table.close' => 'Chiudere',
  'support.table.priority' => 'Priorità',
  'support.table.department' => 'Dipartimento',
  'support.table.subject' => 'Oggetto',
  'support.admin.ticket.createsubtitle' => 'Apri un ticket per un cliente specifico.',
  'support.email.title' => 'Risposta del nostro supporto alla richiesta %subject%',
  'support.email.content' => 'Il nostro supporto ha appena risposto alla tua richiesta di aiuto. Puoi visualizzarlo cliccando sul pulsante qui sopra.',
  'support.email.button' => 'Il mio biglietto',
  'support.show.reopentext' => 'La tua applicazione è attualmente chiusa, puoi riaprirla facendo clic sul pulsante.',
  'support.show.reopen' => 'Riapri l\'applicazione',
  'support.show.your_question' => 'La vostra richiesta',
  'support.department' => 'Dipartimento',
  'support.discussion' => 'Discussione',
  'support.content' => 'Richiesta',
  'support.newticket' => 'Nuovo Biglietto',
  'support.submit' => 'Per inviare',
  'tickets' => 'Biglietti',
  'support.title' => 'Supporto Tecnico',
  'support.messages' => 'Messaggi',
  'support.replied' => 'Ti ha risposto',
  'support.icon' => 'Icona',
  'support.informations' => 'Notizie',
  'support.actions.reopen' => 'L\'applicazione è stata appena riaperta.',
  'support.actions.submit' => 'L\'applicazione è stata appena aperta',
  'support.admin.predefined.title' => 'Risposte predefinite',
  'support.admin.predefined.create' => 'Puoi creare risposte predefinite <a href="%route%" target="_blank"></a> qui',
  'support.admin.predefined.subtitle' => 'Amministrare le varie risposte predefinite dal supporto',
  'support.admin.predefined.global' => 'La risposta può essere disponibile per tutto il personale',
  'support.admin.predefined.tips' => '<strong>[COGNOME]</strong> - Nome cliente | <strong>[FIRSTNAME]</strong> - Nome del cliente | <strong>[EMAIL]</strong> - E-mail del cliente |  <strong>[CORRELATO]</strong> Nome della transazione/servizio correlato (se definito)',
  'support.admin.ticket.title' => 'Appoggiare',
  'support.admin.ticket.subtitle' => 'Gestire i vari ticket di supporto',
  'support.show.reply' => 'Risposta',
  'support.show.textarea' => 'Si prega di spiegare il problema il più possibile. 
Non fornire informazioni riservate (password, ecc.), i nostri tecnici hanno tutte le informazioni necessarie per risolvere il tuo problema',
  'support.states.Pending' => 'In sospeso',
  'support.states.Reply Support' => 'Risposta dell\'assistenza',
  'support.states.Reply Customer' => 'Risposta del cliente',
  'support.states.Closed' => 'Chiuso',
  'support.print' => 'Stampare',
  'support.admin' => 'Il personale sarà avvisato via e-mail',
  'servicespage.options.manage' => 'Hai bisogno di un IP aggiuntivo o di più spazio su disco?',
];