<?php
/**$
    translator - it_IT
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:39:54
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'translatesitems.positive' => 'Il valore deve essere positivo.',
  'translatesitems.numeric' => 'Il valore deve essere un valore numerico valido.',
  'translatesitems.between' => 'Il valore deve essere compreso tra %d e %d.',
  'translatesitems.inArray' => 'Il valore non esiste nei seguenti valori: %s',
  'translatesitems.notInArray' => 'Il valore non deve esistere in questi valori: %s',
  'translatesitems.arrayHasKey' => 'L\'array deve contenere la chiave %s',
  'translatesitems.unique' => 'Il valore deve essere univoco nel database',
  'translatesitems.arrayHasNotKey' => 'La matrice non deve contenere la chiave %s',
  'translatesitems.filetype' => 'Il campo non è un formato convalidato (%s)',
  'translatesitems.maxLength' => 'Il valore deve contenere meno di %d caratteri.',
  'translatesitems.betweenLength' => 'Il valore deve contenere un numero di caratteri compreso tra %d e %d.',
  'translatesitems.bannedEmail' => 'L\'indirizzo e-mail o il nome di dominio sono vietati.',
  'translatesitems.email' => 'Il valore deve essere un indirizzo e-mail valido.',
  'translatesitems.invalidip' => 'il valore deve essere un indirizzo IP convalidato.',
  'translatesitems.url' => 'Il valore deve essere un URL verificato.',
  'translatesitems.domain' => 'Il valore deve essere un dominio valido.',
  'translatesitems.equals' => 'Il valore deve essere uguale alla relativa convalida.',
  'translatesitems.ispassword' => 'La password deve essere quella attuale.',
  'translatesitems.isfuture' => 'La data deve essere futura.',
  'translatesitems.startswith' => 'Il valore deve iniziare con %s.',
  'translatesitems.endswith' => 'Il valore deve terminare con %s.',
  'translatesitems.contains' => 'Il valore deve contenere %s',
  'translatesitems.notcontains' => 'Il valore non deve contenere %s',
  'translatesitems.passwordsecurity' => 'La tua password non è sicura! Si prega di usarne uno diverso',
  'translatesitems.sshpublic' => 'La chiave SSH deve essere una chiave valida',
  'translatesitems.boolean' => 'Il valore deve essere un valore booleano convalidato.',
  'translatesitems.int' => 'Il valore deve essere un numero convalidato.',
  'translatesitems.negative' => 'Il valore deve essere negativo.',
  'translatesitems.max' => 'Il numero deve essere inferiore a %d',
  'translatesitems.min' => 'Il numero deve essere almeno %d',
  'translatesitems.minLength' => 'Il valore deve contenere più di %d caratteri.',
  'translatesitems.license' => 'Questa licenza non è valida %s',
  'translatesitems.exists' => 'Il valore deve esistere nel database.',
  'translatesitems.ispast' => 'La data deve essere passata.',
  'translatesitems.true' => 'Il valore deve essere true.',
  'translatesitems.false' => 'Il valore deve essere false.',
  'translatesitems.uploaded' => 'È necessario caricare un file.',
  'translatesitems.required' => 'Il valore deve essere obbligatorio.',
  'translatesitems.empty' => 'Il valore non può essere vuoto.',
  'translatesitems.slug' => 'Il valore deve essere uno slug valido.',
  'translatesitems.phonenumber' => 'Il valore deve essere un numero di telefono valido.',
  'translatesitems.postcode' => 'Il valore deve essere un codice postale verificato (%s).',
  'translatesitems.numericOrZero' => 'Il valore deve essere un valore numerico valido o uguale a zero.',
  'translatesitems.positiveOrZero' => 'Il valore deve essere positivo o uguale a zero.',
  'translatesitems.ostemplate' => 'Devi scegliere tra un modello o un sistema operativo.',
  'translatesitems.domainIsAlreadyRegistered' => 'Questo dominio è già registrato',
];