<?php
/**$
    VirtualizorCloud - it_IT
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:39:50
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'virtualizorcloud.offline' => 'estinto',
  'virtualizorcloud.online' => 'Illuminato',
  'virtualizorcloud.planname' => 'Nome del piano',
  'virtualizorcloud.graph' => 'Grafica',
  'virtualizorcloud.panel.disk' => 'Spazio su disco',
  'virtualizorcloud.panel.cores' => 'Cuori',
  'virtualizorcloud.panel.in' => 'In arrivo',
  'virtualizorcloud.panel.out' => 'Estroverso',
  'virtualizorcloud.form.resources.priority' => 'Priorità I/O (OpenVZ)',
  'virtualizorcloud.form.resources.vnc' => 'VNC abilitato (KVM)',
  'virtualizorcloud.form.resources.speed' => 'Velocità di rete in KB/s (0 GB/s o vuoto senza limiti)',
  'virtualizorcloud.form.resources.server' => 'Server',
  'virtualizorcloud.form.stockage.space' => 'Spazio su disco (GB)',
  'virtualizorcloud.form.cpu.cores' => 'Cuori',
  'virtualizorcloud.form.cpu.units' => 'Unità',
  'virtualizorcloud.form.cpu.cpu' => '% CPU',
  'virtualizorcloud.form.ips.internalips' => 'Numero di indirizzi IP interni',
  'virtualizorcloud.form.ips.ips' => 'Numero di IP',
  'virtualizorcloud.admin.title' => 'Virtualizor di configurazione',
  'virtualizorcloud.admin.subtitle' => 'Gestire le configurazioni dell\'offerta.',
  'virtualizorcloud.admin.planname' => 'Nome del piano',
  'virtualizorcloud.config.title' => 'Configura la tua offerta',
  'virtualizorcloud.hostname' => 'Ospite',
  'virtualizorcloud.os' => 'OSSO',
  'virtualizorcloud.panel.restart' => 'Riavviare',
  'virtualizorcloud.panel.os_name' => 'OSSO',
  'virtualizorcloud.panel.bandwidth' => 'Larghezza di banda',
  'virtualizorcloud.panel.ram' => 'ARIETE',
  'virtualizorcloud.panel.virt' => 'Virtualizzazione',
  'virtualizorcloud.panel.cpu' => 'CPU',
  'virtualizorcloud.panel.reset' => 'Reinstallazione',
  'virtualizorcloud.form.resources.title' => 'Risorse',
  'virtualizorcloud.form.resources.disk' => 'Spazio su disco (GB)',
  'virtualizorcloud.form.resources.io' => 'Blocco I/O',
  'virtualizorcloud.form.resources.bandwidth' => 'Larghezza di banda (0 GB o vuota senza limiti)',
  'virtualizorcloud.form.resources.inodes' => 'INode (OpenVZ)',
  'virtualizorcloud.form.resources.network_speed' => 'Velocità di rete in MB/s',
  'virtualizorcloud.form.resources.upload_speed' => 'Velocità di download in MB/s',
  'virtualizorcloud.form.stockage.title' => 'Immagazzinamento',
  'virtualizorcloud.form.stockage.ram' => 'MB di RAM (KVM, LXC)',
  'virtualizorcloud.form.stockage.guaranteed' => 'Garanzia RAM (MB)',
  'virtualizorcloud.form.stockage.burstable' => 'RAM espandibile (OpenVZ)',
  'virtualizorcloud.form.configurations.group' => 'Gruppo',
  'virtualizorcloud.form.configurations.vnc' => 'VNC',
  'virtualizorcloud.form.ips.ip6subnet' => 'Numero di indirizzi IPV6',
  'virtualizorcloud.form.ips.ip6' => 'Numero di indirizzi IPv6 della subnet',
  'virtualizorcloud.productname' => 'Nome del prodotto',
  'virtualizorcloud.choosehostname' => 'Scegliere un nome host personalizzato',
  'virtualizorcloud.panel.button' => 'Connessione',
  'virtualizorcloud.panel.start' => 'Inizio',
  'virtualizorcloud.panel.stop' => 'Spegnere',
  'virtualizorcloud.panel.powerstop' => 'Uccidere',
  'virtualizorcloud.panel.usage' => 'Uso',
  'virtualizorcloud.panel.site' => 'Apri il sito web',
  'virtualizorcloud.panel.information' => 'Informazioni sulla struttura',
  'virtualizorcloud.panel.problem' => 'Hai un problema con l\'hosting?',
  'virtualizorcloud.panel.openticket' => 'Apri un ticket!',
  'virtualizorcloud.panel.uptime' => 'Disponibilità',
  'virtualizorcloud.form.resources.ip6' => 'IPv6 (Protocollo IPv6)',
  'virtualizorcloud.form.resources.ip6subnet' => 'Subnet IP6',
  'virtualizorcloud.form.resources.ips' => 'IP',
  'virtualizorcloud.form.resources.oses' => 'Ossa disponibili (separate da virgole)',
  'virtualizorcloud.form.resources.internalips' => 'IP interno',
  'virtualizorcloud.form.resources.portrange' => 'Porta da assegnare al server (separata da virgole)',
  'virtualizorcloud.form.cpu.title' => 'CPU',
  'virtualizorcloud.form.converter.title' => 'Convertitore',
  'virtualizorcloud.form.converter.mb' => 'Digita il tuo numero in MB',
  'virtualizorcloud.form.converter.gb' => 'Digita il tuo numero in GB',
  'virtualizorcloud.form.configurations.title' => 'Configurazione',
  'virtualizorcloud.form.configurations.server' => 'Server',
  'virtualizorcloud.config.subtitle' => 'Amministrare le funzionalità dell\'offerta.',
  'virtualizorcloud.converter.title' => 'Convertitore',
  'virtualizorcloud.converter.mb' => 'Digita il tuo numero in MB',
  'virtualizorcloud.converter.gb' => 'Digita il tuo numero in GB',
];