<?php
/**$
    Welcome - it_IT
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:39:51
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'why_choose_us' => 'Perché scegliere noi?',
  'demonstration' => 'Dimostrazione',
  'demonstrationcontent' => 'Vuoi scoprire la tua futura area clienti? Accedi a una versione demo!',
  'community.title' => 'Comunità',
  'community.twitter.title' => 'Cinguettare',
  'community.twitter.description' => 'Puoi seguirci su Twitter per essere il primo ad essere avvisato dei futuri aggiornamenti.',
  'community.twitter.seemore' => 'Guarda i nostri tweet',
  'themepage.larium.administration.description' => 'Non c\'è bisogno di aprire il tuo accesso FTP, vai direttamente dall\'amministrazione <span class="text-primary fw-bold">CLIENTXCMS</span> per personalizzare il tuo',
  'themepage.larium.administration.list.position.title' => 'Posizioni',
  'themepage.larium.administration.list.position.content' => 'Modifica le posizioni degli elementi (sezioni, menu, cursori, link a piè di pagina) con un semplice clic.',
  'themepage.larium.administration.list.component.title' => 'Componenti automatizzati',
  'themepage.list.visual.title' => 'Nessuna modifica visiva',
  'themepage.list.visual.content' => 'I tuoi clienti non vedono la differenza tra il tuo sito commerciale e la loro area clienti.',
  'themepage.list.components.title' => 'Componenti interattivi',
  'themepage.list.components.content' => 'Aggiungere, modificare, cambiare la posizione dei componenti sulle pagine.',
  'pricing.description' => 'Inizia a lavorare con <span class="text-primary font-weight-bold"> CLIENTXCMS </span> e avvia oggi la tua attività di web hosting.',
  'pricing.formuls.hostownserver' => 'Ospitato sul tuo server',
  'pricing.formuls.custom' => 'Personalizzabile e configurabile',
  'pricing.formuls.sourcecode' => 'Codice sorgente incluso',
  'pricing.formuls.withall' => '%count% Moduli gratuiti a pagamento',
  'pricing.install.title' => 'Installazione e configurazione',
  'pricing.install.count' => 'per installazione',
  'pricing.embedding.title' => 'Incorporare il tuo sito',
  'pricing.embedding.count' => 'attraverso l\'integrazione',
  'pricing.embedding.content' => 'Assicurati che la tua area clienti sia identica al tuo sito web senza transizioni!',
  'pricing.mail.title' => 'Server di posta',
  'pricing.mail.content' => 'Ordinate un server SMTP per la vostra azienda direttamente da CLIENTXCMS.',
  'for.services.notincluded' => 'Modulo aggiuntivo',
  'darktheme' => 'Modalità notturna',
  'features.translated.title' => 'Completamente tradotto',
  'features.configurable.content' => 'Configura i tuoi prodotti, server e opzioni per personalizzare CLIENTXCMS a tuo piacimento.',
  'features.security.title' => 'Sicurezza',
  'features.security.content' => 'CLIENTCMS è in continua evoluzione e migliora la sicurezza giorno dopo giorno.',
  'features.support.title' => 'Supporto personalizzato',
  'features.support.content' => 'Un team a disposizione ogni giorno per aiutarti e rispondere alle tue domande.',
  'home' => 'Ricevimento',
  'shopmore' => 'Ordina di più',
  'reload' => 'Ricaricare',
  'our_modules' => 'I nostri moduli',
  'decovery_our_modules' => 'Scopri i nostri moduli',
  'backtohome' => 'Torna alla homepage',
  'addthemeandfinish' => 'Aggiungi tema e finitura',
  'why_choose_us_sub' => 'CLIENTXCMS è stato creato per la nuova generazione di host innovativi. Configurazione meno complicata, creazione più veloce.',
  'emailtemplates.title' => 'I nostri modelli di email',
  'emailtemplates.subtitle' => 'Personalizza la tua area clienti <span class="text-primary font-weight-bold"> CLIENTXCMS </span> con modelli di email che corrispondono alla tua azienda',
  'licensecheckerpage.howtouse' => 'Come utilizzare questo strumento:',
  'licensecheckerpage.first' => 'Immettere <b>solo</b> il nome di dominio in cui è installato CLIENTXCMS',
  'licensecheckerpage.second' => 'Ad esempio, se è stata eseguita un\'installazione di @ https://clients.exemple.com, è sufficiente inserire <b>clients.exemple.com</b> come dominio',
  'licensecheckerpage.third' => 'Il dominio non deve includere il <b>www</b> o il <b>https://</b>.',
  'cookieconsent' => 'Questo sito web utilizza i cookie per offrirti un\'esperienza utente. Utilizzandolo, accetti il nostro <a href=\'/\' target=\'_blank\' class=\'text-success h6\'> l\'uso dei cookie</a>',
  'welcome.heading' => 'Nuova generazione di provider di hosting',
  'welcome.description' => 'Avvia la tua attività di web hosting con i nostri strumenti.',
  'welcome.refund' => 'Inviando questo modulo, accetti le nostre Condizioni di vendita e utilizzo.',
  'community.discord.title' => 'Discordia',
  'community.discord.description' => 'Usiamo Discord per fornire supporto e per ottenere il tuo feedback in modo da poter pianificare aggiornamenti futuri.',
  'community.discord.seemore' => 'Unisciti al nostro server',
  'themepage.title' => 'Noi abbiamo riunito<br/>
                Il tuo sito web e la tua area clienti',
  'themepage.larium.title' => 'Personalizzabile a piacere',
  'themepage.larium.subtitle' => 'Non c\'è bisogno di gestire un sito vetrina, <span class="text-primary fw-bold">CLIENTXCMS</span> lo include con un\'installazione con un clic e una configurazione semplificata',
  'themepage.larium.subtitle2' => 'Semplifica la tua vita spendendo meno con Larium',
  'themepage.larium.rlt.title' => 'RTL e LTR',
  'themepage.larium.rlt.description' => 'Scegli la posizione <span class="text-primary fw-bold"></span>del menu di navigazione del client dalle impostazioni del tema.',
  'themepage.larium.nightmode.title' => 'Modalità giorno e notte',
  'themepage.larium.nightmode.description' => 'Scegli la modalità <span class="text-primary fw-bold"></span> del tuo tema Notte o Giorno',
  'themepage.larium.administration.title' => 'Gestione da parte dell\'amministrazione',
  'themepage.larium.administration.list.component.content' => 'I componenti possono visualizzare informazioni in modo dinamico, ad esempio annunci o gruppi di prodotti.',
  'themepage.larium.administration.list.translation.title' => 'Componenti di traduzione',
  'themepage.larium.administration.list.translation.content' => 'I componenti possono essere tradotti in base alla lingua dell\'utente.',
  'themepage.larium.administration.list.flex.title' => 'Flessibilità',
  'themepage.larium.administration.list.flex.content' => 'Aggiungi tutti i menu, le sezioni, i social network, i cursori o i link a piè di pagina che desideri.',
  'themepage.larium.administration.list.footer' => 'Gestione del piè di pagina',
  'themepage.larium.administration.list.sections' => 'Gestione delle sezioni',
  'themepage.larium.administration.list.menus' => 'Gestione dei menu',
  'themepage.larium.administration.list.info' => 'Social Media e gestione delle informazioni',
  'themepage.larium.administration.list.sliders' => 'Gestione dello slider sulla homepage',
  'themepage.list.synchronization.title' => 'Prodotti sincronizzati',
  'themepage.list.synchronization.content' => 'Non dovrai più modificare le tue descrizioni in due punti, tutto è sincronizzato.',
  'themepage.list.personalization.title' => 'Personalizzazione',
  'themepage.list.personalization.content' => 'Modifica facilmente il menu di navigazione della tua azienda o i social network.',
  'themepage.subtitle' => 'Approfitta di un sito vetrina incluso in <span class="text-primary fw-bold">CLIENTXCMS che è</span> facile da installare e configurabile come desideri.',
  'themepage.notincluded' => 'Tema non incluso nei nostri piani predefiniti. <a href=\'/Larium\'>Disponibile per l\'acquisto</a>.',
  'modulesfeatures.title' => 'I nostri moduli ufficiali',
  'modulesfeatures.title2' => 'Hai bisogno di più moduli?',
  'modulesfeatures.description2' => 'Altri moduli <span class="text-primary font-weight-bold"> CLIENTXCMS </span> sono disponibili nel negozio!',
  'modulesfeatures.description' => 'Inizia a lavorare con <span class="text-primary font-weight-bold"> CLIENTXCMS e con </span> i moduli sviluppati da noi per te.',
  'modulesfeatures.button' => 'Documentazione ufficiale di CLIENTXCMS',
  'modulesfeatures.documentation' => 'Trova facilmente le risposte a tutte le tue domande con la nostra documentazione!',
  'documentation.title' => 'Documentazione',
  'pricing.title' => 'Tariffe',
  'pricing.formuls.unlimited' => 'Clienti illimitati',
  'pricing.formuls.customers' => 'Fino al %<strong>count%</strong> clienti',
  'pricing.formuls.domain' => '1 Dominio autorizzato',
  'pricing.formuls.nothostownserver' => 'Ospitato sui nostri server',
  'pricing.formuls.modulesfree' => '<strong>%count%</strong> Moduli a pagamento offerti',
  'pricing.formuls.modulefree' => '1 modulo gratuito a pagamento',
  'pricing.formuls.domains' => '%count% Domini consentiti',
  'pricing.formuls.support' => '%supporto% supporto incluso',
  'pricing.formuls.nosourcecode' => 'Codice sorgente non incluso',
  'pricing.formuls.discord' => 'Grade & Private Rooms sul nostro discord',
  'pricing.formuls.installation' => 'Installazione da parte del nostro team',
  'pricing.formuls.with' => 'Conteggio dei moduli gratuiti',
  'pricing.formuls.themes' => 'Contare i temi offerti',
  'pricing.install.dedicated' => 'VPS/Dedicato',
  'pricing.install.content' => 'Assicurati un\'installazione fluida e di successo e lascia che il nostro team installi e configuri CLIENTXCMS per te.',
  'pricing.integration.title' => 'Incorporare il tuo sito',
  'pricing.integration.count' => 'per integrazione',
  'pricing.integration.content' => 'Assicurati che la tua area clienti sia identica al tuo sito web senza transizioni!',
  'pricing.hosting.title' => 'Web Hosting',
  'pricing.hosting.our_hosting' => 'Il nostro web hosting',
  'pricing.hosting.content' => 'Ordina il tuo web hosting per la tua attività direttamente da CLIENTXCMS.',
  'pricing.reseller.title' => 'Rivenditore Web',
  'pricing.reseller.content' => 'Ordina un rivenditore web per la tua azienda direttamente da CLIENTXCMS.',
  'pricing.mailer.title' => 'Server di posta elettronica',
  'pricing.mailer.content' => 'Ordinate un server SMTP per la vostra azienda direttamente da CLIENTXCMS.',
  'for.services.included' => 'A disposizione di tutti',
  'features.translated.content' => 'Tutti i CLIENTXCMS sono tradotti in più lingue, il che rende possibile acquisire clienti da tutto il mondo.',
  'features.developper.title' => 'Adatto agli sviluppatori',
  'features.developper.content' => 'Siamo ben studiati e le risorse della nostra community semplificano lo sviluppo e la personalizzazione di CLIENTXCMS.',
  'features.responsive.content' => 'L\'area clienti è adatta a qualsiasi tipo di schermo per migliorare l\'esperienza dell\'utente.',
  'features.tasks.title' => 'Attività pianificate',
  'features.tasks.content' => 'Le attività ricorrenti vengono eseguite per inviare e-mail o gestire automaticamente i servizi.',
  'features.easy.title' => 'Semplicismo',
  'features.easy.content' => 'Il CMS è progettato per essere il più semplice e intuitivo possibile, adatto sia ai principianti che agli utenti esperti.',
  'features.installation.title' => 'Installazione con 1 clic',
  'features.installation.content' => 'I moduli possono essere scaricati dall\'area di amministrazione della propria area clienti. In questo modo si evitano installazioni complesse.',
  'features.configurable.title' => 'Configurabile',
  'features.title' => 'Le nostre soluzioni',
  'features.description' => 'Inizia a lavorare con <span class="text-primary font-weight-bold">CLIENTXCMS</span> che può fornire tutto ciò di cui hai bisogno per generare profitti, acquisire nuovi clienti e avere un\'interfaccia utente moderna.',
  'pricing.ctxhosting.title' => 'Offriamo piani predefiniti per i provider di hosting',
  'pricing.ctxhosting.content' => 'CTXHosting è la nostra gamma di hosting di alta qualità con offerte pensate per i provider di hosting a partire da <strong>XX€/mese</strong>',
  'pricing.ctxhosting.domain' => 'Nome di dominio .fr acquistabile',
  'pricing.ctxhosting.included' => 'CLIENTXCMS incluso nell\'offerta e preconfigurato',
  'pricing.ctxhosting.info' => 'Servizi gestiti e assistenza',
  'pricing.ctxhosting.installation' => 'Installazione entro 48 ore lavorative',
  'pricing.ctxhosting.start' => 'da XX€/mese',
  'pricing.ctxhosting.addon' => 'Offriamo offerte di archiviazione HDD VPS o PBS per i tuoi clienti.',
];