<?php
/**$
    Wisp - it_IT
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:39:51
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'Wisp.failed.linkserver' => 'La modifica della password non è riuscita perché il server collegato non esiste',
  'Wisp.failed.retrieveuser' => 'Ripristino dell\'utente non riuscito, codice di errore ricevuto: %status_code%',
  'Wisp.failed.changepwd' => 'Modifica della password non riuscita, codice di errore ricevuto: %status_code%',
  'Wisp.panel.openticket' => 'Apri un ticket!',
  'Wisp.panel.information' => 'Informazioni sulla struttura',
  'Wisp.panel.start' => 'Inizio',
  'Wisp.form.resources.title' => 'Risorse',
  'Wisp.form.resources.memory' => 'Memoria (MB)',
  'Wisp.form.resources.disk' => 'Spazio su disco (MB)',
  'Wisp.form.configurations.title' => 'Configurazione',
  'Wisp.form.configurations.image' => 'Finestra mobile Immagine',
  'Wisp.form.configurations.startup' => 'Comando di avvio',
  'Wisp.failed.alreadycreated' => 'La creazione del server non è riuscita perché è già stato creato',
  'Wisp.failed.changepkgexist' => 'Impossibile modificare il pacchetto del server perché non esiste',
  'Wisp.failed.suspendexist' => 'Impossibile sospendere il server perché non esiste.',
  'Wisp.failed.unsuspendexist' => 'L\'annullamento della sospensione del server non è riuscito perché non esiste.',
  'Wisp.failed.terminateexist' => 'Impossibile eliminare il server perché non esiste.',
  'Wisp.failed.satisfying' => 'Impossibile trovare nodi che soddisfino la domanda',
  'Wisp.failed.pwdempty' => 'La password non deve essere vuota',
  'Wisp.failed.suspendserver' => 'Sospensione del server non riuscita, codice di errore ricevuto: %status_code%',
  'Wisp.failed.unsuspendserver' => 'Sospensione del server non riuscita, codice di errore ricevuto: %status_code%',
  'Wisp.failed.terminateserver' => 'Eliminazione del server non riuscita, codice di errore ricevuto: %status_code%',
  'Wisp.failed.buildserver' => 'Aggiornamento della versione del server non riuscito, codice di errore ricevuto: %status_code%',
  'Wisp.failed.startupserver' => 'Aggiornamento all\'avvio del server non riuscito, codice di errore ricevuto: %status_code%',
  'Wisp.panel.disk' => 'Spazio su disco',
  'Wisp.panel.memory' => 'Memoria',
  'Wisp.panel.button' => 'Gestisci il mio server',
  'Wisp.panel.problem' => 'Hai un problema con l\'hosting?',
  'Wisp.adminindex.subtitle' => 'Gestire le configurazioni dell\'offerta.',
  'Wisp.adminindex.memory' => 'Memoria',
  'Wisp.adminindex.disk' => 'Spazio su disco',
  'Wisp.adminindex.productname' => 'Nome del prodotto',
  'Wisp.migrate.title' => 'Migrazione Wisp',
  'Wisp.migrate.subtitle' => 'Utilizzare questa pagina per eseguire la migrazione delle configurazioni di Pterodattilo a Wisp.',
  'Wisp.migrate.info' => 'Questa azione modificherà i tipi di prodotto, migrerà le configurazioni dal modulo Pterodattilo al modulo Wisp.',
  'Wisp.config.title' => 'Configurazione del server',
  'Wisp.config.subtitle' => 'Gestire le diverse funzionalità dell\'offerta.',
  'Wisp.form.features.title' => 'Tratti somatici',
  'Wisp.form.features.databases' => 'Database da assegnare al server',
  'Wisp.form.features.backups' => 'Limite di dimensione del backup (MB)',
  'Wisp.form.features.allocations' => 'Allocazione (MB)',
  'Wisp.form.core.title' => 'Informazione',
  'Wisp.form.core.servername' => 'Nome del server',
  'Wisp.form.core.egg' => 'Fuoco Fatuo dell\'uovo ID',
  'Wisp.form.core.nest' => 'ID Nest Wisp',
  'Wisp.form.core.location' => 'Ubicazione ID Wisp',
  'Wisp.form.converter.gb' => 'Digita il tuo numero in GB',
  'Wisp.offline' => 'estinto',
  'Wisp.online' => 'Illuminato',
  'Wisp.failed.createuser' => 'Creazione dell\'utente non riuscita, codice di errore ricevuto: %status_code%',
  'Wisp.failed.geteggs' => 'Impossibile ottenere i dati sull\'uovo, codice di errore ricevuto: %status_code%',
  'Wisp.failed.getserver' => 'Impossibile trasferire i dati al server, codice di errore ricevuto: %status_code%',
  'Wisp.failed.createserver' => 'Creazione del server non riuscita, codice di errore ricevuto: %status_code%',
  'Wisp.panel.stop' => 'Spegnere',
  'Wisp.panel.powerstop' => 'Uccidere',
  'Wisp.panel.restart' => 'Riavviare',
  'Wisp.adminindex.title' => 'Configurazione di Wisp',
  'Wisp.form.resources.swap' => 'Barattare',
  'Wisp.form.resources.io' => 'Blocco I/O',
  'Wisp.form.resources.portrange' => 'Porta da assegnare al server (separata da virgole)',
  'Wisp.form.resources.cpu' => 'Limite CPU (%)',
  'Wisp.form.configurations.oomkiller' => 'Disabilita OOM Killer',
  'Wisp.form.configurations.dedicatedip' => 'Indirizzo IP dedicato',
  'Wisp.form.converter.title' => 'Convertitore',
  'Wisp.form.converter.mb' => 'Digita il tuo numero in MB',
  'wisp.admin.migratebtn' => 'Area di migrazione',
];