<?php
/**$
    License - de_DE
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:21
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'your_licenses' => 'Ihre Lizenzen',
  'max_domains' => 'Nein. Zulässige Domänen',
  'max_customers' => 'Nein. Autorisierte Kunden',
  'your_domains' => 'Ihre autorisierten Domains',
  'serverstatus' => 'Server-Status',
  'add2' => 'Hinzufügen',
  'upgradenow' => 'Upgraden Sie jetzt Ihre Lizenz',
  'upgradedays' => '%Tage% Angebotene Tage',
  'reset2' => 'Zurücksetzen',
  'automaticrenewal' => 'Automatische Verlängerung',
  'manualrenewal' => 'Manuelle Verlängerung',
  'licenseexpired' => 'Warnung: Ihre Lizenz ist abgelaufen, um CLIENTXCMS weiterhin verwenden zu können, erneuern Sie Ihren Lizenzschlüssel.',
  'ordernow' => 'Jetzt bestellen',
  'ordernow2' => 'Bestellen Sie Ihre CLIENTXCMS-Lizenz ab 9,99 € /Monat',
  'checkoutpage.modules.modulechoose2' => 'Sie können <b>Add-Ons für die Anzahl</b> Ihrer Angebote auswählen',
  'checkoutpage.modules.primarymodule' => 'Erstes Modul',
  'checkoutpage.modules.secondarymodule' => 'Zweites Modul',
  'checkoutpage.modules.tertiarymodule' => 'Drittes Modul',
  'checkoutpage.modules.canchangemodule' => 'Sie können Ihre Module bei der nächsten Verlängerung ändern',
  'checkoutpage.modules.canchange' => 'Sie können diese Domain auch nach dem Kauf noch ändern',
  'checkoutpage.modules.canchange2' => 'Sie können diese Domain auch nach der Verlängerung noch ändern',
  'checkoutpage.modules.modulechoose3' => 'Module, die mit der Lizenz erworben wurden, sind lebenslang gültig',
  'checkoutpage.modules.modulechoose' => 'Wählen Sie ein Add-on',
  'checkoutpage.installation.title' => 'Installation',
  'checkoutpage.installation.subtitle' => 'Unser Team richtet Ihren Kundenbereich für Sie ein, sobald Sie Ihre Bestellung erhalten haben.',
  'licensechecker' => 'Lizenz-Verifizierung',
  'licencepage.reset' => 'Die Lizenzschlüssel wurden erfolgreich zurückgesetzt.',
  'licencepage.reinstall' => 'Token erfolgreich zurückgesetzt',
  'licencepage.save' => 'Die Informationen wurden erfolgreich geändert.',
  'reinstall' => 'Neuinstallieren',
  'onetimemodule' => 'Lifetime-Modul',
  'downloadablefromadmin' => 'Herunterladbares Modul aus Ihrem Administrationsbereich.',
  'experimental.title' => 'Experimenteller Modus',
  'experimental.help' => 'Der experimentelle Modus ermöglicht es Ihnen, Funktionen im Voraus zu haben, kann aber Fehler verursachen, die mit Vorsicht verwendet werden sollten.',
  'downloadmodal.title' => 'Download ist in %version% Version bereit',
  'downloadmodal.description' => 'Bei einer Neuinstallation muss das Token zurückgesetzt werden.',
  'downloadmodal.button1' => 'Laden Sie das Archiv herunter',
  'downloadmodal.button2' => 'Token zurücksetzen',
  'downloadmodal.button3' => 'Lizenzschlüssel zurücksetzen',
  'renewlicense' => 'Lizenz erneuern',
  'renewmodule' => 'Modul erneuern',
];