<?php
/**$
    Proxmox - de_DE
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:11
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'proxmox.console' => 'Konsole',
  'proxmox.disk' => 'Speicherplatz',
  'proxmox.cores' => 'Herz',
  'proxmox.cpuunits' => 'CPU',
  'proxmox.net' => 'Netto',
  'proxmox.panel.problem' => 'Haben Sie ein Problem mit dem Hosting?',
  'proxmox.panel.openticket' => 'Eröffnen Sie ein Ticket!',
  'proxmox.network.title' => 'Netz',
  'proxmox.reboot' => 'Neustarten',
  'proxmox.snapshots.title' => 'Schnappschüsse',
  'proxmox.snapshots.remaining' => 'Es sind nur noch %verbleibende% Snapshots zulässig.',
  'proxmox.backups.success2' => 'Gelöschtes Backup.',
  'proxmox.backups.unauthorized' => 'Sie können keine Sicherungskopie erstellen.',
  'proxmox.form.converter.title' => 'Konverter',
  'proxmox.form.converter.mb' => 'Geben Sie Ihre Nummer in MB ein',
  'proxmox.form.converter.gb' => 'Geben Sie Ihre Nummer in GB ein',
  'proxmox.admin.title' => 'Proxmox-Einrichtung',
  'proxmox.admin.subtitle' => 'Verwalten Sie Ihre Angebotskonfigurationen.',
  'proxmox.admin.productname' => 'Produktname',
  'proxmox.memory' => 'Gedächtnis',
  'proxmox.bwlimit' => 'Bandbreite',
  'proxmox.graph' => 'Graphik',
  'proxmox.unlimited' => 'Unbegrenzt',
  'proxmox.network.type' => 'Art',
  'proxmox.network.link_down' => 'Trennen',
  'proxmox.network.virtio' => 'Virtio',
  'proxmox.network.rate' => 'Milz',
  'proxmox.backups.success3' => 'Backup wiederhergestellt.',
  'proxmox.reinstall.title' => 'Neuinstallation',
  'proxmox.reinstall.remaining' => 'Es bleiben %verbleibende% autorisierte Installationen.',
  'proxmox.reinstall.limit' => 'Sie haben die maximal zulässige Anzahl von Deinstallationen erreicht.',
  'proxmox.reinstall.success' => 'Installation.',
  'proxmox.form.restrictions.reinstall' => 'Anzahl der genehmigten Umzüge',
  'proxmox.form.restrictions.nolimit' => '0 für unbegrenzt',
  'proxmox.form.restrictions.unauthorized' => '0 zum Deaktivieren',
  'proxmox.admin.templates.subtitle' => 'Verwalten Sie die verschiedenen Proxmox-Vorlagen',
  'proxmox.admin.oses.title' => 'Wagen',
  'proxmox.admin.oses.subtitle' => 'Verwalten Sie die verschiedenen Proxmox-Betriebssysteme',
  'proxmox.os' => 'KNOCHEN',
  'proxmox.template' => 'Betriebssystem-Modell',
  'proxmox.offline' => 'ausgestorben',
  'proxmox.online' => 'Angezündet',
  'proxmox.format' => 'Disc-Format',
  'proxmox.size' => 'Größe des Datenträgers',
  'proxmox.hostname' => 'Gastgeber',
  'proxmox.tasks' => 'Flecken',
  'proxmox.uptime' => 'Verfügbarkeit',
  'proxmox.cpu' => 'CPU',
  'proxmox.button' => 'Verbindung',
  'proxmox.informations' => 'Information',
  'proxmox.start' => 'Anfangen',
  'proxmox.stop' => 'So deaktivieren Sie',
  'proxmox.shutdown' => 'Töten',
  'proxmox.choosehostname' => 'Wählen Sie einen benutzerdefinierten Hostnamen',
  'proxmox.network.gw' => 'Tor',
  'proxmox.network.gw6' => 'Gateway v6',
  'proxmox.network.ip' => 'IP-Adresse',
  'proxmox.network.firewall' => 'Feuerstopp',
  'proxmox.network.mtu' => 'Maximale Schnittstellenübertragung',
  'proxmox.network.ip6' => 'IP-Adresse v6',
  'proxmox.network.name' => 'Name',
  'proxmox.network.bridge' => 'Brücke',
  'proxmox.network.hwaddr' => 'MAC-Adresse',
  'proxmox.snapshots.limit' => 'Sie haben die maximal zulässige Anzahl von Snapshots erreicht.',
  'proxmox.snapshots.success' => 'Snapshot gespeichert.',
  'proxmox.snapshots.success2' => 'Snapshot gelöscht.',
  'proxmox.snapshots.success3' => 'Snapshot wiederhergestellt.',
  'proxmox.snapshots.unauthorized' => 'Sie können keinen Schnappschuss machen.',
  'proxmox.backups.title' => 'Sicherungen',
  'proxmox.backups.remaining' => 'Es sind nur noch %verbleibende% Sicherungen(n) zulässig.',
  'proxmox.backups.limit' => 'Sie haben die maximal zulässige Anzahl von Sicherungen erreicht.',
  'proxmox.backups.success' => 'Gespeichertes Backup.',
  'proxmox.config.title' => 'Proxmox',
  'proxmox.config.subtitle' => 'Verwalten Sie die Funktionen des Angebots.',
  'proxmox.form.title' => 'Konfiguration proxmox',
  'proxmox.form.block' => 'IP-Sperre (z.B. 123.223.134.XX / 24)',
  'proxmox.form.importertitle' => 'IP-Block-Importer',
  'proxmox.form.range' => 'IP-Bereich (z. B. 1-16)',
  'proxmox.form.btn' => 'Schneller Import',
  'proxmox.form.global.title' => 'Allgemeine Informationen',
  'proxmox.form.restrictions.title' => 'Einschränkung',
  'proxmox.form.restrictions.snapshot' => 'Anzahl der zulässigen Snapshots',
  'proxmox.form.restrictions.backup' => 'Anzahl der zulässigen Sicherungen',
  'proxmox.settings.password' => 'Legen Sie ein zufälliges Root-Passwort fest und senden Sie es bei der Lieferung per E-Mail',
  'proxmox.settings.lxcparams' => 'Hinzufügen von Parametern beim Hinzufügen des Netzwerks',
  'proxmox.settings.lxcparamshelp' => 'Beispiel: bridge=vmbr0,',
  'proxmox.settings.sshcommand' => 'Befehl, der bei der Installation eines VPS ausgeführt wird',
  'proxmox.settings.sshexecutehelp' => 'Es stehen Variablen zur Verfügung. Weitere Informationen finden Sie in unserer <a href="%link%">Dokumentation</a>',
  'proxmox.settings.sshexecutehelp2' => 'Ist dieser Befehl leer, wird der hier konfigurierte Befehl <a href="/admin/settings#proxmox"> ausgeführt</a>.',
  'proxmox.admin.ipaddress.title' => 'Konfigurations-IP',
  'proxmox.admin.ipaddress.subtitle' => 'Verwalten Sie die verschiedenen IP-Adressen.',
  'proxmox.admin.ipaddress.used' => 'Gebraucht?',
  'proxmox.admin.templates.title' => 'Modell',
  'proxmox.admin.type' => 'Art',
  'proxmox.settings.defaultdisk' => 'Zu ändernder Standarddatenträger',
  'proxmox.settings.vpsprefix' => 'Standardpräfix für Hostnamen',
  'proxmox.settings.backupstorage' => 'Backup-Speicherserver',
];