<?php
/**$
    Pterodactyl - de_DE
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:12
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'pterodactyl.failed.pwdempty' => 'Das Passwort darf nicht leer sein',
  'pterodactyl.failed.linkserver' => 'Kennwortänderung fehlgeschlagen, da der Verbindungsserver nicht vorhanden ist',
  'pterodactyl.failed.retrieveuser' => 'Benutzerwiederherstellung fehlgeschlagen, Fehlercode empfangen: %status_code%',
  'pterodactyl.failed.changepwd' => 'Kennwortänderung fehlgeschlagen, Fehlercode empfangen: %status_code%',
  'pterodactyl.panel.problem' => 'Haben Sie ein Problem mit dem Hosting?',
  'pterodactyl.panel.openticket' => 'Eröffnen Sie ein Ticket!',
  'pterodactyl.panel.information' => 'Immobilien-Info',
  'pterodactyl.panel.start' => 'Anfangen',
  'pterodactyl.form.resources.disk' => 'Speicherplatz (MB)',
  'pterodactyl.form.resources.swap' => 'Tauschen',
  'pterodactyl.form.resources.swaphelp' => '0 deaktiviert den Swap für den Server. -1 lässt keine Begrenzung zu',
  'pterodactyl.form.resources.io' => 'E/A-Block',
  'pterodactyl.form.configurations.image' => 'Bild-Docker',
  'pterodactyl.form.configurations.startup' => 'Befehl "Starten"',
  'pterodactyl.form.configurations.oomkiller' => 'OOM-Killer deaktivieren',
  'pterodactyl.form.configurations.dedicatedip' => 'Dedizierte IP-Adresse',
  'pterodactyl.failed.unsuspendexist' => 'Das Aufheben der Serversperre ist fehlgeschlagen, da er nicht vorhanden ist.',
  'pterodactyl.failed.terminateexist' => 'Der Server konnte nicht gelöscht werden, da er nicht vorhanden ist.',
  'pterodactyl.failed.satisfying' => 'Es konnten keine Knoten gefunden werden, die die Nachfrage befriedigen',
  'pterodactyl.panel.disk' => 'Speicherplatz',
  'pterodactyl.panel.memory' => 'Gedächtnis',
  'pterodactyl.panel.button' => 'Meinen Server verwalten',
  'pterodactyl.config.subtitle' => 'Verwalten Sie die verschiedenen Funktionen des Angebots.',
  'pterodactyl.form.resources.title' => 'Betriebsmittel',
  'pterodactyl.form.resources.memory' => 'Arbeitsspeicher (MB)',
  'pterodactyl.form.core.nest' => 'ID Nest Pterodactylus',
  'pterodactyl.form.core.location' => 'ID Standort Pterodactylus',
  'pterodactyl.form.configurations.title' => 'Konfiguration',
  'pterodactyl.offline' => 'ausgestorben',
  'pterodactyl.online' => 'Angezündet',
  'pterodactyl.failed.alreadycreated' => 'Fehler beim Erstellen des Servers, da er bereits erstellt wurde',
  'pterodactyl.failed.changepkgexist' => 'Das Serverpaket konnte nicht geändert werden, da es nicht vorhanden ist.',
  'pterodactyl.failed.suspendexist' => 'Der Server konnte nicht angehalten werden, da er nicht vorhanden ist.',
  'pterodactyl.failed.createuser' => 'Fehler bei der Benutzererstellung, Fehlercode empfangen: %status_code%',
  'pterodactyl.failed.geteggs' => 'Eidaten konnten nicht abgerufen werden, Fehlercode empfangen: %status_code%',
  'pterodactyl.failed.getserver' => 'Fehler beim Abrufen von Daten auf den Server, Fehlercode empfangen: %status_code%',
  'pterodactyl.failed.createserver' => 'Fehler bei der Servererstellung, Fehlercode empfangen: %status_code%',
  'pterodactyl.failed.suspendserver' => 'Fehler beim Anhalten des Servers, Fehlercode empfangen: %status_code%',
  'pterodactyl.failed.unsuspendserver' => 'Fehler beim Anhalten des Servers, Fehlercode empfangen: %status_code%',
  'pterodactyl.failed.terminateserver' => 'Fehler beim Löschen des Servers, Fehlercode empfangen: %status_code%',
  'pterodactyl.failed.buildserver' => 'Fehler bei der Aktualisierung der Serverversion, Fehlercode empfangen: %status_code%',
  'pterodactyl.failed.startupserver' => 'Fehler beim Serverstart, Fehlercode empfangen: %status_code%',
  'pterodactyl.panel.stop' => 'Ausschalten',
  'pterodactyl.panel.powerstop' => 'Töten',
  'pterodactyl.panel.restart' => 'Neustarten',
  'pterodactyl.adminindex.title' => 'Pterodactylus-Konfiguration',
  'pterodactyl.adminindex.subtitle' => 'Verwalten Sie Ihre Angebotskonfigurationen.',
  'pterodactyl.adminindex.memory' => 'Gedächtnis',
  'pterodactyl.adminindex.disk' => 'Speicherplatz',
  'pterodactyl.adminindex.productname' => 'Produktname',
  'pterodactyl.config.title' => 'Server-Konfiguration',
  'pterodactyl.form.resources.portrange' => 'Port, der dem Server zugewiesen werden soll (Beispiel: 3000-4000)',
  'pterodactyl.form.resources.cpu' => 'CPU-Limit (%)',
  'pterodactyl.form.features.title' => 'Funktionen',
  'pterodactyl.form.features.databases' => 'Datenbanken, die dem Server zugewiesen werden sollen',
  'pterodactyl.form.features.allocations' => 'Zusätzliche Zuordnungen, die dem Server zugewiesen werden sollen',
  'pterodactyl.form.features.backups' => 'Datensicherungen, die dem Server zugewiesen werden sollen',
  'pterodactyl.form.core.title' => 'Information',
  'pterodactyl.form.core.servername' => 'Servername',
  'pterodactyl.form.core.egg' => 'ID Ei Pterodactylus',
];