<?php
/**$
    Pterobox - de_DE
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:11
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'pterobox.cannot.core' => 'Sie können %limit% Kerne nicht überschreiten.',
  'pterobox.cannot.empty' => 'Es ist nicht möglich, einen Wert leer oder 0 festzulegen',
  'pterobox.panel.disk' => 'Speicherplatz',
  'pterobox.config.subtitle' => 'Verwalten Sie die verschiedenen Funktionen des Angebots.',
  'pterobox.form.resources.title' => 'Betriebsmittel',
  'pterobox.form.resources.servers' => 'Anzahl der Server, die erstellt werden können',
  'pterobox.form.resources.cores' => 'CPU-Auslastung (%)',
  'pterobox.form.features.allocations' => 'Zertifikate',
  'pterobox.form.features.backups' => 'Sicherungen',
  'pterobox.form.features.servers' => 'Diener',
  'pterobox.form.features.cores' => 'Herz',
  'pterobox.form.core.title' => 'Information',
  'pterobox.form.core.egg' => 'ID Ei Pterodactylus',
  'pterobox.cannot.database' => 'Sie können %limit% Datenbanken nicht überschreiten.',
  'pterobox.cannot.backup' => 'Sie können %limit% Sicherungen nicht überschreiten.',
  'pterobox.cannot.allocation' => 'Sie können %limit%-Zuordnungen nicht überschreiten.',
  'pterobox.cannot.server' => 'Sie können %limit% Server nicht überschreiten.',
  'pterobox.adminindex.disk' => 'Speicherplatz',
  'pterobox.adminindex.productname' => 'Produktname',
  'pterobox.config.title' => 'Server-Konfiguration',
  'pterobox.form.features.databases' => 'Datenbanken',
  'pterobox.createserver' => 'Erstellen eines Servers',
  'pterobox.updateserver' => 'Ändern des Servers',
  'pterobox.button' => 'Modifizieren',
  'pterobox.servername' => 'Servername',
  'pterobox.used' => 'gebraucht',
  'pterobox.used2' => 'Gebraucht',
  'pterobox.cannot.memory' => 'Sie können %limit% GB Arbeitsspeicher nicht überschreiten.',
  'pterobox.cannot.disk' => 'Sie können %limit% GB Speicherplatz nicht überschreiten.',
  'pterobox.panel.memory' => 'Gedächtnis',
  'pterobox.panel.button' => 'Meinen Server verwalten',
  'pterobox.panel.problem' => 'Haben Sie ein Problem mit dem Hosting?',
  'pterobox.panel.openticket' => 'Eröffnen Sie ein Ticket!',
  'pterobox.panel.information' => 'Immobilien-Info',
  'pterobox.panel.backupswisp' => 'Grenzwert für Backups',
  'pterobox.panel.backupswisphelp' => 'Die Gesamtzahl der Gigabyte, die der Server für seine Sicherungen verwenden kann.',
  'pterobox.adminindex.title' => 'Konfiguration Pterobox',
  'pterobox.adminindex.subtitle' => 'Verwalten Sie Ihre Angebotskonfigurationen.',
  'pterobox.adminindex.memory' => 'Gedächtnis',
  'pterobox.form.resources.memory' => 'Arbeitsspeicher (GB)',
  'pterobox.form.resources.disk' => 'Speicherplatz (GB)',
  'pterobox.form.resources.help' => 'Erhältlich für die gesamte Box',
  'pterobox.form.resources.portrange' => 'Port, der dem Server zugewiesen werden soll (Beispiel: 3000-4000)',
  'pterobox.form.resources.cpu' => 'CPU-Limit (%)',
  'pterobox.form.resources.swap' => 'Tauschen',
  'pterobox.form.resources.swaphelp' => '0 deaktiviert den Swap für den Server. -1 lässt keine Begrenzung zu',
  'pterobox.form.resources.io' => 'E/A-Block',
  'pterobox.form.features.title' => 'Funktionen',
  'pterobox.form.core.nest' => 'ID Nest Pterodactylus',
  'pterobox.form.core.location' => 'ID Standort Pterodactylus',
];