<?php
/**$
    Support - de_DE
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:13
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'department' => 'Abteilung',
  'support.related' => 'Verbundene Dienstleistung/Transaktion',
  'support.admin.department.title' => 'Abteilung',
  'support.admin.department.subtitle' => 'Verwaltung der verschiedenen Support-Abteilungen',
  'support.show.our_reply' => 'Unsere Antwort',
  'support.show.your_reply' => 'Ihre Antwort',
  'support.priority' => 'Priorität',
  'support.priorities.High' => 'Hoch',
  'support.priorities.Medium' => 'Durchschnitt',
  'support.priorities.Low' => 'Schwach',
  'departments' => 'Abteilungen',
  'your_tickets' => 'Ihre Anfragen',
  'new_ticket' => 'Neue Anwendung',
  'reply' => 'Antwort',
  'open_tickets' => 'Offene Anfragen',
  'predefinedreplies' => 'Vordefinierte Antworten',
  'predefinedreply' => 'Voreingestellte Reaktion',
  'support.actions.close' => 'Die Bewerbung wurde soeben geschlossen',
  'support.actions.reply' => 'Die Antwort wurde soeben gepostet',
  'support.table.last_updated' => 'Zuletzt aktualisiert',
  'support.table.close' => 'Schließen',
  'support.table.priority' => 'Priorität',
  'support.table.department' => 'Abteilung',
  'support.table.subject' => 'Betreff',
  'support.admin.ticket.createsubtitle' => 'Öffnen Sie ein Ticket für einen bestimmten Kunden.',
  'support.email.title' => 'Antwort unseres Supports auf Anfrage %subject%',
  'support.email.content' => 'Unser Support hat soeben auf Ihre Bitte um Hilfe reagiert. Sie können es anzeigen, indem Sie auf die Schaltfläche oben klicken.',
  'support.email.button' => 'Mein Ticket',
  'support.show.reopentext' => 'Ihre Bewerbung ist derzeit geschlossen, Sie können sie mit einem Klick auf den Button wieder öffnen.',
  'support.show.reopen' => 'Öffnen Sie die Anwendung erneut',
  'support.show.your_question' => 'Ihre Anfrage',
  'support.department' => 'Abteilung',
  'support.discussion' => 'Diskussion',
  'support.content' => 'Bitten',
  'support.newticket' => 'Neues Ticket',
  'support.submit' => 'Einreichen',
  'tickets' => 'Billette',
  'support.title' => 'Technischer Support',
  'support.messages' => 'Meldungen',
  'support.replied' => 'Ich habe Ihnen geantwortet',
  'support.icon' => 'Ikone',
  'support.informations' => 'Nachrichten',
  'support.actions.reopen' => 'Die Anwendung wurde soeben wieder geöffnet.',
  'support.actions.submit' => 'Die Anwendung wurde soeben geöffnet',
  'support.admin.predefined.title' => 'Vordefinierte Antworten',
  'support.admin.predefined.create' => 'Sie können hier vorgefertigte Antworten <a href="%route%" target="_blank"></a> erstellen',
  'support.admin.predefined.subtitle' => 'Verwalten Sie die verschiedenen vordefinierten Antworten aus dem Support',
  'support.admin.predefined.global' => 'Die Antwort kann allen Mitarbeitern zur Verfügung stehen',
  'support.admin.predefined.tips' => '<strong>[NACHNAME]</strong> - Name des Kunden | <strong>[FIRSTNAME]</strong> - Vorname des Kunden | <strong>[EMAIL] - E-Mail-Adresse</strong> des Kunden |  <strong>[VERWANDT]</strong> Name der zugehörigen Transaktion/Dienstleistung (falls definiert)',
  'support.admin.ticket.title' => 'Unterstützen',
  'support.admin.ticket.subtitle' => 'Verwalten der verschiedenen Support-Tickets',
  'support.show.reply' => 'Antwort',
  'support.show.textarea' => 'Bitte erläutern Sie Ihr Problem so gut wie möglich. 
Geben Sie keine vertraulichen Informationen (Passwörter usw.) heraus, unsere Techniker verfügen über alle notwendigen Informationen, um Ihr Problem zu lösen',
  'support.states.Pending' => 'Anhängig',
  'support.states.Reply Support' => 'Antwort des Supports',
  'support.states.Reply Customer' => 'Antwort des Kunden',
  'support.states.Closed' => 'Geschlossen',
  'support.print' => 'Drucken',
  'support.admin' => 'Mitarbeiter werden per E-Mail benachrichtigt',
  'servicespage.options.manage' => 'Benötigen Sie eine zusätzliche IP-Adresse oder mehr Speicherplatz?',
];