<?php
/**$
    translator - de_DE
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:19
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'translatesitems.positive' => 'Der Wert muss positiv sein.',
  'translatesitems.numeric' => 'Der Wert muss ein gültiger numerischer Wert sein.',
  'translatesitems.between' => 'Der Wert muss zwischen %d und %d liegen.',
  'translatesitems.inArray' => 'Der Wert ist in den folgenden Werten nicht vorhanden: %s',
  'translatesitems.notInArray' => 'Der Wert darf in den folgenden Werten nicht vorhanden sein: %s',
  'translatesitems.arrayHasKey' => 'Das Array muss den Schlüssel %s enthalten.',
  'translatesitems.unique' => 'Der Wert muss in der Datenbank eindeutig sein',
  'translatesitems.arrayHasNotKey' => 'Das Array darf nicht den Schlüssel %s enthalten',
  'translatesitems.filetype' => 'Das Feld ist kein validiertes Format (%s)',
  'translatesitems.maxLength' => 'Der Wert muss weniger als %d Zeichen enthalten.',
  'translatesitems.betweenLength' => 'Der Wert muss zwischen %d und %d Zeichen enthalten.',
  'translatesitems.bannedEmail' => 'Die E-Mail-Adresse oder der Domainname ist gesperrt.',
  'translatesitems.email' => 'Der Wert muss eine gültige E-Mail-Adresse sein.',
  'translatesitems.invalidip' => 'Der Wert muss eine validierte IP-Adresse sein.',
  'translatesitems.url' => 'Bei dem Wert muss es sich um eine verifizierte URL handeln.',
  'translatesitems.domain' => 'Der Wert muss eine gültige Domäne sein.',
  'translatesitems.equals' => 'Der Wert muss mit der Validierung übereinstimmen.',
  'translatesitems.ispassword' => 'Das Passwort muss das aktuelle sein.',
  'translatesitems.isfuture' => 'Das Datum muss in der Zukunft liegen.',
  'translatesitems.startswith' => 'Der Wert muss mit %s beginnen.',
  'translatesitems.endswith' => 'Der Wert muss mit %s enden.',
  'translatesitems.contains' => 'Der Wert muss %s enthalten.',
  'translatesitems.notcontains' => 'Der Wert darf %s nicht enthalten',
  'translatesitems.passwordsecurity' => 'Ihr Passwort ist nicht sicher! Bitte verwenden Sie eine andere',
  'translatesitems.sshpublic' => 'Der SSH-Schlüssel muss ein gültiger Schlüssel sein',
  'translatesitems.boolean' => 'Der Wert muss ein validierter boolescher Wert sein.',
  'translatesitems.int' => 'Der Wert muss eine validierte Zahl sein.',
  'translatesitems.negative' => 'Der Wert muss negativ sein.',
  'translatesitems.max' => 'Die Zahl muss kleiner als %d sein.',
  'translatesitems.min' => 'Die Zahl muss mindestens %d betragen',
  'translatesitems.minLength' => 'Der Wert muss mehr als %d Zeichen enthalten.',
  'translatesitems.license' => 'Diese Lizenz ist ungültig %s',
  'translatesitems.exists' => 'Der Wert muss in der Datenbank vorhanden sein.',
  'translatesitems.ispast' => 'Das Datum muss in der Vergangenheit liegen.',
  'translatesitems.true' => 'Der Wert muss true sein.',
  'translatesitems.false' => 'Der Wert muss false sein.',
  'translatesitems.uploaded' => 'Sie müssen eine Datei hochladen.',
  'translatesitems.required' => 'Der Wert muss erforderlich sein.',
  'translatesitems.empty' => 'Der Wert darf nicht leer sein.',
  'translatesitems.slug' => 'Der Wert muss ein gültiger Slug sein.',
  'translatesitems.phonenumber' => 'Bei dem Wert muss es sich um eine gültige Telefonnummer handeln.',
  'translatesitems.postcode' => 'Der Wert muss eine verifizierte Postleitzahl (%s) sein.',
  'translatesitems.numericOrZero' => 'Der Wert muss eine gültige Zahl oder gleich Null sein.',
  'translatesitems.positiveOrZero' => 'Der Wert muss positiv oder gleich Null sein.',
  'translatesitems.ostemplate' => 'Sie müssen sich zwischen einer Vorlage oder einem Betriebssystem entscheiden.',
  'translatesitems.domainIsAlreadyRegistered' => 'Diese Domain ist bereits registriert',
];