<?php
/**$
    Virtualizor - de_DE
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:15
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'virtualizor.panel.stop' => 'Ausschalten',
  'virtualizor.panel.powerstop' => 'Töten',
  'virtualizor.panel.restart' => 'Neustarten',
  'virtualizor.panel.os_name' => 'KNOCHEN',
  'virtualizor.panel.openticket' => 'Eröffnen Sie ein Ticket!',
  'virtualizor.panel.uptime' => 'Verfügbarkeit',
  'virtualizor.panel.reset' => 'Neuinstallation',
  'virtualizor.admin.title' => 'Konfiguration Virtualizor',
  'virtualizor.productname' => 'Produktname',
  'virtualizor.graph' => 'Grafik',
  'virtualizor.panel.button' => 'Verbindung',
  'virtualizor.panel.start' => 'Licht',
  'virtualizor.panel.in' => 'Ankommend',
  'virtualizor.panel.out' => 'Aufgeschlossen',
  'virtualizor.panel.usage' => 'Verwendung',
  'virtualizor.panel.site' => 'Öffnen Sie die Website',
  'virtualizor.panel.information' => 'Immobilien-Info',
  'virtualizor.panel.problem' => 'Haben Sie ein Problem mit dem Hosting?',
  'virtualizor.converter.gb' => 'Geben Sie Ihre Nummer in GB ein',
  'kvm' => 'KVM (KVM)',
  'openvz' => 'OpenVZ',
  'lxc' => 'LXC',
  'virtualizor.hostname' => 'Gastgeber',
  'virtualizor.os' => 'KNOCHEN',
  'virtualizor.offline' => 'ausgestorben',
  'virtualizor.online' => 'Angezündet',
  'virtualizor.planname' => 'Name des Plans',
  'virtualizor.panel.bandwidth' => 'Bandbreite',
  'virtualizor.panel.ram' => 'WIDDER',
  'virtualizor.panel.virt' => 'Virtualisierung',
  'virtualizor.panel.cpu' => 'CPU',
  'virtualizor.panel.disk' => 'Speicherplatz',
  'virtualizor.panel.cores' => 'Herz',
  'virtualizor.admin.subtitle' => 'Verwalten Sie Ihre Angebotskonfigurationen.',
  'virtualizor.admin.planname' => 'Name des Plans',
  'virtualizor.config.title' => 'Richten Sie Ihr Angebot ein',
  'virtualizor.config.subtitle' => 'Verwalten Sie die Funktionen des Angebots.',
  'virtualizor.converter.title' => 'Konverter',
  'virtualizor.converter.mb' => 'Geben Sie Ihre Nummer in MB ein',
  'virtualizor.choosehostname' => 'Wählen Sie einen benutzerdefinierten Hostnamen',
];