<?php
/**$
    VirtualizorCloud - de_DE
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:16
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'virtualizorcloud.offline' => 'ausgestorben',
  'virtualizorcloud.online' => 'Angezündet',
  'virtualizorcloud.planname' => 'Name des Plans',
  'virtualizorcloud.graph' => 'Grafik',
  'virtualizorcloud.panel.disk' => 'Speicherplatz',
  'virtualizorcloud.panel.cores' => 'Herz',
  'virtualizorcloud.panel.in' => 'Ankommend',
  'virtualizorcloud.panel.out' => 'Aufgeschlossen',
  'virtualizorcloud.form.resources.priority' => 'I/O-Priorität (OpenVZ)',
  'virtualizorcloud.form.resources.vnc' => 'VNC-fähig (KVM)',
  'virtualizorcloud.form.resources.speed' => 'Netzwerkgeschwindigkeit in KB/s (0 GB/s oder leer ohne Limit)',
  'virtualizorcloud.form.resources.server' => 'Server',
  'virtualizorcloud.form.stockage.space' => 'Speicherplatz (GB)',
  'virtualizorcloud.form.cpu.cores' => 'Herz',
  'virtualizorcloud.form.cpu.units' => 'Einheit',
  'virtualizorcloud.form.cpu.cpu' => 'CPU %',
  'virtualizorcloud.form.ips.internalips' => 'Anzahl der internen IP-Adressen',
  'virtualizorcloud.form.ips.ips' => 'Anzahl der IPs',
  'virtualizorcloud.admin.title' => 'Konfiguration Virtualizor',
  'virtualizorcloud.admin.subtitle' => 'Verwalten Sie Ihre Angebotskonfigurationen.',
  'virtualizorcloud.admin.planname' => 'Name des Plans',
  'virtualizorcloud.config.title' => 'Richten Sie Ihr Angebot ein',
  'virtualizorcloud.hostname' => 'Gastgeber',
  'virtualizorcloud.os' => 'KNOCHEN',
  'virtualizorcloud.panel.restart' => 'Neustarten',
  'virtualizorcloud.panel.os_name' => 'KNOCHEN',
  'virtualizorcloud.panel.bandwidth' => 'Bandbreite',
  'virtualizorcloud.panel.ram' => 'WIDDER',
  'virtualizorcloud.panel.virt' => 'Virtualisierung',
  'virtualizorcloud.panel.cpu' => 'CPU',
  'virtualizorcloud.panel.reset' => 'Neuinstallation',
  'virtualizorcloud.form.resources.title' => 'Betriebsmittel',
  'virtualizorcloud.form.resources.disk' => 'Speicherplatz (GB)',
  'virtualizorcloud.form.resources.io' => 'E/A-Block',
  'virtualizorcloud.form.resources.bandwidth' => 'Bandbreite (0 GB oder leer für keine Begrenzung)',
  'virtualizorcloud.form.resources.inodes' => 'INode (OpenVZ)',
  'virtualizorcloud.form.resources.network_speed' => 'Netzwerkgeschwindigkeit in MB/s',
  'virtualizorcloud.form.resources.upload_speed' => 'Download-Geschwindigkeit in MB/s',
  'virtualizorcloud.form.stockage.title' => 'Lagerung',
  'virtualizorcloud.form.stockage.ram' => 'MB of RAM (KVM, LXC)',
  'virtualizorcloud.form.stockage.guaranteed' => 'RAM-Garantie (MB)',
  'virtualizorcloud.form.stockage.burstable' => 'Speicherfähiger Arbeitsspeicher (OpenVZ)',
  'virtualizorcloud.form.configurations.group' => 'Gruppe',
  'virtualizorcloud.form.configurations.vnc' => 'VNC',
  'virtualizorcloud.form.ips.ip6subnet' => 'Anzahl der IPV6-Adressen',
  'virtualizorcloud.form.ips.ip6' => 'Anzahl der IPv6-Adressen des Subnetzes',
  'virtualizorcloud.productname' => 'Produktname',
  'virtualizorcloud.choosehostname' => 'Wählen Sie einen benutzerdefinierten Hostnamen',
  'virtualizorcloud.panel.button' => 'Verbindung',
  'virtualizorcloud.panel.start' => 'Anfangen',
  'virtualizorcloud.panel.stop' => 'Ausschalten',
  'virtualizorcloud.panel.powerstop' => 'Töten',
  'virtualizorcloud.panel.usage' => 'Verwendung',
  'virtualizorcloud.panel.site' => 'Öffnen Sie die Website',
  'virtualizorcloud.panel.information' => 'Immobilien-Info',
  'virtualizorcloud.panel.problem' => 'Haben Sie ein Problem mit dem Hosting?',
  'virtualizorcloud.panel.openticket' => 'Eröffnen Sie ein Ticket!',
  'virtualizorcloud.panel.uptime' => 'Verfügbarkeit',
  'virtualizorcloud.form.resources.ip6' => 'IPv6-Schnittstelle',
  'virtualizorcloud.form.resources.ip6subnet' => 'IP6-Subnetz',
  'virtualizorcloud.form.resources.ips' => 'IP',
  'virtualizorcloud.form.resources.oses' => 'Verfügbare Bones (durch Kommas getrennt)',
  'virtualizorcloud.form.resources.internalips' => 'Interne IP-Adresse',
  'virtualizorcloud.form.resources.portrange' => 'Port, der dem Server zugewiesen werden soll (durch Kommas getrennt)',
  'virtualizorcloud.form.cpu.title' => 'CPU',
  'virtualizorcloud.form.converter.title' => 'Konverter',
  'virtualizorcloud.form.converter.mb' => 'Geben Sie Ihre Nummer in MB ein',
  'virtualizorcloud.form.converter.gb' => 'Geben Sie Ihre Nummer in GB ein',
  'virtualizorcloud.form.configurations.title' => 'Konfiguration',
  'virtualizorcloud.form.configurations.server' => 'Server',
  'virtualizorcloud.config.subtitle' => 'Verwalten Sie die Funktionen des Angebots.',
  'virtualizorcloud.converter.title' => 'Konverter',
  'virtualizorcloud.converter.mb' => 'Geben Sie Ihre Nummer in MB ein',
  'virtualizorcloud.converter.gb' => 'Geben Sie Ihre Nummer in GB ein',
];