<?php
/**$
    Welcome - de_DE
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:16
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'why_choose_us' => 'Warum sollten Sie sich für uns entscheiden?',
  'demonstration' => 'Demonstration',
  'demonstrationcontent' => 'Sie möchten Ihren zukünftigen Kundenbereich entdecken? Greifen Sie auf eine Demoversion zu!',
  'community.title' => 'Gemeinschaft',
  'community.twitter.title' => 'Zwitschern',
  'community.twitter.description' => 'Sie können uns auf Twitter folgen, um als Erster über zukünftige Updates informiert zu werden.',
  'community.twitter.seemore' => 'Sehen Sie sich unsere Tweets an',
  'themepage.larium.administration.description' => 'Sie müssen Ihren FTP-Zugang nicht öffnen, sondern können direkt aus der Administration <span class="text-primary fw-bold">CLIENTXCMS</span> Ihre',
  'themepage.larium.administration.list.position.title' => 'Positionen',
  'themepage.larium.administration.list.position.content' => 'Ändern Sie die Positionen der Elemente (Abschnitte, Menüs, Schieberegler, Footer-Links) mit einem einfachen Klick.',
  'themepage.larium.administration.list.component.title' => 'Automatisierte Komponenten',
  'themepage.list.visual.title' => 'Keine optischen Veränderungen',
  'themepage.list.visual.content' => 'Ihre Kunden sehen den Unterschied zwischen Ihrer Händlerseite und ihrem Kundenbereich nicht.',
  'themepage.list.components.title' => 'Interaktive Komponenten',
  'themepage.list.components.content' => 'Hinzufügen, Bearbeiten, Ändern der Position von Komponenten auf Seiten.',
  'pricing.description' => 'Beginnen Sie mit <span class="text-primary font-weight-bold"> CLIENTXCMS zu arbeiten </span> und starten Sie noch heute Ihr Webhosting-Geschäft.',
  'pricing.formuls.hostownserver' => 'Gehostet auf Ihrem eigenen Server',
  'pricing.formuls.custom' => 'Anpassbar und konfigurierbar',
  'pricing.formuls.sourcecode' => 'Inklusive Quellcode',
  'pricing.formuls.withall' => '%count% Kostenlose kostenpflichtige Module',
  'pricing.install.title' => 'Installation & Konfiguration',
  'pricing.install.count' => 'pro Installation',
  'pricing.embedding.title' => 'Einbetten Ihrer Website',
  'pricing.embedding.count' => 'durch Integration',
  'pricing.embedding.content' => 'Stellen Sie sicher, dass Ihr Kundenbereich ohne Übergang mit Ihrer Website identisch ist!',
  'pricing.mail.title' => 'Mailserver',
  'pricing.mail.content' => 'Bestellen Sie einen SMTP-Server für Ihr Unternehmen direkt bei CLIENTXCMS.',
  'for.services.notincluded' => 'Zusatzmodul',
  'darktheme' => 'Nacht-Modus',
  'features.translated.title' => 'Vollständig übersetzt',
  'features.configurable.content' => 'Konfigurieren Sie Ihre Produkte, Server und Optionen, um CLIENTXCMS nach Ihren Wünschen anzupassen.',
  'features.security.title' => 'Sicherheit',
  'features.security.content' => 'CLIENTCMS entwickelt sich ständig weiter und verbessert die Sicherheit von Tag zu Tag.',
  'features.support.title' => 'Persönlicher Support',
  'features.support.content' => 'Ein Team, das Ihnen jeden Tag zur Verfügung steht, um Ihnen zu helfen und Ihre Fragen zu beantworten.',
  'home' => 'Empfang',
  'shopmore' => 'Mehr bestellen',
  'reload' => 'Nachladen',
  'our_modules' => 'Unsere Module',
  'decovery_our_modules' => 'Entdecken Sie unsere Module',
  'backtohome' => 'Zurück zur Startseite',
  'addthemeandfinish' => 'Thema hinzufügen & Finish',
  'why_choose_us_sub' => 'CLIENTXCMS ist für die neue Generation innovativer Hosts gemacht. Weniger komplizierte Einrichtung, schnellere Erstellung.',
  'emailtemplates.title' => 'Unsere E-Mail-Vorlagen',
  'emailtemplates.subtitle' => 'Passen Sie Ihren Kundenbereich <span class="text-primary font-weight-bold"> CLIENTXCMS mit E-Mail-Vorlagen an</span>, die zu Ihrem Unternehmen passen',
  'licensecheckerpage.howtouse' => 'So verwenden Sie dieses Tool:',
  'licensecheckerpage.first' => 'Geben Sie <b>nur</b> den Domainnamen ein, auf dem CLIENTXCMS installiert ist',
  'licensecheckerpage.second' => 'Wenn es z. B. eine @ https://clients.exemple.com-Installation gab, geben Sie einfach <b>clients.exemple.com</b> als Domäne ein',
  'licensecheckerpage.third' => 'Die Domain darf weder <b>www</b> noch <b>https://</b> enthalten.',
  'cookieconsent' => 'Diese Website verwendet Cookies, um Ihnen eine Benutzererfahrung zu bieten. Durch die Nutzung erklären Sie sich mit unserer <a href=\'/\' target=\'_blank\' class=\'text-success h6\'> Verwendung von Cookies einverstanden</a>',
  'welcome.heading' => 'Neue Generation von Hosting-Providern',
  'welcome.description' => 'Starten Sie Ihr Webhosting-Geschäft mit unseren Tools.',
  'welcome.refund' => 'Mit dem Absenden dieses Formulars erklären Sie sich mit unseren Verkaufs- und Nutzungsbedingungen einverstanden.',
  'community.discord.title' => 'Zwietracht',
  'community.discord.description' => 'Wir nutzen Discord, um Support zu leisten und euer Feedback zu erhalten, damit wir zukünftige Updates planen können.',
  'community.discord.seemore' => 'Treten Sie unserem Server bei',
  'themepage.title' => 'Wir haben<br/>
                Ihre Website und Ihr Kundenbereich',
  'themepage.larium.title' => 'Beliebig anpassbar',
  'themepage.larium.subtitle' => 'Es ist nicht erforderlich, eine Storefront-Site zu verwalten, <span class="text-primary fw-bold">CLIENTXCMS</span> enthält es mit einer Ein-Klick-Installation und einer vereinfacht konfigurierbaren',
  'themepage.larium.subtitle2' => 'Vereinfachen Sie Ihr Leben für weniger Geld mit Larium',
  'themepage.larium.rlt.title' => 'RTL & LTR',
  'themepage.larium.rlt.description' => 'Wählen Sie die <span class="text-primary fw-bold">Position des Client-Navigationsmenüs</span> aus den Designeinstellungen aus.',
  'themepage.larium.nightmode.title' => 'Tag- und Nachtmodus',
  'themepage.larium.nightmode.description' => 'Wählen Sie den <span class="text-primary fw-bold">Modus</span> Ihres Themas Night or Day',
  'themepage.larium.administration.title' => 'Management aus der Verwaltung',
  'themepage.larium.administration.list.component.content' => 'Komponenten können Informationen wie Anzeigen oder Produktgruppen dynamisch anzeigen.',
  'themepage.larium.administration.list.translation.title' => 'Übersetzungs-Komponenten',
  'themepage.larium.administration.list.translation.content' => 'Komponenten können entsprechend der Sprache des Benutzers übersetzt werden.',
  'themepage.larium.administration.list.flex.title' => 'Flexibilität',
  'themepage.larium.administration.list.flex.content' => 'Fügen Sie so viele Menüs, Abschnitte, soziale Netzwerke, Schieberegler oder Fußzeilenlinks hinzu, wie Sie möchten.',
  'themepage.larium.administration.list.footer' => 'Footer-Verwaltung',
  'themepage.larium.administration.list.sections' => 'Sektionsleitung',
  'themepage.larium.administration.list.menus' => 'Menü-Verwaltung',
  'themepage.larium.administration.list.info' => 'Social Media & Informationsmanagement',
  'themepage.larium.administration.list.sliders' => 'Slider-Verwaltung auf der Startseite',
  'themepage.list.synchronization.title' => 'Synchronisierte Produkte',
  'themepage.list.synchronization.content' => 'Sie müssen Ihre Beschreibungen nicht mehr an zwei Stellen bearbeiten, alles ist synchron.',
  'themepage.list.personalization.title' => 'Anpassung',
  'themepage.list.personalization.content' => 'Bearbeiten Sie ganz einfach das Navigationsmenü Ihres Unternehmens oder die sozialen Netzwerke.',
  'themepage.subtitle' => 'Profitieren Sie von einer Showcase-Site, die in <span class="text-primary fw-bold">CLIENTXCMS enthalten ist, einfach</span> zu installieren und nach Belieben konfigurierbar ist.',
  'themepage.notincluded' => 'Das Thema ist nicht in unseren Standardplänen enthalten. <a href=\'/Larium\'>Zum Kauf verfügbar</a>.',
  'modulesfeatures.title' => 'Unsere offiziellen Module',
  'modulesfeatures.title2' => 'Benötigen Sie weitere Module?',
  'modulesfeatures.description2' => 'Weitere Module <span class="text-primary font-weight-bold"> CLIENTXCMS </span> sind im Shop verfügbar!',
  'modulesfeatures.description' => 'Beginnen Sie mit <span class="text-primary font-weight-bold"> CLIENTXCMS und mit </span> von uns für Sie entwickelten Modulen.',
  'modulesfeatures.button' => 'Offizielle CLIENTXCMS-Dokumentation',
  'modulesfeatures.documentation' => 'Finden Sie die Antworten auf all Ihre Fragen ganz einfach mit unserer Dokumentation!',
  'documentation.title' => 'Dokumentation',
  'pricing.title' => 'Grundsteuer',
  'pricing.formuls.unlimited' => 'Unbegrenzte Anzahl von Kunden',
  'pricing.formuls.customers' => 'Bis zu %<strong>count%</strong> Kunden',
  'pricing.formuls.domain' => '1 Autorisierte Domain',
  'pricing.formuls.nothostownserver' => 'Gehostet auf unseren Servern',
  'pricing.formuls.modulesfree' => '<strong>%count%</strong> Kostenpflichtige Module Angeboten',
  'pricing.formuls.modulefree' => '1 kostenloses kostenpflichtiges Modul',
  'pricing.formuls.domains' => '%count% Zulässige Domänen',
  'pricing.formuls.support' => '%support% Support inklusive',
  'pricing.formuls.nosourcecode' => 'Quellcode nicht enthalten',
  'pricing.formuls.discord' => 'Grade & Private Rooms auf unserem Discord',
  'pricing.formuls.installation' => 'Installation durch unser Team',
  'pricing.formuls.with' => 'Freie Module zählen',
  'pricing.formuls.themes' => 'Anzahl der angebotenen Themen',
  'pricing.install.dedicated' => 'VPS/Dediziert',
  'pricing.install.content' => 'Sorgen Sie für eine reibungslose und erfolgreiche Installation und lassen Sie CLIENTXCMS von unserem Team für Sie installieren und konfigurieren.',
  'pricing.integration.title' => 'Einbetten Ihrer Website',
  'pricing.integration.count' => 'durch Integration',
  'pricing.integration.content' => 'Stellen Sie sicher, dass Ihr Kundenbereich ohne Übergang mit Ihrer Website identisch ist!',
  'pricing.hosting.title' => 'Webhosting',
  'pricing.hosting.our_hosting' => 'Unser Webhosting',
  'pricing.hosting.content' => 'Bestellen Sie Ihr Webhosting für Ihr Unternehmen direkt bei CLIENTXCMS.',
  'pricing.reseller.title' => 'Web-Wiederverkäufer',
  'pricing.reseller.content' => 'Bestellen Sie einen Web-Reseller für Ihr Unternehmen direkt bei CLIENTXCMS.',
  'pricing.mailer.title' => 'E-Mail-Server',
  'pricing.mailer.content' => 'Bestellen Sie einen SMTP-Server für Ihr Unternehmen direkt bei CLIENTXCMS.',
  'for.services.included' => 'Verfügbar für alle',
  'features.translated.content' => 'Alle CLIENTXCMS sind in mehrere Sprachen übersetzt, was es ermöglicht, Kunden aus der ganzen Welt zu gewinnen.',
  'features.developper.title' => 'Entwicklerfreundlich',
  'features.developper.content' => 'Wir sind gut recherchiert und unsere Community-Ressourcen machen es einfach, CLIENTXCMS zu entwickeln und anzupassen.',
  'features.responsive.content' => 'Der Kundenbereich eignet sich für jede Art von Bildschirm, um die Benutzererfahrung zu verbessern.',
  'features.tasks.title' => 'Geplante Aufgaben',
  'features.tasks.content' => 'Wiederkehrende Aufgaben werden ausgeführt, um E-Mails zu versenden oder Dienste automatisch zu verwalten.',
  'features.easy.title' => 'Vereinfachung',
  'features.easy.content' => 'Das CMS ist so einfach und intuitiv wie möglich gestaltet und eignet sich sowohl für Anfänger als auch für erfahrene Benutzer.',
  'features.installation.title' => '1-Klick-Installation',
  'features.installation.content' => 'Die Module können in Ihrem Administrationsbereich Ihres Kundenbereichs heruntergeladen werden. Dadurch wird eine aufwendige Installation vermieden.',
  'features.configurable.title' => 'Konfigurierbar',
  'features.title' => 'Unsere Lösungen',
  'features.description' => 'Beginnen Sie mit <span class="text-primary font-weight-bold">CLIENTXCMS</span>, das alles bietet, was Sie brauchen, um Gewinne zu erzielen, neue Kunden zu gewinnen und eine moderne Benutzeroberfläche zu haben.',
  'pricing.ctxhosting.title' => 'Wir bieten vorgefertigte Pläne für Hosting-Anbieter an',
  'pricing.ctxhosting.content' => 'CTXHosting ist unser Angebot an hochwertigem Hosting mit Angeboten für Hosting-Anbieter ab <strong>XX€/Monat</strong>',
  'pricing.ctxhosting.domain' => 'Kaufbarer .fr-Domainname',
  'pricing.ctxhosting.included' => 'CLIENTXCMS im Angebot enthalten & vorkonfiguriert',
  'pricing.ctxhosting.info' => 'Managed Services & Hilfe',
  'pricing.ctxhosting.installation' => 'Installation innerhalb von 48 Arbeitsstunden',
  'pricing.ctxhosting.start' => 'ab XX€/Monat',
  'pricing.ctxhosting.addon' => 'Wir bieten VPS- oder PBS-HDD-Speicherangebote für Ihre Kunden an.',
];