<?php
/**$
    Wisp - de_DE
    CLIENTXCMS Translator system - Exported on 2024-02-03 13:40:17
    If you want to help you translate into your language, you can contact us via our support.
*/
return [
  'Wisp.failed.linkserver' => 'Kennwortänderung fehlgeschlagen, da der Verbindungsserver nicht vorhanden ist',
  'Wisp.failed.retrieveuser' => 'Benutzerwiederherstellung fehlgeschlagen, Fehlercode empfangen: %status_code%',
  'Wisp.failed.changepwd' => 'Kennwortänderung fehlgeschlagen, Fehlercode empfangen: %status_code%',
  'Wisp.panel.openticket' => 'Eröffnen Sie ein Ticket!',
  'Wisp.panel.information' => 'Immobilien-Info',
  'Wisp.panel.start' => 'Anfangen',
  'Wisp.form.resources.title' => 'Betriebsmittel',
  'Wisp.form.resources.memory' => 'Arbeitsspeicher (MB)',
  'Wisp.form.resources.disk' => 'Speicherplatz (MB)',
  'Wisp.form.configurations.title' => 'Konfiguration',
  'Wisp.form.configurations.image' => 'Bild-Docker',
  'Wisp.form.configurations.startup' => 'Befehl "Starten"',
  'Wisp.failed.alreadycreated' => 'Fehler beim Erstellen des Servers, da er bereits erstellt wurde',
  'Wisp.failed.changepkgexist' => 'Das Serverpaket konnte nicht geändert werden, da es nicht vorhanden ist.',
  'Wisp.failed.suspendexist' => 'Der Server konnte nicht angehalten werden, da er nicht vorhanden ist.',
  'Wisp.failed.unsuspendexist' => 'Das Aufheben der Serversperre ist fehlgeschlagen, da er nicht vorhanden ist.',
  'Wisp.failed.terminateexist' => 'Der Server konnte nicht gelöscht werden, da er nicht vorhanden ist.',
  'Wisp.failed.satisfying' => 'Es konnten keine Knoten gefunden werden, die die Nachfrage befriedigen',
  'Wisp.failed.pwdempty' => 'Das Passwort darf nicht leer sein',
  'Wisp.failed.suspendserver' => 'Fehler beim Anhalten des Servers, Fehlercode empfangen: %status_code%',
  'Wisp.failed.unsuspendserver' => 'Fehler beim Anhalten des Servers, Fehlercode empfangen: %status_code%',
  'Wisp.failed.terminateserver' => 'Fehler beim Löschen des Servers, Fehlercode empfangen: %status_code%',
  'Wisp.failed.buildserver' => 'Fehler bei der Aktualisierung der Serverversion, Fehlercode empfangen: %status_code%',
  'Wisp.failed.startupserver' => 'Fehler beim Serverstart, Fehlercode empfangen: %status_code%',
  'Wisp.panel.disk' => 'Speicherplatz',
  'Wisp.panel.memory' => 'Gedächtnis',
  'Wisp.panel.button' => 'Meinen Server verwalten',
  'Wisp.panel.problem' => 'Haben Sie ein Problem mit dem Hosting?',
  'Wisp.adminindex.subtitle' => 'Verwalten Sie Ihre Angebotskonfigurationen.',
  'Wisp.adminindex.memory' => 'Gedächtnis',
  'Wisp.adminindex.disk' => 'Speicherplatz',
  'Wisp.adminindex.productname' => 'Produktname',
  'Wisp.migrate.title' => 'Irrlicht der Migration',
  'Wisp.migrate.subtitle' => 'Verwenden Sie diese Seite, um Ihre Pterodactyl-Konfigurationen zu Wisp zu migrieren.',
  'Wisp.migrate.info' => 'Diese Aktion ändert die Produkttypen und migriert die Konfigurationen vom Pterodactyl-Modul zum Wisp-Modul.',
  'Wisp.config.title' => 'Server-Konfiguration',
  'Wisp.config.subtitle' => 'Verwalten Sie die verschiedenen Funktionen des Angebots.',
  'Wisp.form.features.title' => 'Funktionen',
  'Wisp.form.features.databases' => 'Datenbanken, die dem Server zugewiesen werden sollen',
  'Wisp.form.features.backups' => 'Größenbeschränkung für Sicherungen (MB)',
  'Wisp.form.features.allocations' => 'Allokation (MB)',
  'Wisp.form.core.title' => 'Information',
  'Wisp.form.core.servername' => 'Servername',
  'Wisp.form.core.egg' => 'ID Ei Wisp',
  'Wisp.form.core.nest' => 'ID Nest Wisp',
  'Wisp.form.core.location' => 'ID-Standort Wisp',
  'Wisp.form.converter.gb' => 'Geben Sie Ihre Nummer in GB ein',
  'Wisp.offline' => 'ausgestorben',
  'Wisp.online' => 'Angezündet',
  'Wisp.failed.createuser' => 'Fehler bei der Benutzererstellung, Fehlercode empfangen: %status_code%',
  'Wisp.failed.geteggs' => 'Eidaten konnten nicht abgerufen werden, Fehlercode empfangen: %status_code%',
  'Wisp.failed.getserver' => 'Fehler beim Abrufen von Daten auf den Server, Fehlercode empfangen: %status_code%',
  'Wisp.failed.createserver' => 'Fehler bei der Servererstellung, Fehlercode empfangen: %status_code%',
  'Wisp.panel.stop' => 'Ausschalten',
  'Wisp.panel.powerstop' => 'Töten',
  'Wisp.panel.restart' => 'Neustarten',
  'Wisp.adminindex.title' => 'Konfigurieren von Wisp',
  'Wisp.form.resources.swap' => 'Tauschen',
  'Wisp.form.resources.io' => 'E/A-Block',
  'Wisp.form.resources.portrange' => 'Port, der dem Server zugewiesen werden soll (durch Kommas getrennt)',
  'Wisp.form.resources.cpu' => 'CPU-Limit (%)',
  'Wisp.form.configurations.oomkiller' => 'OOM-Killer deaktivieren',
  'Wisp.form.configurations.dedicatedip' => 'Dedizierte IP-Adresse',
  'Wisp.form.converter.title' => 'Konverter',
  'Wisp.form.converter.mb' => 'Geben Sie Ihre Nummer in MB ein',
  'wisp.admin.migratebtn' => 'Migrationsgebiet',
];